spinnaker/kork

- build.gradle
also removes some redundant build config (already applied by the
project plugin)
> pins version of spinnaker-dependencies

- kork-cassandra/kork-cassandra.gradle
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/AstyanaxComponents.java
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/ClusterHostSupplierFactory.java
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/DefaultAstyanaxKeyspaceFactory.java
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/EurekaHostSupplier.java
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/KeyspaceConnectionPoolMonitorFactory.java
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/KeyspaceInitializer.java
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/SpectatorConnectionPoolMonitor.java
- kork-cassandra/src/test/groovy/com/netflix/spinnaker/kork/astyanax/AstyanaxComponentsSpec.groovy
- kork-cassandra/src/test/java/com/netflix/spinnaker/kork/astyanax/DefaultAstyanaxKeyspaceFactoryTest.java
Makes kork-cassandra more configurable/tunable for production Cassandra clients
* ConnectionPoolConfiguration and AsytanaxProperties are bound via `@ConfigurationProperties`
* Allows a host supplier for ring discovery
* provides an optional EurekaHostSupplier to discover nodes via Eureka
Closes #12 (Rebased on top of it)
@ajordens ptal
> Cassandra config update

- kork-core/src/main/java/com/netflix/spinnaker/kork/aws/AwsMetricsSupport.java
@anotherchrisberry PTAL addresses exceptions we were seeing this morning
> Add some defensive checks around spectator tag generation for AWS backoff/retry instrumentation

- kork-web/kork-web.gradle
- kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/Blacklist.java
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingJSSESocketFactory.java
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingSSLImplementation.java
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingX509TrustManager.java
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/ReloadingFileBlacklist.java
- kork-web/src/test/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingX509TrustManagerSpec.groovy
- kork-web/src/test/groovy/com/netflix/spinnaker/tomcat/x509/ReloadingFileBlacklistSpec.groovy
This is a bit convoluted due to what it takes to wire in the TrustManager to tomcat
This exposes a `server.ssl.crlFile` configuration property which is configured onto the tomcat connector.
That can either be the path to a legitimate CRL file, in which case the standard Tomcat CRL handling will apply.
Alternatively this can be the path to a custom blacklist file. To configure this way, prefix the path with `blacklist:`
E.g. in the relevant yaml file:
````yaml
server:
ssl:
crlFile: blacklist:/path/to/my/blacklist
````
The custom blacklist takes the form of one entry per line following
````
certificate issuer x500 name:::certificate serial number
````
e.g.
````
OU=Some OU, O=My Org, CN=My CA, L=Where Waldo is, ST=CA, C=US:::12345
````
A client presented certificate will be compared against …
> Adds support for configuring CRL or custom blacklisting on tomcat SSL

- build.gradle
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/ReloadingFileBlacklist.java
Using Files.lines returns a Stream that has to be explicitly closed, switched to Files.readAllLines since we are going to process them all anyway..
> fixes open file leak in ssl blacklist reading

- kork-stackdriver/kork-stackdriver.gradle
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/ConfigParams.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MetricDescriptorCache.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MonitoredResourceBuilder.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/StackdriverWriter.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/MetricDescriptorCacheTest.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/MonitoredResourceBuilderTest.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/StackdriverWriterTest.java
@duftler 
This PR is for a module intended for spectator but being placed here for the initial release to simplify initial integration with spinnaker as well as ongoing maintenance until the integration has a chance to stabilize and spinnaker catches up to spectator.
I am going to layer the KorkConfig on top of this in a followup PR. In the long term, this module would only be the KorkConfig and this PR would be refactored out into a spectator/spectator-ext-stackdriver. I think it will be easiest and simplest between now and then to just keep everything here. The java namespace I use for this PR pretends this is in spectator, not kork.
This StackdriverWriter dumps a SpectatorRegistry into Stackdriver Time Series data.
It is based on a runtime conversion, making up Stackdriver schemas on …
> Added stackdriver writer.

- build.gradle
- kork-stackdriver/kork-stackdriver.gradle
- kork-stackdriver/src/main/java/com/netflix/spinnaker/config/StackdriverConfig.java
- settings.gradle
@cfieber 
This is the PR from earlier this week. I went to update it against head and did something that caused the PR to get dropped for some reason.
This adds a bean that can get picked up by all the microservices to add stackdriver support in (false by default). I'd like it to also add in the web metrics API I added into spectator 0.41 but commented it out because spinnaker is only on 0.36. I originally wrote it against the source so it had been working until I stopped building against source and started consuming spectator as spinnaker dependencies. I'm leaving it in.
There are a couple comments in the config with questions to you basically asking whether I can delete the commented out block or if in fact there is an issue I need to consider. Should be straightforward.
Thanks.
> Adds Stackdriver config

- kork-web/kork-web.gradle
- kork-web/src/main/groovy/com/netflix/spinnaker/config/ResolvedEnvironmentEndpoint.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy
- kork-web/src/main/groovy/org/springframework/boot/actuate/endpoint/ResolvedEnvironmentEndpoint.groovy
A super handy debugging tool, `/resolveEnv` is different from the `/env` endpoint, which potentially lists the same value multiple times across different PropertySources. This endpoint prints the value once fully resolved.
Example output snippet from Gate:
```
{
...
"server.address": "localhost",
"server.port": "8084",
"services.bakery.allowMissingPackageInstallation": "false",
"services.bakery.baseUrl": "http://localhost:8087",
"services.bakery.extractBuildDetails": "true",
"services.bakery.host": "localhost",
"services.bakery.port": "8087",
"services.cassandra.cluster": "CASS_SPINNAKER",
"services.cassandra.embedded": "false",
"services.cassandra.host": "localhost",
"services.cassandra.port": "9042",
"services.clouddriver.aws.udf.enabled": "true",
"services.clouddriver.baseUrl": …
```
> Adds /resolvedEnv endpoint

- build.gradle
- kork-core/src/main/java/com/netflix/spinnaker/kork/metrics/SpectatorConfiguration.java
- kork-swagger/kork-swagger.gradle
- kork-web/kork-web.gradle
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingJSSESocketFactory.java
Using the update to spinnaker-dependencies, migrate kork to Spring Boot 1.4 and related dependencies
NOTE: Spring Boot 1.4 automatically uses Tomcat 8.5.5. In 8.5, several APIs were refactored including JSSESocketFactory. This patch pins Tomcat to 8.0.24, latest stable version of 8.0 until this refactoring can be dealt with.
> Upgrade to Spring Boot 1.4

- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/ConfigParams.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MetricDescriptorCache.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MonitoredResourceBuilder.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/StackdriverWriter.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/MetricDescriptorCacheTest.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/StackdriverWriterTest.java
@lwander 
If running on gce, you have to store metrics in the project of the managed
resources so force the project. But still need to configure the project if
you are not on gce (and thus dont have a gce managed resource).
When transforming [timer] metrics, lookup the hints for the original metric
name, not the transformed one.
> Stackdriver fixes.

- .gitignore
- build.gradle
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/AstyanaxComponents.java
- kork-cassandra/src/main/java/com/netflix/spinnaker/kork/astyanax/CassandraConfigurationProperties.java
- kork-cassandra/src/test/java/com/netflix/spinnaker/kork/astyanax/DefaultAstyanaxKeyspaceFactoryTest.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/archaius/ArchaiusConfiguration.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/archaius/SpringEnvironmentPolledConfigurationSource.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/aws/AwsComponents.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/aws/InstrumentedBackoffStrategy.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/aws/InstrumentedRetryCondition.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/eureka/BootHealthCheckHandler.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaComponents.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaConfigurationProperties.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/metrics/SpectatorConfiguration.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/metrics/SpectatorGcLoggingConfiguration.java
- kork-hystrix/src/main/groovy/com/netflix/spinnaker/config/HystrixSpectatorConfig.groovy
- kork-stackdriver/src/main/java/com/netflix/spinnaker/config/StackdriverConfig.java
- kork-web/src/main/groovy/com/netflix/spinnaker/config/ErrorConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttpClientComponents.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttpClientConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/config/RetrofitConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfigurationProperties.java
- kork-web/src/main/groovy/com/netflix/spinnaker/okhttp/OkHttpClientConfigurationProperties.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/okhttp/SpinnakerRequestInterceptor.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/retrofit/RetrofitConfigurationProperties.java
- kork-web/src/main/groovy/com/netflix/spinnaker/retrofit/Slf4jRetrofitLogger.java
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/SslExtensionConfigurationProperties.java
Step towards working with newer Spring versions that have problems working with `@Value` annotated properties, particularly at the `@Configuration` class level.
There are some changes in the lifecycle in Spring 4.3 that manifest in `@Value` annotations not reading from configuration if they have defaults set. This moves all the configuration into `@ConfigurationProperties` beans instead. Additionally it is recommended to keep `@Configuration` classes simple - to that end I've removed `@Autowired` fields in those classes and replaced with adding the appropriate parameter to whatever `@Bean` method was using the autowired value.
Other noise in this PR: removed a `Precondition` class in favor of the same functionality that is native in java 8 (`Objects.requireNonNull`)
> Remove Autowiring and Value in Configurations.

- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MetricDescriptorCache.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/StackdriverWriter.java
- kork-stackdriver/src/main/java/com/netflix/spinnaker/config/StackdriverConfig.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/MetricDescriptorCacheTest.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/StackdriverWriterTest.java
Instead of being optimistic that I can create informed Metric Descriptors specifying
the labels that will be needed for the different use cases, this approach is
pessimistic and assumes that the definition is eventually going to be discovered
to be wrong and fixes the definition when it encounters a problem.
I'm not convinced that this will not lose data -- it does not at the moment,
however the issue exists either way. At least this strategy adds resilience
and makes it easier to have a judas deployment easily flush out any new labels.
The underlying descriptors can be extracted to proactively define them for new
deployments as a better starting point.
This removes the need for actually caching descriptors or having "hints" as a
workaround.
@lwander 
This is similar to the python server …
> Rewrote stackdriver integration

- build.gradle
- kork-security/kork-security.gradle
- kork-security/src/test/groovy/com/netflix/spinnaker/security/MDCSpec.groovy
- the MDC context is no longer inherited across threads
> Explicit dependency on a recent release of logback

- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/ConfigParams.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MetricDescriptorCache.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/StackdriverWriter.java
- kork-stackdriver/src/main/java/com/netflix/spinnaker/config/StackdriverConfig.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/MetricDescriptorCacheTest.java
- kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/StackdriverWriterTest.java
Also, change the default instanceid to be <server>:<port> which is more
readable than a UUID but still unique at any given point in time.
@ttomsu
> Always store stackdriver metrics unique per application.

- kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/okhttp/OkHttpClientConfigurationProperties.groovy
* update default cipher suites to mozilla modern TLS recommendation.
* prefer server cipher suite order
* add jdk.tls System properties to Tomcat initializer (reject client renegotiation and increase DH key size)
> fix(ssl): improve TLS configuration

- kork-swagger/src/main/java/com/netflix/spinnaker/config/SwaggerConfig.java
@duftler or @jtk54 please review.
The generated API doc endpoints have an extra slash (e.g. `localhost:8084//applications`), since `basePath` is `/` by default.
The swagger UI seems to be a little smarter and isn't affected by this change.
> feat(swagger): makes base and documentation paths configurable

- kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlers.java
- kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlersSpec.groovy
Previously the GenericExceptionHandler only looked for the `@ResponseStatus`
annotation on the exception class itself.
With this change set, the handler will look on the exception class
_as well as_ any implemented interfaces or super classes.
An HTTP 500 will be returned iff no `@ResponseStatus` annotation is found.
> fix(web): Support @ResponseStatus on parent classes/interfaces

- .gitignore
- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
- kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy
Allows gate to propagate the origin of a user request (either `deck` or `api`) to downstream services. This will be consumed by orca to be injected into executions for prioritization.
@spinnaker/netflix-reviewers PTAL
> feat(web): Add user origin to AuthenticatedRequest

- kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/TomcatContainerCustomizerUtil.groovy
Allows for additional connector customizers in extension code to reuse
common TLS configuration code.
Installed this locally in gate and tested via sslyze that allthethings are still right on the SSL front.
> refactor(tls): refactor tomcat connector init into util class.

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
I wound up leaving the artifact resolution out of this since I think the validator leaves the usage clear-enough.
> feat(artifacts): Expected artifact definition

- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
Making AuthenticatedRequest.getSpinnaker[Request,Trace]Id methods public for use in clouddriver/orca
> fix(web): making traceId getters public

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
I realized this makes rendering the artifacts a lot easier. Without this flag, a user would have to delete/clear the "DefaultArtifact" contents to avoid specifying a default. If they change their mind, they need to go back and add all the fields in again.
> feat(artifacts): Add useDefaultArtifact flag

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
This allows us to associate each expected artifact with the artifact it
matched. The goal is to ensure that the artifacts are resolved only
once, when they are first declared (either in the trigger config, or
stage config).
> feat(artifacts): add boundArtifact to expectedArtifact

- kork-security/src/main/java/com/netflix/spinnaker/security/User.java
- kork-security/src/test/groovy/com/netflix/spinnaker/security/UserSpec.groovy
`new SimpleGrantedAuthority()` will fail when passed `""`.
> fix(security): Filter out empty roles when building authorities

- kork-core/src/main/java/com/netflix/spinnaker/kork/jackson/InvalidSubtypeConfigurationException.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/jackson/ObjectMapperSubtypeConfigurer.java
- kork-core/src/test/java/com/netflix/spinnaker/kork/jackson/ObjectMapperSubtypeConfigurerTest.java
Lifting the same functionality out from Keiko into kork. Swabbie has need for this, but not Keiko, and Keel needs this in `keel-core`, but doesn't have Keiko in that module. Ported from Kotlin to avoid any weirdness.
https://github.com/spinnaker/keiko/blob/master/keiko-spring/src/main/kotlin/com/netflix/spinnaker/config/SpringObjectMapperConfigurer.kt
> feat(core): Jackson subtype configurer

- kork-aws/kork-aws.gradle
- kork-aws/src/main/groovy/com/netflix/spinnaker/kork/aws/bastion/BastionConfig.groovy
- kork-aws/src/main/groovy/com/netflix/spinnaker/kork/aws/bastion/BastionCredentialsProvider.groovy
- kork-aws/src/main/groovy/com/netflix/spinnaker/kork/aws/bastion/BastionProperties.groovy
Pulled from https://github.com/spinnaker/clouddriver/tree/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/bastion
Since `clouddriver`, `front50`, and soon `echo` will be using this I'm pulling it here. @ajordens and I will refactor `clouddriver` and `front50` after this is merged.
> refactor(aws): pull bastion config to kork

- kork-dynomite/kork-dynomite.gradle
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientConfiguration.java
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientDelegate.java
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientDelegateFactory.java
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientFactory.java
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteDriverProperties.java
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/StaticHostSupplier.java
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/StaticTokenMapSupplier.java
- kork-jedis/kork-jedis.gradle
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientConfiguration.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientDelegate.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientDelegateFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisDriverProperties.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisHealthIndicatorFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisPoolFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientConfiguration.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientDelegate.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientDelegateFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientSelector.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/exception/ConflictingConfiguration.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/exception/MissingRequiredConfiguration.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/exception/RedisClientFactoryNotFound.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/exception/RedisClientNotFound.java
- kork-jedis/src/test/groovy/com/netflix/spinnaker/kork/jedis/RedisClientSelectorSpec.groovy
There's a lot here, but most of it is just pulling out configuration stuff from orca, clouddriver, et al.
Standardizes redis (or dynomite) configuration for services, and adds support for named clients. Each named client supports both a `primary` and `previous` client. `RedisClientDelegate` exists, but is now provided by `RedisClientSelector`, which provides a little interface for getting a named client (if it exists) or optionally falling back to a default client connection. Supports our existing redis connection/connectionPrevious scheme as well, so long as a `JedisClientDelegate` is also created alongside the `Pool<Jedis>` stuff.
Here's what a configuration looks like:
```yaml
redis:
connection: redis://localhost:6379
clients:
executionRepository:
primary:
driver: dynomite
config: …
```
> feat(redis): Adding jedis/dynomite client factories

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
Artifacts from Igor contains fields that can't be directly mapped to the fields in Kork's `Artifact` class. This commit will put the data in these fields into the metadata map.
> feat(artifacts): Put "unknown" fields into the metadata map

- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientDelegate.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientDelegate.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientDelegate.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisScanResult.java
Dynomite's scan methods don't implement the Jedis interfaces. This method puts a small facade around barebones functionality of scan. 
```java
client.withScan("mypattern*", 100, (scan) -> {
log.info(
"This is called for every scan iteration and has {} items", 
scan.getResults().size()
);
});
```
Something like that.
> feat(redis): Add scan command facade

- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
- This fixes an issue where ExecutionId wasn't propagating to clouddriver task threads, ensuring it's added to the User-Agent string for AWS calls.
> fix(mdc): propagate execId across threads

- kork-core/kork-core.gradle
- kork-core/src/main/java/com/netflix/spinnaker/kork/PlatformComponents.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/transientconfig/ScopedCriteria.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/transientconfig/SpringTransientConfigService.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/transientconfig/TransientConfigConfiguration.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/transientconfig/TransientConfigService.java
- kork-core/src/test/groovy/com/netflix/spinnaker/kork/transientconfig/SpringTransientConfigServiceSpec.groovy
Offers a pluggable dynamic / transient config service interface, and a default Spring-backed implementation. Two primary APIs are offered: A generic `getTransientConfig` and a `isEnabled` feature flag. Both of which support passing a `Supplier<Boolean>` predicate that must satisfy to `true` before returning the actual value. If `false`, the `defaultValue` is returned.
An additional layer of logic was added to feature flags that allows us to pass in canned `ScopedCriteria` according to our usual domain filters: `application`, `region`, `cloudProvider` and `account`. Precedence (highest to lowest) is currently: `region -> account -> cloudProvider -> application -> global`.
Given a feature flag `myFeature`, the configs for the Spring-backed implementation would be:
* `myFeature.enabled` …
> feat(core): TransientConfigService

- kork-core/src/main/java/com/netflix/spinnaker/kork/PlatformComponents.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/dynamicconfig/DynamicConfigSerivce.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/dynamicconfig/ScopedCriteria.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/dynamicconfig/SpringDynamicConfigService.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/dynamicconfig/TransientConfigConfiguration.java
- kork-core/src/test/groovy/com/netflix/spinnaker/kork/dynamicconfig/SpringDynamicConfigServiceSpec.groovy
* Fixed `isEnabled` Spring implementation to uniformly format enabled flags.
* Renamed `s/Transient/Dynamic` ... since that makes more sense.
* Renamed `getTransientConfig` to simply `getConfig`
FYI @ajordens
> fix(core): Simplify name of config service, fix isEnabled Spring implementation

- kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlers.java
Full stacktraces will now only be logged for 5xx errors.
> fix(web): Be more selective around logging exceptions for http errors

- kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/lock/RefreshableLockManager.java
- kork-jedis/kork-jedis.gradle
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java
- kork-jedis/src/test/groovy/com/netflix/spinnaker/kork/jedis/locking/RedisLockManagerSpec.groovy
- `LockManager` defines a basic locking interface. 
- `RefreshableLock` as an extension of `LockManager`. Defines lock heartbeat functionality.
- Simple usage:
``` 
val acquireLockResponse = lockManager.acquireLock(locksName, maxLockDuration), {
// Callback to run when lock is acquired
// Lock will be kept alive with periodic heartbeats for `maxLockDuration`.
})
log.info("Status", acquireLockResponse.lockStatus)
- Heartbeats are handled by an internal single-threaded scheduler executor. The run frequency of the scheduler is configurable as well as the default lease duration.
> feat(redis): Generic Locking support

- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java
- no need to release a lock we did not acquire
> fix(locking): Do not attempt to release lock if already taken

- kork-web/src/main/java/com/netflix/spinnaker/kork/web/interceptors/MetricsInterceptor.java
- kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/interceptors/MetricsInterceptorSpec.groovy
Some prep work for Q3 pubsub work. I want to know what sort of payload sizes we're shipping around between services, as different sizes will dictate different approaches. Hard use case: If a request payload `orca -> echo` is greater than 256KB, we won't be able to ship the actual message via SQS and would instead need to store it in S3, or maybe use a log stream instead, or solution Z.
> feat(web): Add request content length to metrics

- kork-aws/kork-aws.gradle
- kork-aws/src/main/groovy/com/netflix/spinnaker/kork/aws/ARN.java
- kork-aws/src/main/groovy/com/netflix/spinnaker/kork/aws/pubsub/PubSubUtils.java
Pulling sns and sqs management to Kork for ease of use across services.
Fixing permissions on sqs creation to be more narrow.
> feat(aws): adding sns/sqs utils

- kork-web/src/main/java/com/netflix/spinnaker/okhttp/OkHttp3MetricsInterceptor.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/OkHttpMetricsInterceptor.java
Reports a timer with sufficient tag detail to identify communication
issues between services.
ie) requests from `orca` to `echo` are failing
Only the host is identified, see the `controller.invocations` tag on the
destination service if you'd like more information about specific
endpoints that may be problematic.
> feat(okhttp): A simple metrics network interceptor for okhttp/okhttp3

- kork-web/src/main/groovy/com/netflix/spinnaker/okhttp/OkHttpClientConfigurationProperties.groovy
Allows for either `connectTimoutMs` or `connectTimeoutMs` to be specified.
> fix(web): Provide backwards compatibility for `okHttpClient.connectTimoutMs`

- kork-hystrix/src/main/groovy/com/netflix/spinnaker/hystrix/spectator/HystrixSpectatorPublisherCommand.groovy
- kork-hystrix/src/main/groovy/com/netflix/spinnaker/hystrix/spectator/HystrixSpectatorPublisherThreadPool.groovy
> fix(hystrix): Avoid an `NaN` when publishing `hystrix.currentTime`

- kork-core/src/main/java/com/netflix/spinnaker/kork/lock/RefreshableLockManager.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java
- kork-jedis/src/test/groovy/com/netflix/spinnaker/kork/jedis/locking/RedisLockManagerSpec.groovy
- added `MAX_HEARTBEAT_REACHED` to heartbeat
- added a new metric for when a lock reaches the max lock duration
> refactor(locking): Differentiate heartbeat status

- kork-artifacts/kork-artifacts.gradle
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
- kork-artifacts/src/test/groovy/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifactSpec.groovy
BREAKING CHANGE: This change affects the way in which artifacts injected
into a pipeline are matched to expected artifacts. Prior to this change,
a match was successful if the regular expression in the expected artifact
matched any substring of the corresponding field in the incoming artifact;
after this change, the regular expression in the expected artifact must
match the entire corresponding field incoming artifact.
As an example, consider an incoming artifact with name 'artifact123'. Before
this change, it would match expected artifacts with names 'artifact' and
'artifact.*'.  After this change, the incoming artifact will no longer
match an expected artifact with name 'artifact' but will continue to match
'artifact*'; users will need to explicitly add a wildcard (or some more
complex …
>  feat(artifacts): Artifact matching should use entire string

- kork-aws/src/main/groovy/com/netflix/spinnaker/kork/aws/pubsub/PubSubUtils.java
Instead of returning the topic arn, which we already know, we should return the subscription arn so that we can edit filters on that subscription
> fix(pubsub): return subscr arn when creating subscr

- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientConfiguration.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientDelegateFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisDriverProperties.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisPoolFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientConfiguration.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisPool.java
While working on a fix for https://github.com/spinnaker/spinnaker/issues/3309, I noticed a few bugs / missing items.
* Adds a `GenericObjectPoolConfig` as a fallback bean to the `JedisClientConfiguration`. This will now allow kork to use any service-provided override but fallback to default settings if not provided. `GenericObjectPoolConfig` can still be provided on a per-client basis.
* Fixed a bug where two `primaryDefault` clients could be created. For example, Orca currently creates its own `primaryDefault` client, then kork was creating its own as well. Kork will now only create these default clients if one has not already been created by a service.
* Backwards compatibility for `redis.connectionPrevious` was not present. I added this following the same semantics as the …
> fix(jedis): Allow services to override connection pool settings

- kork-core/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaComponents.java
This messed me up in Keel as I injected `EurekaClient` but there are actually 2 beans of that interface. Both are actually the same object. Using `@Primary` means that clients that wire `EurekaClient` will get just one bean rather than a stacktrace. Anyone still wiring `DiscoveryClient` won't be affected.
> fix(spring): disambiguate EurekaClient beans so they can be injected without a qualifier

- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientConfiguration.java
Previously, clients were getting initialized as "default", which did not take into account the fact that they may have been "primary". This PR fixes that naming to correctly make the name as either "primaryDefault" or "previousDefault".
Verified this does the right thing by triumphantly getting Swabbie to use a locally published kork 🎊
> fix(redis): name clients correctly to 'primaryDefault' (vs 'default')

- kork-secrets/kork-secrets.gradle
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretDecryptionException.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretEngineRegistry.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretException.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretManager.java
- kork-secrets/src/test/java/com/netflix/spinnaker/config/secrets/SecretManagerTest.java
Part of a series of PRs for the Secrets Management Project. This PR
adds SecretManager and SecretEngineRegistry. 
spinnaker/spinnaker#3649
> feat(kork/secrets): Adding SecretManager

- kork-secrets/kork-secrets.gradle
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretManager.java
`decryptAsFile()` should have been returning the original string passed in if that string is unencrypted. `decrypt()` also behaves this way, so the change here just checks if the string returned matches the string passed in.
> fix(secrets): return original file path if not encrypted

- kork-expressions/kork-expressions.gradle
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionEvaluationSummary.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionTransform.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/SpelHelperFunctionException.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/whitelisting/FilteredMethodResolver.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/whitelisting/FilteredPropertyAccessor.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/whitelisting/InstantiationTypeRestrictor.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/whitelisting/MapPropertyAccessor.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/whitelisting/ReturnTypeRestrictor.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/whitelisting/WhitelistTypeLocator.java
- kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionTransformTest.java
- settings.gradle
We need basic expression evaluation to exist in echo to be able to evaluate expressions in expected artifact inputs before they are matched to trigger artifacts. Moving the common logic here.
Leaving the addition of functions related to stage context and server group identification in Orca as that model is specific to Orca and we only need trigger context evaluation in Echo. The relationship between kork-expressions and Orca's extension to them will become more apparent with the follow-on Orca PR.
> refactor(expressions): Move common expression logic from orca-core

- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisException.java
Make InstrumentedJedisException inherit from JedisException. InstrumentedJedisException is not exported from kork, so it should inherit from a meaningful base class. This will let all the various components that rescue JedisException work as intended.
This was found while debugging Redis connections in Clouddriver. We have a proxy that closes idle connections after 50 s and have observed several issues with Clouddriver when the connections are killed. One of the issues is that pipelines randomly fail with frame in the stacktrace:
https://github.com/spinnaker/clouddriver/blob/302965edaf1dc62be262bc6013fb49eb91e4d5d7/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/data/task/jedis/RedisTaskRepository.java#L102-104
After capturing the packets during such a failed pipeline, …
> fix(redis): Inherit JedisException in InstrumentedJedis

- kork-core/kork-core.gradle
- kork-core/src/main/java/com/netflix/spinnaker/kork/secrets/SecretApplicationContextInitializer.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/secrets/SecretAwarePropertySource.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/secrets/SecretBeanPostProcessor.java
- kork-core/src/main/resources/META-INF/spring.factories
- kork-core/src/test/java/com/netflix/spinnaker/kork/secrets/SecretAwarePropertySourceTest.java
- kork-core/src/test/java/com/netflix/spinnaker/kork/secrets/SecretBeanPostProcessorTest.java
- kork-secrets-aws/kork-secrets-aws.gradle
Part of secrets management project: [spinnaker/spinnaker#3649](https://github.com/spinnaker/spinnaker/issues/3649)
Adds a Spring PropertySource to allow for decryption of secrets in the services when configs are read in.
> feat(core/secrets): decrypt application secrets

- kork-core/src/main/java/com/netflix/spinnaker/kork/lock/RefreshableLockManager.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java
- ensures fetching most up to date lock before attempting to release it
- added a requestId property on heartbeat requests for convenience
> fix(locking): Fixing race condition causing intermittent test failures

- kork-secrets-aws/src/main/java/com/netflix/spinnaker/config/secrets/engines/S3SecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretManager.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/engines/AbstractStorageSecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/engines/NoopSecretEngine.java
We need to clear the secret caches at the end of each session so the code picks up any user changes to secret fields or files.
Part of https://github.com/spinnaker/spinnaker/issues/3649
> feat(secrets): clear secret caches at the end of each session

- kork-secrets-aws/src/main/java/com/netflix/spinnaker/config/secrets/engines/S3SecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/engines/AbstractStorageSecretEngine.java
The current error messages aren't as helpful as they could be. Adding a specific errors for the following:
- bucket unauthorized
- bucket not found
- file not found
- key not found
> feat(secrets): improve error messages for S3 secret engine decryption

- kork-core/src/main/java/com/netflix/spinnaker/kork/secrets/SecretAwarePropertySource.java
The saml keystore doesn't end with "file" or "path" so currently it won't be decrypted in the services. This change enables decryption.
> feat(secrets): decrypt saml keystore in services

- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretManager.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretSession.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/engines/AbstractStorageSecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/engines/NoopSecretEngine.java
- kork-secrets/src/test/java/com/netflix/spinnaker/config/secrets/SecretManagerTest.java
- kork-secrets/src/test/java/com/netflix/spinnaker/config/secrets/engines/AbstractStorageEngineTest.java
Some secret files such as java keystores will require decryption in the form of bytes instead of strings.
Part of spinnaker/spinnaker#3649
> feat(secrets): add decryption as bytes for binary secret files

- kork-web/src/main/groovy/com/netflix/spinnaker/config/ActuatorEndpointsConfiguration.java
- kork-web/src/main/groovy/com/netflix/spinnaker/config/MetricsEndpointConfiguration.java
Without registering a requestMatcher, these WebSecurityConfigurerAdapters will handle the auth
for any request, when they really only care about allowing access to certain paths and the
opinions of how to perform application wide authentication/authorization are intended to be
configured elsewhere.
> fix(authz): apply requestMatchers on security configurers.

- spinnaker-dependencies/spinnaker-dependencies.gradle
Use Spock 1.1 that we explicitly specify vs one provided in spring-dependencies
> fix(bom): make sure we get spock 1.1

- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
- kork-security/src/test/groovy/com/netflix/spinnaker/security/AuthenticatedRequestSpec.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/MetricsInterceptor.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/OkHttp3MetricsInterceptor.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/OkHttpMetricsInterceptor.java
This also adds ability to propagate any `X-SPINNAKER-*` header automatically
And, ability to notify with a metric and a log when a request doesn't have
headers needed to successfully pass identity of the caller
(i.e. `X-SPINNAKER-USER` and `X-SPINNAKER-ACCOUNTS`)
symmetric PR in orca
> refactor(headers): Refactor header propagation logic

- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
javadoc task was failing on `&` and `>` characters when running a release build
> fix(javadoc): use entities for invalid javadoc.

- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
Since the typical usage pattern for allowAnonymous is to inline wrap a call to a retrofit service,
and the retrofit exceptions are already unchecked, it simplifies coding (in java) not to have to
try catch around calls to allowAnonymous
> fix(auth): converts allowAnonymous to unchecked exceptions

- kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy
Fixes a bug resulting from https://github.com/spinnaker/kork/pull/270
where X-SPINNAKER-* headers stopped being propagated because they were
not compared in a case insensitive way
> fix(requests): Correctly compare header names

- kork-sql/kork-sql.gradle
Looks like this version wasn't actually being forced in kork-sql
> fix(sql): force jooq version at 3.9.6

- kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfigurationProperties.java
- kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/TomcatContainerCustomizerUtil.groovy
newer tomcat as part of the upgrade to boot2 is stricter about
which characters are allowed in a URI path or query, but does
support relaxed mode for those characters.
this exposes two additional configuration options:
```yaml
default:
relaxedPathCharacters: "[]"
relaxedQueryCharacters: ${default.relaxedPathCharacters}
```
These strings consist of characters that are allowable in URIs
even if they don't strictly conform to the RFC.
An example we found was the square bracket characters were
previously acceptable, and were used in pipeline configuration
names. This setting allows us to preserve that capability
until we can migrate callers to properly URLEncode paths and
queries
> feat(tomcat): allow relaxed URI support

- spinnaker-dependencies/spinnaker-dependencies.gradle
MPTv1 has a strong dependency on jinjava 2.2.3 and anything higher breaks it
> fix(dependencies): pin back jinjava version

- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/SecretAwarePropertySource.java
When reading in properties on startup, the java keystore needs to be prepended with "file:".
@dibyom PTAL
> fix(secrets): Keystore should be classpath relative

- kork-exceptions/kork-exceptions.gradle
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/core/RetrySupport.java
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/ConstraintViolationException.java
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/HasAdditionalAttributes.java
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/IntegrationException.java
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/SpinnakerException.java
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/SystemException.java
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/UserException.java
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/web/exceptions/InvalidRequestException.java
- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/web/exceptions/ValidationException.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/controllers/GenericErrorController.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlers.java
Adds a hierarchy of root-level Spinnaker exception interface types:
```
SpinnakerException      # root-level interface
|
+- UserException        # exceptional conditions caused by an end-user
|
+- IntegrationException # exceptional conditions caused by non-core Spinnaker
|                       # code (cloud providers, extensions, etc)
|
+- SystemException      # exceptional conditions caused by core Spinnaker
```
Some basic `*RuntimeException` types are included which can be extended;
however it would be preferable to avoid direct usage, preferring concrete,
exception types.
The problem I'm trying to solve here is how difficult it is to classify errors into the three buckets (user vs integration vs core). How does this seem?
> feat(exceptions): Adding tiered root-level exceptions

- spinnaker-dependencies/spinnaker-dependencies.gradle
Clouddriver was using bcpkix 1.60 with bcprov 1.61. The former depends on the latter, so we should make sure the versions are consistent.
> chore(kork): Use a consistent bouncycastle version.

- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/TelemetryHelper.java
Instead of builing a long string and getting the payload size of that string, just compute the size of each string in the list and return the sum.  This significantly reduces allocations during caching cycles for the kubernetes provider, which often calls mset with a long list of parameters.
> perf(redis): Optimize payloadSize

- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/TelemetryHelper.java
The same optimization as in #310, but for the function computing payload size on a Map<String, String>.
> perf(redis): Optimize payloadSize for Map<String,String>

- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttpClientComponents.groovy
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/MetricsInterceptor.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/OkHttp3MetricsInterceptor.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/OkHttpMetricsInterceptor.java
For local development, it is tedious to see all the "anonymous" request warnings.
Add ability to disable the check via config variable, e.g:
```yaml
spring:
profiles: local
okHttpClient:
interceptor:
skipHeaderCheck: true
```
> feat(headers): add ability to skip auth header checks

- spinnaker-dependencies/spinnaker-dependencies.gradle
The new Retrofit unlocks built-in Kotlin coroutine compatibility by marking Retrofit interface methods as `suspend` functions. See spinnaker/keel#242
> new versions of Retrofit and OkHttp

- kork-manageddelivery/kork-manageddelivery.gradle
- kork-manageddelivery/src/main/java/com/netflix/spinnaker/kork/manageddelivery/model/ResourceEvent.java
- settings.gradle
Moving the `ResourceEvent` classes into kork so they can be shared by keel and gate, and we can have some strong typing.
This is an experiment! If this works well, we will leave it for some shared things. If it doesn't work well, I'll remove this and duplicate the classes like we normally do.
> feat(managedDelivery): adding resource event model classes

- build.gradle
- kork-bom/kork-bom.gradle
compileOnly dependency should not be added to generated pom.xml,
see discussion: https://discuss.gradle.org/t/publishing-plugin-should-respect-compileonly-configuration/22903/2
see related commit: nebula-plugins/nebula-publishing-plugin@a5432aa
Currently all published `pom.xml` contain:
```
<dependency>
<groupId>org.projectlombok</groupId>
<artifactId>lombok</artifactId>
<version/>
<scope>provided</scope>
</dependency>
```
which is considered invalid by Maven and thus all transitive dependencies of such artifacts are omitted.
> fix(bom): Fix generated pom.xml to omit invalid lombok declaration

- spinnaker-dependencies/spinnaker-dependencies.gradle
Spring Cloud release train Greenwich.SR2 includes a fix for using [Hashicorp Vault with an embedded Config Server](https://github.com/spring-cloud/spring-cloud-config/issues/1393), as used by clouddriver.
> chore(dependencies): Upgrade Spring Cloud to Greenwich.SR2

- kork-config/kork-config.gradle
- kork-config/src/main/java/com/netflix/spinnaker/kork/boot/DefaultPropertiesBuilder.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/ConfigFileService.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/ConfigServerBootstrap.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/ConfigFileServiceAutoConfiguration.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/RemoteConfigSourceConfigured.java
- kork-config/src/main/resources/META-INF/spring.factories
- kork-config/src/main/resources/spinnakerconfig.yml
- kork-config/src/test/java/com/netflix/spinnaker/kork/configserver/ConfigFileServiceTest.java
- settings.gradle
This PR mostly contains code extracted from clouddriver that will be required by other services for integration with Spring Cloud Config Server. It will also reduce some duplicated Spring Boot default properties.
> feat(configuration): Add kork-config module for Spring Cloud Config Server integration

- kork-config/src/main/java/com/netflix/spinnaker/kork/boot/DefaultPropertiesBuilder.java
A few default property names and values were copied incorrectly to this new central utility class.
> fix(configuration): Fix default property values

- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/ConfigServerBootstrap.java
when deployed by halyard, all config lands in `/opt/spinnaker/config` so we need to set the config server bootstrap location to include `/opt/spinnaker/config` so that it gets picked up.
> fix(config): fix config server bootstrap location

- kork-expressions/kork-expressions.gradle
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionEvaluationSummary.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionFunctionProvider.kt
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
To support extracting expression handling from Orca, 
* Apply Orca changes from https://github.com/spinnaker/orca/commit/a4815ce1b5f12e551d5d6dc05526a2158775a6a0
* Apply Orca changes from https://github.com/spinnaker/orca/commit/52d35db40474e2b8fefaa318f36495d439e64f4e
* Encapsulate all expression-handling functions in implementations of `ExpressionFunctionsProvider`
* Enhance `ExpressionFunctionsProvider` to reduce `Arrays.asList()` and `Collections.singletonList` boilerplate
> refactor(expressions): Apply Orca changes to expressions

- kork-core/src/main/resources/META-INF/spring.factories
- kork-sql/kork-sql.gradle
- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/DefaultThreadUncaughtExceptionHandler.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/ThreadUncaughtExceptionHandler.java
While investigating another issue, I realized that uncaught thread exceptions aren't logged correctly.
They are logged to `stderr` and, depending on logstash config, may or may not show up in the logs.
This change configures a default uncaught thread exception handler and logs the exceptions as `error`s.
It then, optionally, passes the exception to the previous handler (if there was one).
This behavior can be disabled with `globalExceptionHandlingEnabled=false`
> fix(exceptions): correctly log uncaught exceptions

- spinnaker-dependencies/spinnaker-dependencies.gradle
In Clouddriver, we have a transitive dependency on 26.0-android, which
is overriding the version we set here anyway.
I talked to @dreynaud and the issue that prompted
spinnaker/clouddriver#3692 was actually that IntelliJ was compiling
against Guava 27.1, but then using Guava 19.0 on the classpath. Then it
was getting an error about a missing method because it was trying to
call a method added in Guava 20. This error was specific to IntelliJ and
wouldn't have happened if Gradle was used (which will ensure that the
same version is used at compilation and runtime).
So I think this should be a safe thing to do.
> chore(dependencies): Upgrade Guava

- kork-config/kork-config.gradle
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/CloudConfigApplicationListener.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/CloudConfigAwarePropertySource.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/CloudConfigResourceService.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/ConfigFileLoadingException.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/ConfigFileService.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/ConfigFileUtils.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/CloudConfigAutoConfiguration.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/ConfigFileServiceAutoConfiguration.java
- kork-config/src/main/resources/META-INF/spring.factories
- kork-config/src/test/java/com/netflix/spinnaker/kork/configserver/CloudConfigResourceServiceTest.java
- kork-config/src/test/java/com/netflix/spinnaker/kork/configserver/ConfigFileServiceTest.java
The Spring Cloud Config Server integration provided by `kork-config` includes the ability to specify account credentials (e.g. Kubernetes account `kubeconfigfile` and Google account `json-path`) as files that are stored in a Config Server backend like git, using a `configserver:` qualifier. 
Previously code in services that accessed these file references in account properties needed to use a `ConfigFileService` bean provided by `kork-config` to resolve the file references, pulling the specified file from the Config Server backend if necessary. 
This was starting to get unwieldy and intrusive in services, especially in cases where the code using the account properties wasn't implemented as Spring beans that could get a `ConfigFileService` bean injected into it. This PR adds a Spring …
> feat(config): Resolve configfiles using a custom PropertySource

- spinnaker-dependencies/spinnaker-dependencies.gradle
the updated bom bumps jackson-databind from 2.9.9 -> 2.9.9.3
see https://github.com/FasterXML/jackson-databind/issues/2387
> fix(vuln): upgrade jackson for CVE remediation

- kork-web/src/main/groovy/com/netflix/spinnaker/config/ResolvedEnvironmentConfigurationProperties.java
- kork-web/src/main/groovy/com/netflix/spinnaker/endpoint/ResolvedEnvironmentEndpoint.java
This was a regression from the boot2 upgrade where, now that there is a
ConfigurationProperties class for keysToSanitize, we are by default saying
do not sanitize anything.  This changes the default behaviour to use the
Sanitizer's default set of keywords to sanitize with.
While this is technically a breaking change, I think the expectation of
anyone using this would be that they don't have to supply configuration
to get a reasonable default level of resolvedEnv sanitiation, and anyone
who has supplied a custom value for this property will continue to work
as expected.
> fix(resolvedEnv): unless explicitly configured, use Sanitizer defaults.

- kork-core/src/main/java/com/netflix/spinnaker/kork/PlatformComponents.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/version/ServiceVersion.java
There's really no need to re-resolve after we've done it once. Also removing a log message that says a version can't be resolved: It gets noisy.
> fix(core): Cache service version

- kork-core/kork-core.gradle
- kork-sql/src/test/kotlin/com/netflix/spinnaker/kork/sql/SpringStartupTests.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
Adds a nice Spring integration & annotations to the global project's dependency list: [Documentation](https://resilience4j.readme.io/docs/getting-started-3)
I was thinking we'd use `{service}-web/config/application.yml` to document all resilience configs within a service. It'd be an interesting exercise to additionally maintain any of Netflix's resilience4j config in OSS, keeping all configs in a `netflixResilience` spring profile.
> feat(core): Add resilience4j boot2 annotations api

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/whitelisting/InstantiationTypeRestrictor.java
This allows us to do URL encoding in pipeline expressions
> feat(expressions): allow java.net.URLEncoder class in pipeline expressions

- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/EncryptedSecret.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/SecretAwarePropertySource.java
- kork-secrets/src/test/java/com/netflix/spinnaker/kork/secrets/EncryptedSecretTest.java
This replaces the less-than-ideal logic around determining if an encrypted secret is a saml file, a regular file or string value. Now, users should use the `encryptedFile:s3!...` syntax for secret files and `encrypted:s3!...` for secret strings. The logic for prepending saml files with "file:" after decrypting moves into gate with this PR: https://github.com/spinnaker/gate/pull/919
This proposes to keep both sets of logic in place for version 1.16/1.17, but mark the old logic as deprecated and remove it fully in version 1.17/1.18?
> feat(secrets): add encryptedFile syntax for secret files

- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/core/RetrySupport.java
This should help prevent issues where we mix up maxRetries and retryBackoff
> fix(retry): deprecate RetrySupport method with long in favor of Duration

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/config/PluginsAutoConfiguration.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/config/PluginsConfigurationProperties.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/PluginBeanPostProcessor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManager.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactoryTest.kt
Even better, let's just not have an enabled flag on plugins. Everyone gets it: This will simplify the integration story.
> refactor(plugins): Remove enabled flag entirely

- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/SpinnakerException.java
Allows for `throw new SpinnakerException("some constructor args").setRetryable(true)`
> feat(exceptions): chain style accessor for SpinnakerException retryable

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/config/PluginsAutoConfiguration.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManager.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpringPluginStatusProvider.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringPluginStatusProviderTest.kt
This will likely need to change in the future to use Front50 as the ultimate source of these values, but this is an incremental improvement over default PF4J.
> feat(plugins): Spring-backed plugin status provider

- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/ConfigFileService.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/CloudConfigAutoConfiguration.java
- kork-config/src/test/java/com/netflix/spinnaker/kork/configserver/ConfigFileServiceTest.java
This enables support for `configserver:` prefixed files transparently for services already using ConfigFileService.
It fixes the issue in Clouddriver of changes not being detected when referencing `kubeconfigFile` with `configserver` from a Cloud config server loaded config.
> fix(config): support configserver files

- gradle/buildViaTravis.sh
we semi regularly see some of the autobump PRs fail because the artifacts haven't propagated through bintray,
this just sticks a sleep 60 after running the final then runs bumpDependencies
> chore(build): sleep between publish and dependency bump

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/whitelisting/InstantiationTypeRestrictor.java
`DayOfWeek` was missed from this https://github.com/spinnaker/orca/pull/3071
`LocalDateTime` is being requested to completed `LocalDate`
> fix(expressions): add DayOfWeek and LocalDateTime to allowed list

- spinnaker-dependencies/spinnaker-dependencies.gradle
Pick up new ECS task definition fields.
Updating to match [Netflix/AWSObjectMapper](https://github.com/Netflix/AWSObjectMapper/blob/master/build.gradle#L44)
> chore(aws): Bump aws sdk

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionTransform.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
- kork-expressions/src/main/kotlin/com/netflix/spinnaker/kork/expressions/ExpressionFunctionProvider.kt
We would like to add SpEL function auto-complete ability to `deck` for better useability.
This requires that we can describe functions nicely and enum them from orca
* Add function description to `FunctionDefinition`
* Add ability to get all registered `FunctionProviders`
(also minor java doc fixups to remove compiler warnings)
> feat(expressions): Add plumbing to support function auto-complete

- kork-expressions/src/main/kotlin/com/netflix/spinnaker/kork/expressions/ExpressionFunctionProvider.kt
follow-up for https://github.com/spinnaker/kork/pull/410 after talking to @christopherthielen
This change adds ability to specify additional documentation for a spel function.
This documentation will (soon) show up in `deck` as the user is entering expressions
> fix(expressions): allow more detailed documentation for spel functions

- kork-plugins/src/main/java/com/netflix/spinnaker/kork/plugins/spring/PluginLoader.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManager.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactory.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/PluginSystemTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManagerTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactoryTest.kt
Plugins didn't actually load. AbstractPluginManager conflates instantiation and initialization. The SpinnakerPluginManager pluginStatusProvider was delegating to null (even with the proxy in place) and load plugins, enabling and disabling failed with NPEs. The most straight forward way to fix it was to circumvent the create* methods and just initialize the protected members direct that are passing into SpinnakerPluginManager. There are tests that show the problem and fail without the changes.
> fix(plugins): fix SpinnakerPluginManager initialization

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginDescriptor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentExtensionConfigResolver.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerManifestPluginDescriptorFinderTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerPropertiesPluginDescriptorFinderTest.kt
My example plugin (https://github.com/claymccoy/pf4jStagePlugin) has a namespace. In order for it to load in orca the config must have the namespace in the config path, but it can't be in the enabled path.
```
spinnaker:
plugins:
RandomWaitPlugin:
enabled: true
Armory.RandomWaitPlugin:
extensions:
armory.randomWaitStage:
enabled: true
config:
defaultMaxWaitTime: 60
```
This change unifies the path to be \<namespace\>.\<plugin name\>.
Since PF4J uses the pluginId, I've had to override our SpinnakerPluginDescriptor to use \<namespace\>.\<plugin name\> as the pluginId. There are still places that require just the plugin name without the namespace, so I've added an attribute pluginName to distinguish that.
I think that plugin namespace should probably be required, but I've made it optional …
> fix(plugins): plugin enable config did not use namespace

- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt
- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/SecondaryPoolDialectCondition.kt
- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/SqlProperties.kt
- kork-sql/src/test/kotlin/com/netflix/spinnaker/kork/sql/SqlConfigurationTests.kt
- kork-sql/src/test/resources/application-test.yml
- Conditionally add secondary liquibase target if configured.
- Conditionally add secondary JOOQ (DSLContext) to target a different dialect than the primary source. If two connection pools exist and they both are of same dialect we will not create secondary JOOQ bean. (eg: application having 2 pools against the same datasource will not need a secondary JOOQ)
- Configuration is backward compatible for the most part. Applications will need to wire up the JOOQ and pool as applicable on the app side of things.
- Tests exercise taking in the new sql config and verifies the bean existence as expected.
> feat(sql): Support for multiple SQL data sources

- spinnaker-dependencies/spinnaker-dependencies.gradle
With this version bump, we can remove `@Extension` from plugin extensions and instead just use `@SpinnakerExtension`.
> chore(dependency): Bump pf4j to 3.2.0

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
This is the first step in addressing the discussion [here](https://github.com/spinnaker/igor/pull/535#discussion_r340260634).
The all-arg constructors for Artifact and ExpectedArtifact accept a lot of similarly-typed parameters; to encourage use of the Builder inside each of these classes, mark these constructors
deprecated with the goal of eventually removing them.
The no-arg constructors don't have a problem with too many parameters, but they do encourage a pattern of creating an empty object and then setting fields on it rather than creating a fully-formed object. (One day it would be great to make these classes immutable, which would force
use of the Builder.) For this reason, also deprecate the no-arg constructor.
Adding an annotation to a lombok-generated constructor is experimental …
> refactor(artifacts): Deprecate Artifact constructors

- kork-plugins/src/test/java/com/netflix/spinnaker/kork/plugins/testplugin/api/TestExtension.java
- kork-plugins/src/test/java/com/netflix/spinnaker/kork/plugins/testplugin/unsafe/UnsafeTestExtension.java
- kork-plugins/src/test/java/com/netflix/spinnaker/kork/plugins/testplugin/unsafe/UnsafeTestPlugin.java
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/loaders/SpinnakerDefaultPluginLoaderTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/testplugin/TestPluginBuilder.kt
- kork-plugins/src/test/resources/unsafe-testplugin/plugin.properties
TestPluginBuilder will generate java source and compile to create a standalone plugin directory
suitable for referencing as a plugin to install. Useful for testing to have the ability to
create a plugin that is not already in the test classpath.
> feat(plugins): adds a plugin generation testing tool and tests SpinnakerDefaultPluginLoader

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/loaders/UnsafePluginClassLoader.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessorTest.kt
Unsafe plugins were putting jars and classes in their own ClassLoader, and then loading Classes from the parent delegate (a different class loader). This obviously failed.
The easiest fix for this was to make UnsafePluginClassLoader addURL append to the same `parent` class loader. Since addURL is protected this was done using reflection, and there is an assumption that `parent` is a URLClassLoader. Not ideal at all, but it is "unsafe" mode right?
I looked at making UnsafePluginClassLoader being more careful about who it delegates to, but PF4J makes that difficult. There may be better ways to handle this at a higher level like overriding AbstractPluginManager.loadPlugin or making changes to PF4J so that using the parent class loader exclusively is an option (basically making unsafe mode an …
> fix(plugins): allow unsafe plugins to load

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/PluginSystemTest.kt
Fixes an issue reading the plugin directory configuration due to the SpinnakerPluginManager's early
initialization happening before ConfigurationProperties are bound.
Adds some tests to PluginSystemTest that load external plugins and extensions.
> fix(plugins): fix PluginManager plugin directory bootstrapping

- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientDelegate.java
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteDriverProperties.java
- kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/LocalRedisDynomiteClient.java
- kork-jedis-test/src/main/java/com/netflix/spinnaker/kork/jedis/EmbeddedRedis.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientDelegate.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisHealthIndicatorFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisPoolFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientDelegate.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedis.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedPipeline.java
- kork-jedis/src/test/groovy/com/netflix/spinnaker/kork/jedis/locking/RedisLockManagerSpec.groovy
- kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java
- kork-sql/kork-sql.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
**DO NOT MERGE**
This PR should not be merged until services that use kork-managed dependencies are ready to upgrade. 
Upgrade Spring Boot from 2.1.7 to 2.2.2. The Boot upgrade requires no code changes, but brings in newer versions of some Boot-managed dependencies that do require code changes. 
Jedis upgrade to `redis.clients:jedis:3.1.0`
* Packaging changes (especially `XxxCommand` classes)
* Various backward-incompatible API changes
* Previously deprecated methods removed
The Jedis upgrade necessitates an upgrade to `com.netflix.dyno:dyno-jedis:1.7.2`
* Compatibility with Jedis 3.1.x
* Various backward-incompatible API changes
Liquibase upgrade to `org.liquibase:liquibase-core:3.8.0`
* One backward-incompatible API change
> chore(dependencies): Upgrade Spring Boot to 2.2

- kork-plugins/kork-plugins.gradle
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/PluginUpdateService.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManager.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessorTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/testplugin/TestPluginBuilder.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/PluginUpdateServiceTest.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
Current functionality is pretty naive: All plugins in the repository are downloaded, and the latest
plugin version is always selected as the desired plugin version to install.
> feat(plugins): Remote plugin download capabilities

- kork-telemetry/src/main/java/com/netflix/spinnaker/kork/telemetry/caffeine/CaffeineStatsCounter.java
This will allow us to do:
```
Caffeine.newBuilder().recordStats(() -> new MetricsStatsCounter(registry, "some-cache"))
> feat(metrics): Add caffeine cache StatsCounter implementation using Spectator registry

- spinnaker-dependencies/spinnaker-dependencies.gradle
Fixes an annoying bug we're hitting in some Keel tests
> chore(dependencies): bump Strikt

- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/SpinnakerExtension.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/CanonicalPluginIdValidator.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginDescriptor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/ConfigResolver.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentExtensionConfigResolver.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/dsl.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerManifestPluginDescriptorFinder.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerPropertiesPluginDescriptorFinder.kt
- kork-plugins/src/test/java/com/netflix/spinnaker/kork/plugins/testplugin/unsafe/UnsafeTestExtension.java
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessorTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/PluginSystemTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactoryTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentExtensionConfigResolverTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerManifestPluginDescriptorFinderTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerPropertiesPluginDescriptorFinderTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/testplugin/TestPluginBuilder.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/types.kt
- kork-plugins/src/test/resources/unsafe-testplugin/plugin.properties
Having a separate - yet basically required - namespace property for plugins
felt clumsy and was likely asking for bugs. This change removes the separate
namespace attribute from plugin descriptors in favor of requiring plugin IDs
to follow a new canonical ID format: `{namespace}.{pluginId}`.
This also removes the `pluginName` attribute from descriptors, as it appears
that is no longer necessary either from the couple tests that were asserting
its presence and values - `pluginId` has the same value.
> refactor(plugins): Remove separate namespace in favor of canonical ID

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentExtensionConfigResolver.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
* Forgot to update `com.fasterxml.jackson:jackson-bom` to 2.10.1 in the boot-2.2 PR, leaving both 2.9.9 and 2.10.1 in the classpath of many services and causing orca to fail.
* Boot 2.2 brings Liquibase 3.8.2 which JAR contains a misplaced `META-INF/services/com.fasterxml.jackson.databind.Module` file.
Jackson's `ObjectMapper.findModules()` will scan the classpath for such files in order to dynamically loads all Jackson modules found. The liquibase file contains `com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule` but this class isn't provided by the liquibase JAR nor necessarily elsewhere in the classpath.
Kork tests weren't impacted because they don't execute with liquibase loaded on the classpath.
Orca for example is loading both kork-plugins and liquibase, causing …
> fix(dependencies): Spring Boot 2.2 upgrade issues

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpringPluginStatusProvider.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentExtensionConfigResolver.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/PluginSystemTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentExtensionConfigResolverTest.kt
Previously, config looked like this:
```yaml
spinnaker:
plugins:
repositories:
spinnakerRepo:
url: repo.url
netflix.helloworld:
enabled: true
config: {}
```
Where `pluginId`s under `spinnaker.plugins` were conflicting with `repositories` and `rootPath`. This PR introduces another layer of configuration, putting all extensibility-related config under a single root path of `spinnaker.extensibility`.
```yaml
spinnaker:
extensibility:
repositories:
spinnakerRepo:
url: repo.url
plugins:
netflix.helloworld:
enabled: true
config: {}
```
With this, I also renamed `rootPath` to `pluginsRootPath`, as this is more descriptive of its functionality.
> fix(plugins): Change plugin config paths to avoid path conflicts

- kork-core/src/main/java/com/netflix/spinnaker/kork/PlatformComponents.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/ConfigResolver.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentConfigResolver.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/PluginUpdateService.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManager.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManagerTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentConfigResolverTest.kt
I forgot that Spring configs are not available when we're setting up the plugin framework, so remote repository configuration did not work. I've refactored `SpringEnvironmentConfigResolver` a little bit so it's not just for extension configuration, but can be used broadly for loading whatever kind of configs we need as POJOs, instead of resorting to only `Environment.getProperty`, etc.
I made a couple other changes while testing this stuff out, I think some of it related to the Boot 2.2 upgrade:
- Added `@ImportAutoConfiguration` excludes for some resilience4j stuff. It was causing Orca to crash while starting up. I'd like to have resilience4j all autowired, but it's an issue for another day.
- Moved plugin updates / downloads before PluginManager's call to `loadPlugins`. I was finding …
> fix(plugins): Correctly read remote repositories from config

- kork-core/src/main/java/com/netflix/spinnaker/kork/archaius/ArchaiusConfiguration.java
The polling in Archaius is causing issues in some environments that do not use it: unnecessary reloads and when secrets - any, not just `kork-secrets` - are referenced they are being reloaded which can be costly and cause temporary files to keep being created.
I'm not sure if this is the best way to disable Archaius but this adds a simple `archaius.enabled` flag to turn it off.
cc: @cfieber
> feat(archaius): Allow users to disable Archaius

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginDescriptor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerManifestPluginDescriptorFinder.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerPropertiesPluginDescriptorFinder.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactoryTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/loaders/SpinnakerPluginLoaderTests.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/proxy/aspects/utils.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/spring/actuator/SpinnakerPluginEndpointTest.kt
- kork-plugins/src/test/resources/testplugin/plugin.properties
This was largely to implement equals/hashCode but also plays slightly nicer with the
expected extension mechanism of PF4J.
There is a slightly worse immutability story here, but the base PluginDescriptor is
already a fully nullable POJO so I don't think it is too bad to have our new
attributes as var as well.
Also adds some PluginLoading tests (the original driver for the desire to have an
equality test on SpinnakerPluginDescriptor..). These are implemented as a generic
TCK as I have a follow-up PR that introduces a new plugin-type that exercises the
same set of tests for that type.
> refactor(plugins): makes SpinnakerPluginDescriptor a subclass of DefaultPluginDescriptor.

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
Closes spinnaker/spinnaker#5205.
The all-arg and no-arg constructors for Artifact and ExpectedArtifact are marked as deprecated, as consumers should be constructing artifacts by using the lombok-generated builder class.
Remove the no-arg constructors entirely, and make the all-arg constructors private.  The all-arg constructors are used by the inner builder class; had we omitted the explicit AllArgsConstructor
annotation, the Builder annotation would have generated a package-private all-args constructor for us. The goal of explicitly adding the annotation is so that we can make the constructor private.
> refactor(artifacts): Make artifact constructors private

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
This reverts commit 66d3391b2c071ea932d972343e6fa32a9452bb91.
When bumping the services, I realized that deserialization with Jackson is using the all-args constructor implicitly.  We need to configure the Artifact and ExpectedArtifact classes to use the builder for deserialization.  I will make this change and re-apply later today, but I don't want to leave things broken all day so reverting for now.
> fix(artifacts): Revert making constructors private

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/model/ArtifactTest.java
When a serialized artifact has unknown keys, they should be added to the resulting artifact's metadata map upon deserialization. The switch to use a builder for deserialization broke this; fix it and add a test for this case.
> fix(artifacts): Properly deserialize unknown keys in artifact

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManager.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/bundle/PluginBundleExtractor.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManagerTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/bundle/PluginBundleExtractorTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/PluginUpdateServiceTest.kt
- kork-plugins/src/test/resources/bundle/deck/index.js
Plugin bundles are an aggregate of one or more PF4J plugin zip artifacts. It provides an experience for plugin developers to produce a single plugin artifact that is applied to one or more services. A bundle would look something like this:
```
my-cool-plugin.zip
orca.zip
deck.zip
...
```
The `PluginBundleExtractor` provides the ability to extract a downloaded plugin bundle and source the correct internal plugin artifact for use by a service. It is also backwards compatible with a normal PF4J plugin artifact, in case a developer does not need bundle capabilities.
> feat(plugins): Support for extracting plugin bundles

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManager.kt
SpinnakerUpdateManager attempts to put plugins into a root directory, this causes the service to crash if the directory does not exist. This PR ensures the directory is present
> fix(plugins): create plugins directory if not present

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManager.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/finders/PluginRefPluginDescriptorFinder.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/finders/SpinnakerPluginDescriptorFinder.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/loaders/PluginRefPluginLoader.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/pluginref/PluginRef.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/repository/PluginRefPluginRepository.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/finders/PluginRefPluginDescriptorFinderTests.kt
- kork-plugins/src/test/resources/test.plugin-ref
- kork-plugins/src/test/resources/testplugin/plugin.properties
This introduces a new plugin type that is registered if pf4j is
set to development mode to enable a local plugin development
experience.
A plugin-ref is a JSON file with a pointer to the actual location
of a plugin and a list of the classes and libraries to include
when building the PluginClasspath.
This allows a runtime experience similar to dropping a fully
packaged plugin into the host application, without requiring
the packaging and deployment step - aside from a one time
generation and copy/link of the plugin-ref file.
This changeset includes all the plumbing to make plugin-ref
a supported type of plugin, but there is still work to do
in tooling and documentation to make the development
experience reasonable.
With this changeset and the following set of steps, you can
work with the …
> feat(plugins): plugin reference plugin type for local development

- kork-plugins-spring-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/spring/PrivilegedSpringPlugin.java
- kork-plugins-spring-api/src/test/kotlin/com/netflix/spinnaker/kork/plugins/api/spring/PrivilegedSpringPluginTest.kt
- kork-plugins-spring-api/src/test/kotlin/com/netflix/spinnaker/kork/plugins/api/spring/types.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessor.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessorTest.kt
This allows plugins to wire themselves into the application’s Spring context by explicitly registering BeanDefinitions.
See https://github.com/claymccoy/springExamplePlugin for a working example and list of capabilities.
Note that unsafe mode in your plugin is not required for this.
I tried this the way that was intended by sharing the app's Spring context and it didn't load my plugin beans correctly.
https://github.com/spinnaker/kork/pull/454
I did some research about Spring context initialization and lifecycle and tried a lot of different things. The full application context doesn't seem to be fully ready at this point. So I tried using postProcessBeanFactory to create and register the plugin beans, but that didn't work quite right either. The recommended approach is using …
> feat(plugins): Added privileged Spring plugin

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/PluginUpdateService.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManager.kt
This is in support of deck asset proxy work in Gate.
> chore(plugins): Publicly expose downloadPluginRelease on UpdateManager

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/VersionRequirementsParser.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/VersionRequirementsParserTest.kt
Supports https://github.com/spinnaker/front50/pull/690
> fix(plugins): VersionRequirementsParser should throw InvalidPluginVersionRequirementException when SUPPORTS_PATTERN does not match

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/FileDownloaderProvider.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/FileDownloaderProviderTest.kt
Safely call FileDownloaderProperties in FileDownloaderProvider.
Closes: https://github.com/spinnaker/spinnaker/issues/5324
> fix(plugins): FileDownloaderProperties should be optional

- kork-core/src/main/java/com/netflix/spinnaker/kork/threads/NamedThreadFactory.java
We now use a NamedThreadFactory in orca and clouddriver, hoist it up in kork so that it's available to all without reinventing the wheel
> feat(namedthreadfactory): Add NamedThreadFactory

- kork-artifacts/kork-artifacts.gradle
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
- kork-artifacts/src/test/groovy/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifactSpec.groovy
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifactTest.java
* refactor(artifacts): Make ExpectedArtifact immutable 
There was only ever one place where ExpectedArtifact was being mutated, which was to set the boundArtifact. This place has been updated to return a copy of the artifact instead of mutating it, so none of the setters in this class are used. Remove the setters and mark the fields (as well as the class) final.
Technically the class is only shallowly immutable, as Artifact itself remains mutable, but this should still make it much easier to reason about expected artifacts and reduce action-at-a-distance bugs.
* refactor(artifacts): Add nullable annotations to ExpectedArtifact 
defaultArtifact and boundArtifact can be null; the existing code that uses ExpectedArtifacts assumes that both id and matchArtifact are not null (and will NPE if …
> refactor(artifacts): Make ExpectedArtifact immutable

- kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50UpdateRepositoryConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/PluginUpdateService.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManager.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/front50/Front50Service.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/front50/Front50UpdateRepository.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/PluginSystemTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/PluginUpdateServiceTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/front50/Front50UpdateRepositoryTest.kt
This does a few things for us:
- Update repositories should return all plugin info objects, that includes the front50 repo.  Cache the world.  This keeps the process of determining which plugin to install unified, which leads me to...
- `SpinnakerUpdateManager.getLastPluginRelease` will be used to select the plugin version for installation.  There will be a follow up PR to Gate for this (for use in the `DeckPluginCache`). We will eventually refactor this, but at least it's all in one place.
> refactor(plugins): Plugin version and service requirement selected via SpinnakerUpdateManager

- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
Seems like this was made private by mistake and I intend to use it in gate.
> chore(api): make AuthenticatedRequest::getSpinnakerApplication public

- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
- kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy
Quality of life change that adds nice getters and setters in AuthenticatedRequest. With this change, the MDC updates and lookups are encapsulated in AuthenticatedRequest and don't leak out in AuthenticatedRequestFilter or any other caller.
Also factor out AuthenticatedRequest::clear() to reduce some duplication.
> feat(auth): expand AuthenticatedRequest API

- kork-core/src/main/java/com/netflix/spinnaker/kork/common/Header.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/dynamicconfig/SpringDynamicConfigService.java
- kork-security/kork-security.gradle
- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
- kork-security/src/test/groovy/com/netflix/spinnaker/security/AuthenticatedRequestSpec.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/context/AuthenticatedRequestContext.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/context/AuthenticatedRequestContextProvider.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/context/RequestContext.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/context/RequestContextProvider.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/MetricsInterceptor.java
This PR lifts Header out of AuthenticatedRequest and moves it into kork-core so that it can be accessed from both kork-web and kork-security.
In kork-web, we introduce a RequestContext interface with a concrete implementation that pulls values from AuthenticatedRequest. Consumers that need to access values from a RequestContext just need to get an autowired RequestContextProvider.
This should make code that depends on these values to be more easily testable and make it easier to go from one type of context to another (as I am currently doing in gate).
> feat(context): provide a RequestContext abstraction

- spinnaker-dependencies/spinnaker-dependencies.gradle
This pulls in https://github.com/pf4j/pf4j-update/pull/48 which is necessary for how we wire up update repositories.
> chore(dependencies): bump pf4j-update to 2.3.0

- kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50UpdateRepositoryConfiguration.java
Kind of annoying this is a problem but I'd rather not spread unnecessary configuration around.
> fix(plugins): Check multiple default property locations for front50 base-url

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
We've made this change elsewhere (front50 update repository) but I need to make it here now too.  Without this the application name is empty, since the `applicationContext. getApplicationName()` does not use the property `spring.application.name` (looks like it tries to source the name from servlet context path).  Anyways, that results is `PluginBundleExtractor` throwing an `IntegrationException`.  This hasn't been an issue until now since I'm actually trying to load a bundled plugin on the backend.
> fix(plugins): Source application name from spring.application.name prop for SpinnakerPluginManager

- kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50UpdateRepositoryConfiguration.java
This is what I get for trying to be nice and making this config process simple.  The call to `orElse` actually calls `front50RepositoryProps.getUrl` regardless of the BindResult, which results in an exception when that is not set.  This resolves that issue.
> fix(plugins): Update repository URL should be sourced via getOrElse call

- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/ConfigurableExtension.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/SpinnakerExtension.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactory.kt
- kork-plugins/src/test/java/com/netflix/spinnaker/kork/plugins/testplugin/unsafe/UnsafeTestExtension.java
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessorTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringExtensionFactoryTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/testplugin/TestPluginBuilder.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/types.kt
I noticed while doing unrelated work that `kork-plugins` and `kork-plugins-api` modules shared the same package. This is quite undesirable, especially as we introduce more APIs for plugins to use and create implementations for said APIs in `kork-plugins`.
This is a pretty bigly breaking change, but it's gotta happen imo and may as well happen sooner than later.
> refactor(plugins): Move plugins-api to api package

- kork-web/src/main/groovy/com/netflix/spinnaker/config/RequestContextConfiguration.groovy
- kork-web/src/main/java/com/netflix/spinnaker/config/RequestContextConfiguration.java
Not sure if kork-web is the right place for this to get picked up automatically as a config by most services, but it depends on things in -core and in -security and I wasn't sure how to untangle these dependencies.
> chore(config): add config for a default RequestContextProvider

- kork-swagger/kork-swagger.gradle
- kork-swagger/src/main/java/com/netflix/spinnaker/config/SwaggerConfig.java
This is either the best idea or the worst idea I've had in a while...
After submitting the last PR, I realized that there is a way to exclude groovy from Swagger annotations without forcing it as a dependency.
In general I'm not a fan of reflection as it makes it really hard to perform static analysis and is hard to maintain. But this may be the one time in my life where it is actually the right solution to the problem.
> refactor(swagger): Remove groovy dependency from kork-swagger

- kork-config/kork-config.gradle
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/CloudConfigAutoConfiguration.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/RemoteConfigSourceConfigured.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/SpringCloudAwsConfiguration.java
- kork-config/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/SpringCloudAwsS3ResourceLoaderConfiguration.java
- kork-config/src/main/resources/META-INF/spring.factories
- spinnaker-dependencies/spinnaker-dependencies.gradle
The Spring Cloud Hoxton.SR1 release train includes a new version of Spring Cloud Config that provides additional capabilities for Spinnaker. 
* Additional Vault authentication options such as AWS EC2, AWS IAM, Google Cloud Compute, Google Cloud IAM, and Kubernetes. This requires a new dependency on Spring Cloud Vault. 
* AWS s3 as an additional Config Server backend option, including the ability to serve credentials files via the [`configserver:` syntax](https://www.spinnaker.io/setup/configuration/#configuration-files). This requires a new dependency on Spring Cloud AWS. 
* Redis as an additional Config Server backend option. 
Corresponding documentation updates in https://github.com/spinnaker/spinnaker.github.io/pull/1653
> chore(dependencies): Upgrade Spring Cloud to Hoxton.SR1

- spinnaker-dependencies/spinnaker-dependencies.gradle
Bringing AWS SDK from 1.11.656 (Oct 18, 2019) to 1.11.723 (Feb 14, 2020)
Fixes spinnaker/spinnaker#5378
Fixes spinnaker/spinnaker#5338
> chore(dependencies): Upgrade AWS SDK

- spinnaker-dependencies/spinnaker-dependencies.gradle
Upgrade eureka version.
Fix CVE-2019-10173 caused by xstream dependency from following services:
- clouddriver
- echo
- fiat
- front50
- gate
- halyard
- igor
- kayenta
- orca
- rosco
> chore(dependencies): resolve CVEs issues

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/repository/Front50UpdateRepository.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/repository/Front50UpdateRepositoryTest.kt
We don't want services to be totally unable to start if Front50 is unavailable.
> fix(plugins): Allow front50 to be inaccessible while loading plugins

- kork-core/src/main/java/com/netflix/spinnaker/kork/PlatformComponents.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/version/ManifestVersionResolver.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/version/ServiceVersion.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManager.kt
Some problems with `ServiceVersion` wiring after adding it to the plugin framework.
- There are potentially multiple `VersionResolver`s; `ServiceVersion` should be used by the codebases.
- The plugin framework initializes before normal Spring wiring, so beans wired up by other areas of kork or an application will not be available yet.
Also moved the config to a more general location (`service-version`, instead of `spinnaker.extensibility`, since `ServiceVersion` is not part of the plugin framework itself.
> fix(plugins): Rework ServiceVersion bean wiring

- kork-pubsub-aws/src/main/java/com/netflix/spinnaker/kork/pubsub/aws/SNSPublisher.java
Turns out, it can override the actual metric name
> fix(metrics): don't publish a metric with a `name` tag

- spinnaker-dependencies/spinnaker-dependencies.gradle
This should fix the breakage caused by spinnaker/clouddriver#4373
Specifically, the library upgrade there depends on guava 28.2, so Maven sucks in `28.2-android`, which doesn't have `ImmutableMap#toImmutableMap`.
The error happens at runtime because at compile time it's using `28.1-jre`, but that gets overridden in the distribution by the android version.
> chore(guava): upgrade guava

- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/PluginSdks.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/httpclient/HttpClient.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/httpclient/HttpClientConfig.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/httpclient/HttpClientRegistry.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/httpclient/Request.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/httpclient/Response.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/HttpClientSdkConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/IdResolver.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/PluginSdksImpl.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/HttpClientSdkFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClient.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientRegistry.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3Response.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/internal/CompositeOkHttpClientFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/internal/DefaultOkHttp3ClientFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/internal/OkHttp3ClientFactory.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerExtensionFactoryTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientRegistryTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientTest.kt
- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttpClientComponents.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttpMetricsInterceptorProperties.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/MetricsInterceptor.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/OkHttp3MetricsInterceptor.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/OkHttpMetricsInterceptor.java
The first actual API for `kork-plugins-api` and one that will be necessary pretty quick here as we at Netflix start getting closer to moving our internal extensions into plugins. This HTTP client is designed to allow plugins to make HTTP requests without directly wiring up & configuring their own HTTP clients, per-se.
An extension could have a constructor dependency on `HttpClientProvider` and with #506, it would be injected and the implementation of the `HttpClient`s themselves would be encapsulated within the service internals, allowing us to iterate the client without forcing transitive dependencies on plugin developers.
**ACTION**: Review the API. I went with _simple_ being the primary guiding light. I explicitly decided not to follow in a pattern like Retrofit despite its nice API …
> feat(plugins): HTTP client plugin API

- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttp3ClientConfiguration.groovy
We recently encountered a crash loop using the igor 1.18.X codeline
when enabling SSL with a local truststore. The error being thrown is
```
Failed to instantiate [com.jakewharton.retrofit.Ok3Client]: Factory method
'ok3Client' threw exception; nested exception is java.lang.UnsupportedOperationException:
clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
```
The stack trace allowed me to trace it back to kork's instantiation of the okHttpClient
which wasn't updated to pass in the TrustManager with the update of that JDK.
This only shows up if you are terminating SSL with your own truststore in the pod
so we may have been the first ones to come across this issue in the wild.
> fix(ssl): pass TrustManager to okHttp SSL socketfactory for JDK9+

- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttp3ClientConfiguration.groovy
Cherrypicked from `master` to `release-1.18.x`
> fix(ssl): pass TrustManager to okHttp SSL socketfactory for JDK9+ (#540)

- kork-plugins/src/main/java/com/netflix/spinnaker/config/HttpClientSdkConfiguration.java
There are downstream failures due to this config being enabled by default, and honestly I just want to fix other bugs and move on and not deal with this problem right now.
> fix(plugins): Disable HttpClientSdkConfiguration

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/proxy/ExtensionInvocationProxy.kt
EventListener.processEvent(Event) does not return a value (void), which results in null being returned here. But result can't be null, so there is a runtime exception. This causes an error in the log and invocationStates.after() does not get executed.
> fix(plugins): handle extension method with void return type

- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttp3ClientConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/okhttp/OkHttpClientConfigurationProperties.groovy
I noticed that `okhttp3`'s async dispatcher implements a queue in order to enforce a maximum number of in-flight requests per hostname, with a default of 5. since we’ve seen its queues block and since keel attempts to support lots of concurrent resource checks which all require clouddriver calls (a single hostname), I think the ability to tune this would be nice.
> feat(okhttp): support for dispatcher max-conn tuning

- .github/workflows/bump_dependencies.yml
- .github/workflows/release.yml
The release build failed on bump dependencies due to API rate limits. Since it's the release workflow, it can't be re-run.
This splits the bump dependencies task out into its own workflow, triggered by a custom repository dispatch event from release. Splitting it out into its own workflow means we can rerun just the dependency bump task.
Uses: https://github.com/peter-evans/repository-dispatch
> chore(github): Split bump dependencies into its own workflow

- .detekt.yml
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManager.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/bundle/PluginBundleExtractor.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginManagerTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/bundle/PluginBundleExtractorTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManagerTest.kt
Halyard does not currently have knowledge of which plugins should be placed onto each spinnaker service. For now, we can log a warning if there are plugin configs placed onto services that are not required for the plugin to function, so that halyard can successfully deploy plugins to Spinnaker.
Currently Spinnaker throws an error if plugin configs are laid down upon a service that does not require it
> fix(plugins): allow for plugin configs on all services

- .github/workflows/release.yml
https://help.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
> fix(build): Dispatch bump workflow with Spinnaker github token

- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/httpclient/HttpClientConfig.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientRegistry.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/OkHttp3ClientFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/internal/CompositeOkHttpClientFactory.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientRegistryTest.kt
Since we're storing metatron URLs as "metatron://my-service", we need a way to normalize them back into real URLs.
... Also squeaked in some defaults to help guard against NPEs.
> fix(plugins): Allow normalization of baseurls from OkHttp3ClientFactories

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/ExtensionBeanDefinitionRegistryPostProcessor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/internal/CompositeOkHttpClientFactory.kt
Disables `ExtensionInvocationProxy`. While working on Orca, I discovered that it doesn't handle proxied stage tasks well (at all) during serialization/deserialization. Rather than try to work on a hack that will get things to work, I'm disabling this code path for the time being while we work on MVP functionality. I think there's a solution here to support using the invocation proxy, or similar, but it will need more diligent effort than what we're willing to take on for the time being.
This PR also removes some reified code that was causing stackoverflow errors for some reason.
> fix(plugins): Disable invocationproxy, remove reified fun optimization

- .github/workflows/build.yml
There's no point in doing this, and this will allow us to build and move onto testing if we can create a release for Kork.
> fix(build): Do not publish snapshot on release-* branches

- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/httpclient/HttpClientConfig.java
- kork-plugins/kork-plugins.gradle
- kork-plugins/src/main/java/com/netflix/spinnaker/config/HttpClientSdkConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClient.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3Response.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/internal/DefaultOkHttp3ClientFactory.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientIntegrationTest.kt
Had two problems today. First, the ObjectMapper wasn't configured, oops. Second, `Ok3HttpClient` was closing responses before user-land code would have the opportunity to read response bodies, so I changed all that around.
Also added an integration test for the httpclient, since obviously the unit tests didn't catch it.
> fix(plugins): Configured ObjectMapper and better respoonse body handling

- spinnaker-dependencies/spinnaker-dependencies.gradle
There are new versions of both junit and assertj; let's pull those in. I tested the full test suite of clouddriver and orca with these new dependencies, and all tests passed in both.
> chore(test): Bump test dependencies

- .github/workflows/release.yml
On the last kork bump, 4 of the 14 builds failed because the new artifact wasn't available yet. I don't think speed for the bumps is generally that critical, so let's just play it safe and use five minutes?
Aslo: fix the indentation, which was kinda all over the place in this file.
> chore(GHA): sleep for 5 minutes before running bumpdeps

- kork-secrets-aws/kork-secrets-aws.gradle
- kork-secrets-gcp/kork-secrets-gcp.gradle
- kork-secrets/kork-secrets.gradle
- kork-security/kork-security.gradle
- kork-web/kork-web.gradle
A number of commonly-used kork modules export their implementation dependencies as api dependencies. In cases where a depdendency is not used in the API of a module and is just an implementation detail, move it to an implementation dependency. (In some cases the dependency could be removed entirely.)
There are definitely many other places in kork where we can clean things up (reducing things on the compile path in all services) but this is just a small thing I could get done quickly.
I've already updated the microservices (or have an open PR) to explicilty add in dependencies in cases where we were depending on an accidental transitive dependency.
> refactor(dependencies): Reduce transitive dependencies

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/internal/SpinnakerPluginInfo.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/repository/Front50UpdateRepositoryTest.kt
Still working through some ideas of how to use this (either here in kork or just in front50), but this resolves the `MissingKotlinParameterException` on startup when front50 update repository is enabled.
> fix(plugins): Remove state field and add preferred field on SpinnakerPluginRelease

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManager.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/internal/Front50Service.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/PluginInfoRelease.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/provider/AggregatePluginInfoReleaseProvider.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/provider/PluginInfoReleaseProvider.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/Front50PluginInfoReleaseSource.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/PluginInfoReleaseSource.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/PreferredPluginInfoReleaseSource.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/SpringPluginInfoReleaseSource.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManagerTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/provider/AggregatePluginInfoReleaseProviderTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/release_plugins.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/Front50PluginInfoReleaseSourceTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/LatestPluginInfoReleaseSourceTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/PreferredPluginInfoReleaseSourceTest.kt
Somewhere along the way we stopped using `SpinnakerPluginInfo` so this change updates a few more files than should've been necessary.  Really, this just adds a new plugin info release source.
> feat(plugins): Add preferred plugin info release source

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManager.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/internal/SpinnakerPluginInfo.kt
The cast was a poor choice - it never would succeed.  The reason we didn't see this bug is because we were only testing with front50's update repository, which returns a `SpinnakerPluginInfo` object.  This supports any PF4J compatible update repository (though the `preferred` field is only supported if using the front50 update repository).
> fix(plugins): Use Jackson to convert PF4J PluginInfo to SpinnakerPluginInfo

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/LatestPluginInfoReleaseSource.kt
I missed another bad cast (this is the last one) in `LatestPluginInfoReleaseSource`.
> fix(plugins): Use Jackson to convert PF4J PluginRelease to SpinnakerPluginRelease

- kork-security/src/main/java/com/netflix/spinnaker/security/AllowedAccountsAuthorities.java
- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
- kork-security/src/main/java/com/netflix/spinnaker/security/User.java
- kork-security/src/test/groovy/com/netflix/spinnaker/security/AllowedAccountsAuthoritiesSpec.groovy
- kork-security/src/test/groovy/com/netflix/spinnaker/security/AuthenticatedRequestSpec.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy
deprecates User and updates interactions to support UserDetails instead of User.
adds support for encoding allowedAccounts as granted authorities
> refactor(security): refactor AuthenticatedRequest to support generic UserDetails

- kork-plugins-spring-api/kork-plugins-spring-api.gradle
After https://github.com/spinnaker/spinnaker-gradle-project/pull/135, I can't depend on `kork-plugins-spring-api` from my plugin because it doesn't know how to resolve the version for `spring-boot-starter`. 
I think the package was previously pulling it transitively from `kork-plugins-api` but can no longer do so because of the gradle plugin change. @cfieber ?
In any case this package should probably depend on spinnaker-dependencies explicitly.
> fix(kork-spring-api): explicitly depend on spinnaker-dependencies

- kork-sql/src/test/kotlin/com/netflix/spinnaker/kork/sql/health/SqlHealthProviderSpec.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
In particular we'd like to use JOOQ 3.13.x on Keel because it gives us the ability to have `@NonNull` and `@Nullable` annotations in generated classes.
> update Spring Boot and JOOQ

- spinnaker-dependencies/spinnaker-dependencies.gradle
Bumping to latest version of OkHttp3 to resolve platform-specific TLS bugs.
> fix(misc): Upgrade okhttp3 client lib

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
* fix(artifacts): Improve null safety of expected artifact 
The ExpectedArtifact class is annotated such that id and matchArtifact are not null, but this is not actually enforced anywhere.
First, explicitly write out the AllArgsConstructor that was generated by lombok, and move the Builder annotation to it (so the builder uses that constructor when finally creating the object).
Then update the constructor to have a ParametersAreNullable annotation as we can't control what gets passed to the constructor, and handle when we are passed a null id or matchArtifact.
For the id case, we'll just translate to an empty string. For the matchArtifact case, we'll create an empty matchArtifact. As the point of a matchArtifact is to contain filters that determine whether a given artifact matches this …
> refactor(artifacts): Improve null-safety of Artifact class

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
In the last PR I was a bit overzealous in converting all null entries in artifacts to emtpy string. This is a bit more invasive than intended, as there are a number of places that are checking only against null (and not empty). The benefit of this is not all that clear given the potential to break things, so reverting that part of the change.
The remainder of the PR remains---deprecating the setters.
> refactor(artifacts): Revert null to empty conversion

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
* fix(artifacts): Fix incorrect non-null annotation
Adding NullableByDefault to the Artifact class is also marking the builder methods as Nullable which is incorrect, and annoying as the generaly pattern is to chain calls. This is causing all calls like Artifact.builder().name("abc").build() to have every call in the chain be highlighted by editors that are aware of these annotations.
Add a MethodsReturnNonnullByDefault to the builder class, as it will always return non-null from its methods. (Also remove the ParametersAreNullableByDefault that is implied by the top-level annotation on the class.)
* fix(artifacts): Return this from builder putMetadata
This is a minor improvement to the builder API; all the auto-generated builder functions return this so you can chain them, but I forgot to …
> fix(artifacts): Fix incorrect non-null annotation

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/model/ArtifactTest.java
There's still one annoying thing that I didn't properly fix in the last commit. Because the whole Artifact class is annotated as NullableByDefault, we get a warning every time we call .toBuilder() which *is* guaranteed to return non-null. We can't directly annotate it as it's generated by Lombok; let's fix this by using FieldsAreNullableByDefault so that it doesn't affect method values.
At first I wanted to affect method return values because the fact that the fields are nullable means the accessors are also nullable. But after testing, marking the fields as Nullable does cause the lombok-generated accessors to be marked nullable, so marking the fields nullable is enough.
> fix(artifacts): Fix non-null annotation

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/model/ArtifactTest.java
It turns out that the Nonnull annotation I added to metadata caused lombok to insert an overzealous null-check in the .metdata() function in the artifact builder, which breaks deserializing artifacts with the metadata explicitly set to null.
Let's explicitly write out the Lombok-generated function, and instead of throwing an NPE, just translate the null value to an empty Hashmap.
The added test failed before this change and passes after.
> fix(artifacts): Fix NPE deserializing artifacts

- gradle.properties
- spinnaker-dependencies/spinnaker-dependencies.gradle
Looks like everyone just gets this dependency from kork. I guess we can't really do this with `fiatVersion`, since it would be a circular dependency...
So it's kinda weird that this is different than how we handle all the other cross-repo dependencies, but I'm inclined to leave it. What do you think?
> chore(moniker): Allow for moniker autobumps

- kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java
Turns out `DatabaseMetadata.getTables()` will include views as well as tables. If you then try to truncate those, it esplode.
> Avoid trying to truncate DB views

- spinnaker-dependencies/spinnaker-dependencies.gradle
Updating the aws-sdk version to use 1.11.802 to support new ecs task definition properties using the latest aws-sdk-java version as per https://github.com/aws/aws-sdk-java/releases
**Note: Do not merge until https://github.com/Netflix/AWSObjectMapper/pull/86 has been released**
> chore(aws): bump aws-sdk version to 1.11.802

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/model/ArtifactTest.java
As part of making Artifact immutable, we also want to make the contents of metadata shallowly immutable.  (We can't enforce deep immutability as it can contain arbitrary Objects.)
We've already deprecated (and removed from calling code) any way for consumers to directly modify the metadata map (or even for them to know that we are storing this as a Map).
That being said, there is still the loophole of clients passing in a Map, then keeping around a reference and modifying it. Let's close that loophole my making a shallow copy of the map before storing it on the Artifact.
Also, remove an unecessary qualified reference to Artifact.ArtifactBuilder.
> refactor(artifacts): Shallow copy artifact metadata

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/proxy/aspects/MetricInvocationAspect.kt
- kork-telemetry/src/main/java/com/netflix/spinnaker/kork/telemetry/MethodInstrumentation.java
Typically the concrete target class will not be invoked directly, instead the invocation will occur on the type (like `Task#execute` for example) -- in that instance we would fail to lookup the `Metered` annotation because the interface/abstract class methods do not and should not contain the `Metered` annotation.
> fix(plugins): Lookup method from target class when instrumenting extension point method invocation with timing metric

- kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50PluginsConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/Front50FileDownloader.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/Front50FileDownloaderTest.kt
- Set Front50 plugin downloader to use new provider implementation that allows us to swap underlying clients to custom impls.
> fix(misc): Move to new client provider for plugin downloads

- kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50PluginsConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/Front50FileDownloader.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/Front50FileDownloaderTest.kt
OkHttpClientProvider is not available to wire up during plugin framework initialization.
> fix(misc): revert client provider impl for plugin downloads

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManager.kt
Without this change, overwrites occur when multiple plugins share the same version.
> fix(plugins): Prefix downloaded plugin with plugin ID

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpinnakerPluginDescriptor.kt
So that we can deserialize this properly when calling `/installedPlugins` from other services.
> fix(plugins): Add Jackson compatible private setter setDependencies on SpinnakerPluginDescriptor

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/allowlist/AllowListTypeLocator.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/allowlist/FilteredMethodResolver.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/allowlist/FilteredPropertyAccessor.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/allowlist/InstantiationTypeRestrictor.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/allowlist/MapPropertyAccessor.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/allowlist/ReturnTypeRestrictor.java
This refactor should not affect the current consumers of the
kork-expressions dependency since the configuration of the
allow list is handled in this library and at least for now
those classes are effectively an implementation detail.
> fix(naming): use better naming for expressions allow list

- kork-jedis-test/src/main/java/com/netflix/spinnaker/kork/jedis/EmbeddedRedis.java
A lot of tests use EmbeddedRedis; it's a lot easier for tests to clean up this redis if it implements AutoCloseable as then they can use a try-with-resources construct.
Add a close() method that just calls the existing destroy().
> feat(redis): EmbeddedRedis implements AutoCloseable

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
* refactor(artifacts): Remove deprecated functions
These functions have been deprecated for more than a month (including a release of Spinnaker) and have been removed from all client code. It's time to remove them entirely.
* refactor(artifacts): Make fields final
Now that we've removed all setters for Artifact, we can make its fields final.
> refactor(artifacts): Make fields final

- kork-runtime/README.md
- kork-runtime/kork-runtime.gradle
- settings.gradle
kork-runtime serves as a grouping of the runtime modules within kork for a
Spinnaker service (similar to a spring-boot-starter style module).
By collecting these opinions here, we can more easily refactor existing or
introduce new runtime opinions and propagate those to all the consuming
services.
This is specifically intended for modules that expose AutoConfiguration
or com.netflix.spinnaker.config style scanned Configuration classes and
are expected to be present in a running system, but aren't needed as a
compile time dependency.
> feat(dependencies): adds kork-runtime module

- kork-swagger/kork-swagger.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
consumers of this module should only expect io.swagger:swagger-annotations anything else
is asking for breakage as we upgrade
this will break a couple of consumers that are transitively getting guava via their
kork-swagger dependency but I will fix the autobump PRs for those directly
> fix(dependencies): fix kork-swagger transitive dependencies

- kork-core/src/main/java/com/netflix/spinnaker/kork/discovery/NoDiscoveryStatusPublisher.java
Used by Orca -- although unsure if it's actually _used_ by anyone.
> fix(core): Add method to change internal discovery status

- kork-plugins/src/main/java/com/netflix/spinnaker/config/SerdeSdkConfiguration.java
I suspect this is an issue of having not made the return type `SdkFactory`, so it never actually gets wired up.
> fix(plugins): Correctly wireup serde SdkFactory

- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt
Reverts spinnaker/kork#712
I'm seeing an issue with this change and read-only mode where things fail due to some unsatisfied dependencies
there is an `@DependsOn("liquibase")` on the data source class and it seems like with read-only set that is either blocking a whole chain of components from initializing or introducing a circular dependency (because there is another bean named liquibase that this ends up dependant on)
the purpose of the dependsOn annotation was to block the context from continuing to initialize while the migrations are running, so if we can find another way to do that we should be good to get this change back in
alternatively could we just set spring.liquibase.enabled=false .. that stops liquibase autoconfiguration (that probably blows something else up... heh)
> Revert "feat(sql): Add a feature flag for liquibase migrations"

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionTransform.java
- kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionTransformTest.java
Fixes spinnaker/spinnaker#5865.
* test(spel): Add tests on ExpressionTransform
The next commit will fix a bug in ExpressionTransform; first add some tests to document the current behavior. In particular, test the behavior in handling nested maps and nested lists.
* fix(spel): Fix flattening of nested arrays in SpEL evaluation
Currently nested lists are being flattened when evaluating expressions. This is incorrect, as expression evaluation should not affect the shape of the data structure; it should only handle evaluating expressions in the components of that data structure.
There are some situations in the Kubernetes provider where we need a list of lists in the context; this currently breaks because upon evaluating expressions these lists get flattened.
> fix(spel): Fix flattening of nested arrays in SpEL evaluation

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/proxy/aspects/MetricInvocationAspect.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/proxy/aspects/MetricInvocationAspectTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/proxy/aspects/utils.kt
I was reviewing a plugin that @dreynaud wrote and saw that he annotated a private method on an extension point with `@Metered`.  I then realized that our logic to skip private methods was basically pointless since we require the `@Metered` annotation (the logic to skip private methods was originally there when we automatically metered all extension methods - we no longer do that).
> feat(plugins): Allow metrics on private methods annotated with @Metered

- kork-eureka/src/main/java/com/netflix/spinnaker/kork/archaius/ArchaiusAutoConfiguration.java
- kork-eureka/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaAutoConfiguration.java
- kork-eureka/src/test/kotlin/com/netflix/spinnaker/kork/EurekaSystemTest.kt
This moves archaius config back to being a BeanPostProcessor to ensure it happens early in the lifecycle.
I had made some bad assumptions around autoconfig ordering via the annotations that were clarified here:
https://github.com/spring-projects/spring-boot/issues/22337
> fix(eureka): ensure archaius config happens before eureka config

- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt
- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/migration/SpringLiquibaseProxy.kt
Right now it is hard to run e.g. a read-only clouddriver cluster towards a read-only database, because there's no way to disable the migrations (which will cause Clouddriver to fail on startup if it can't write to the DB).
I'm piggybacking on the `sql.read-only` feature flag.
This is take 2 of this PR, after #712 had to be reverted due to Spring startup issues. See #718. I think this way of disabling the migration is less intrusive, because the liquibase beans will still be present in the context.
> feat(sql): Add a feature flag for liquibase migrations

- kork-annotations/src/main/java/com/netflix/spinnaker/kork/annotations/DeprecationInfo.java
There's been discussion of how to deprecate things in `-api` modules. We have some general guidance, but I wanted something a little more standard that we can easily point people to that will help guide them in providing useful code deprecation context.
Idea here is that any time we use the `@Deprecated` annotation, this annotation would also come along for the ride.
Rather than include a bunch of information on usage and process in the annotation docs, I figured pointing to the spinnaker.io website would be a better place, and we can improve the docs there.
> feat(annotations): Adding DeprecationInfo annotation

- kork-web/src/main/java/com/netflix/spinnaker/config/DefaultServiceEndpoint.java
- kork-web/src/main/java/com/netflix/spinnaker/config/ServiceEndpoint.java
This is to support use cases wherein some additional configuration, resolved at runtime, is necessary to wire up the underlying HTTP client
> feat(web): Add config map to ServiceEndpoint

- build.gradle
- gradle.properties
- gradle/kotlin-test.gradle
- gradle/kotlin.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
Nebula Kotlin is no longer supporting Kotlin >= 1.4 so I've switched to using the regular Kotlin Gradle plugin. I also bumped a couple of Kotlin related dependencies.﻿
Consuming projects will also need to switch from using Nebula Kotlin.
> Kotlin 1.4

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/SdkFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/HttpClientSdkFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/serde/SerdeServiceSdkFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/yaml/JacksonYamlResourceLoader.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/yaml/YamlResourceLoaderSdkFactory.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/context/PluginSdksRegisteringCustomizer.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/yaml/JacksonYamlResourceLoaderTest.kt
I thought I could be lazy and just pass `Any::class.java` to the `SdkFactory` instead of the extension class, which is not available. This didn't work so hot because the resource loader SDK uses the value to load resources from the class path.
With this fix in, it looks like all of our plugins load as-is without modification under V2.
> fix(plugins): Refactor PluginSdk to also allow using plugin class

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/DefaultBeanPromoter.kt
The original `DefaultBeanPromoter` was calling a convenience function on the `ApplicationContext` that Java was not correctly resolving, causing extensions to be autowiring candidates by the service; which caused breakages as we're selectively promoting beans to the service context. This simplification just registers the extension beans as singletons directly on the bean factory, which is what I wanted all along.
> fix(plugins): V2 promote extensions as singletons

- gradle/kotlin.gradle
- kork-sql/src/test/kotlin/com/netflix/spinnaker/kork/sql/PagedIteratorSpec.kt
- kork-sql/src/test/kotlin/com/netflix/spinnaker/kork/sql/health/SqlHealthProviderSpec.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
Could've removed Spek from kork entirely, but I wanted to see how Spek 2.x works. 
Supposedly it has better IDE performance than Spek 1.x, but I haven't seen evidence of this yet via kork: Orca has some really large, phenomenally slow tests that could be upgraded that should give better results. Spek 1.x and Spek 2.x can live side-by-side, so I'll try converting a single test to compare, but kork has been entirely migrated.
> refactor(test): Migrate Spek to Spek2

- kork-retrofit/kork-retrofit.gradle
- kork-retrofit/src/test/kotlin/com/netflix/spinnaker/kork/retrofit/RetrofitServiceProviderTest.kt
- kork-retrofit2/kork-retrofit2.gradle
- kork-retrofit2/src/test/kotlin/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceProviderTest.kt
- kork-web/kork-web.gradle
- kork-web/src/main/java/com/netflix/spinnaker/config/okhttp3/RawOkHttpClientConfiguration.java
- kork-web/src/main/java/com/netflix/spinnaker/config/okhttp3/RawOkHttpClientFactory.java
- spinnaker-dependencies/spinnaker-dependencies.gradle
Doing the bare minimum for OSS here; getting Zipkin wired up into okhttp, but not configuring Sleuth. I suspect it's a slim chance that Zipkin is going to be utilized outside of Netflix, so I figured I would spare the effort of wiring that up for OSS.
Does this seem reasonable? Sleuth can always be added later for everyone else if there's demand.
> feat(web): Add optional Zipkin integration to RawOkHttpClientFactory

- kork-jedis/kork-jedis.gradle
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisPoolFactory.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientConfiguration.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientConnectionProperties.java
- kork-jedis/src/test/java/com/netflix/spinnaker/kork/jedis/RedisClientConnectionPropertiesTest.java
Fixes parsing of `password` when using redis clusters, previously this included the basic authentication separator `:`  as part of the password.
Fixes parsing of `database` when using redis node pools, previously the default database `0` was always returned.
Moves these functions into `RedisClientConnectionProperties` so that they can be shared between redis types.
> fix(redis): fix parsing parameters from uri

- spinnaker-dependencies/spinnaker-dependencies.gradle
https://nvd.nist.gov/vuln/detail/CVE-2016-2402
> chore(dependencies): bump okhttp from 2.7.0 to 2.7.5 due to vulnerabilities

- spinnaker-dependencies/spinnaker-dependencies.gradle
bump bouncycastle to remove CVE that can cause outofmemory issues amongst other things
> chore(dependencies): bump bouncycastle to 1.64

- spinnaker-dependencies/spinnaker-dependencies.gradle
this allows us to bump Spring to a newer version independent of bumping Spring-Boot
> chore(dependencies): bring in specific spring version

- kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy
This supports the `RequestLoggingFilter` in `gate` which would
benefit from the `AuthenticatedRequest` not being explicitly
cleared.
Specifically, the `RequestLoggingFilter` runs outside the
`AuthenticatedRequestFilter` and is missing some MDC variables
that are being prematurely cleared (X-SPINNAKER-REQUEST/USER).
> feat(web): `AuthenticatedRequest.clear()` is now configurable

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/SpringPluginInfoReleaseSource.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/SpringPluginInfoReleaseSourceTest.kt
We saw an issue wherein plugins failed to load (specifically, all Deck plugins in Gate's plugin cache) because of a bad plugin version configuration.  I think in this scenario it's reasonable to handle the exception so that we can allow other plugins to load.  The other version resolution mechanisms will still run here - latest version, preferred version, and pinned version in front50 - so the plugin will at least still load in a best effort manner.
> fix(plugins): Handle exception due to malformed configuration for plugin version

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
I'd like to get these behind our own DNS and CDN eventually, but I think this may suffice for now?
> feat(plugins): Include spinnaker-official and spinnaker-community repositories by default

- spinnaker-dependencies/spinnaker-dependencies.gradle
There's a fairly critical bug https://github.com/mockk/mockk/issues/510 that results in extremely un-obvious failure modes so rolling back for now
> chore(dependencies): roll back mockk

- kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java
- spinnaker-dependencies/spinnaker-dependencies.gradle
- Bump testcontainers to fix builds on MacOS (https://github.com/testcontainers/testcontainers-java/pull/3159)
- In Clouddriver, we (will) have foreign keys to deal with when and need to cascade.
> test(sql/postgres): bump testcontainers, truncate cascade for PostgreSQL

- kork-credentials-api/src/main/java/com/netflix/spinnaker/credentials/NoopCredentialsLifecycleHandler.java
- kork-credentials/kork-credentials.gradle
- kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CredentialsTypeBaseConfiguration.java
- kork-credentials/src/main/java/com/netflix/spinnaker/credentials/CredentialsTypeProperties.java
- kork-credentials/src/test/java/com/netflix/spinnaker/credentials/CredentialsTypeBaseConfigurationTest.java
This adds an easier way to configure credentials repository. This will be used when converting artifact credentials. For instance, the logic in https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/config/KubernetesConfiguration.java would become:
```
@Bean
public CredentialsTypeProperties<KubernetesNamedAccountCredentials, KubernetesConfigurationProperties.ManagedAccount> kubernetesCredentials(
KubernetesConfigurationProperties configurationProperties,
KubernetesCredentials.Factory kubernetesCredentialFactory) {
return CredentialsTypeProperties.<KubernetesNamedAccountCredentials, KubernetesConfigurationProperties.ManagedAccount>builder()
.credentialsDefinitionClass(KubernetesConfigurationProperties.ManagedAccount.class) …
```
> feat(credentials): easily create customizable credential repositories

- spinnaker-dependencies/spinnaker-dependencies.gradle
Makes sure services are using a more recent commons collection that has some CVE fixes.  3.2.2 is really the last released version of this library, and I'd not expect any additional updates on this particular library.  This fix is a "safeguard" vs. any real known vulnerability that mostly impacts security scans.
> fix(cves): Outdated commons collection library constraints

- kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlers.java
- kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlersMvcSpec.groovy
Replaces a one-off `ExceptionHandler` in `clouddriver`.
See: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/WebConfig.groovy#L97
> feat(web): Generic exception handler support for `IllegalArgumentException`

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
An oddity here, I'm not really sure why things are buggered here for people.
> fix(plugins): Use getter/setters for accessing config flag

- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/internal/ExtensionInvocationHandler.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/internal/ExtensionPointMetadataProvider.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/internal/SpinnakerExtensionPoint.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/proxy/ExtensionInvocationProxy.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/proxy/LazyExtensionInvocationProxy.kt
So a service can have some understanding of plugin IDs associated with extension point instances, if need be.
> feat(plugins): Get plugin ID from proxied spinnaker extension point

- kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java
DSLContext no longer exposes a `close` method, which a couple of tests in Clouddriver want to call.﻿
> use CloseableDSLContext in SqlTestUtil

- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/LatestPluginInfoReleaseSource.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/PreferredPluginInfoReleaseSource.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/SpringPluginInfoReleaseSource.kt
At info level these logs can be a bit noisy, especially since these sources run on a cycle (in the remote plugin cache process).
> chore(plugins): Downgrade plugin release source logging from info to debug

- kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java
- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
Seeing some issues with `clouddriver` that seemingly only
happen when running with the newer jooq.
Reverting until we have time to investigate.
> fix(dependencies): Revert JOOQ upgrade

- kork-retrofit/kork-retrofit.gradle
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandler.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandlerTest.java
cc: @ajordens .. an attempt to address https://github.com/spinnaker/spinnaker/issues/6237
> fix(retrofit): Explicitly mark BAD_REQUEST and NOT_FOUND errors as not retryable

- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/events/Async.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/events/SpinnakerApplicationEvent.java
- kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/events/SpinnakerEventListener.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/ApplicationEventListenerBeanPostProcessor.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/AsyncSpringEventListenerAdapter.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/SpringEventListenerAdapter.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/SpringPluginInitializer.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/v2/ApplicationEventListenerBeanPostProcessorTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/v2/SpringEventListenerAdapterTest.kt
Initial support for allowing plugins to listen on application events.
This comes from a community request to listen in on [BeforeInitialExecutionPersist](https://github.com/spinnaker/orca/blob/master/orca-core/src/main/java/com/netflix/spinnaker/orca/events/BeforeInitialExecutionPersist.java). As with all things, I had to create an adapter to convert from Spring types to non-Spring types.
I'll be making a followup PR to adapt Orca accordingly.
> feat(plugins): Support application event listeners

- kork-plugins-tck/kork-plugins-tck.gradle
- kork-plugins-tck/src/test/kotlin/com/spinnaker/netflix/kork/plugins/TestPluginGeneratorTest.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
Bintray / JCenter is shutting down so I started publishing Strikt to Maven Central. This PR switches us to a newer version that is available from there. There are a couple of minor changes because JVM-specific things have moved to a new sub-module.﻿
> new version of Strikt that is on mavenCentral

- kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
- kork-security/src/test/groovy/com/netflix/spinnaker/security/AuthenticatedRequestSpec.groovy
In cases where the value is not available, `Optional.empty()`
should be returned.
This gets us closer to the behavior that existed prior to the
refactor (and generifying) on 04/19.
> fix(security): `getAuthenticationHeaders()` should support MDC attributes with `null` values

- gradle.properties
- spinnaker-dependencies/spinnaker-dependencies.gradle
Release [1.4.3](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.4.3) just came out and it solves a long-standing issue with coroutine contexts and `ThreadLocal` that we're hoping will finally make our MDC integration in `keel` work! 🙏 
Also bumps Kotlin to 1.4.31.
> chore(deps): Upgrade Kotlin and kotlinx-coroutines

- kork-web/src/main/java/com/netflix/spinnaker/kork/web/interceptors/Criticality.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/interceptors/MetricsInterceptor.java
- kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/interceptors/MetricsInterceptorMicrometerTest.java
- kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/interceptors/MetricsInterceptorSpec.groovy
When we add this annotation to controller methods we will be able to set the criticality of the controller method - this is useful to better setup alerts on failures of only controller methods tagged with a criticality of "high".
> feat(metrics): Add Criticality annotation and use in MetricsInterceptor

- kork-web/src/main/java/com/netflix/spinnaker/kork/web/interceptors/Criticality.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/interceptors/MetricsInterceptor.java
- kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/interceptors/MetricsInterceptorSpec.groovy
Method annotation takes precedence, then to controller (class) annotation, then fallsback to "unknown".
> fix(metrics): Mark metric criticality on controllers

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/SpinnakerPluginService.kt
Reverts spinnaker/kork#853
This wasn't working as intended, and furthermore the lazy proxing is quite nice to inject service beans into plugin beans and vice versa.
> Revert "feat(plugins): Add config property to enable/disable extension proxying"

- .github/workflows/bump_dependencies.yml
- .github/workflows/release.yml
Also dropping the waiting time in the release workflow to make the overall wait time 20 minutes (didn't realize that bumpdeps polls for the artifact for 10 minutes).
> fix(bumpdeps): point to maven central instead of bintray

- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/PluginsConfigurationPropertiesTest.kt
The `spinnaker.extensibility.enable-default-repositories` flag didn't work, which was breaking users who have air-gapped environments and needed to turn the default repos off.
I tried to unify the configuration to be more consistent by just mapping `PluginsConfigurationProperties` with a `Binder` and removed a spot where we were manually mapping a single property (`pluginsRootPath`). I'm not sure why the repositories are handled differently: https://github.com/spinnaker/kork/blob/master/kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java#L136-L142. I can clean that up too if that makes sense.
I initially used the `ConfigResolver` instead of a `Binder`, but decided against it since it doesn't map properties in a way that people will expect. It doesn't do …
> fix(plugins): fixes enable-default-repositories flag

- kork-tomcat/kork-tomcat.gradle
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/DefaultTomcatConnectorCustomizer.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/TomcatConfigurationProperties.java
- kork-tomcat/src/test/java/com/netflix/spinnaker/kork/tomcat/WebEnvironmentTest.java
This particular log is from a test, but in production, we've seen circumstances where various spinnaker microservices log this message, more often under high load:
```
2021-05-04 12:38:10.495  INFO 16142 --- [o-auto-1-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: The HTTP header line [x-dum@my: foo] does not conform to RFC 7230 and has been ignored.
at org.apache.coyote.http11.Http11InputBuffer.skipLine(Http11InputBuffer.java:986) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
at org.apache.coyote.http11.Http11InputBuffer.parseHeader(Http11InputBuffer.java:835) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
at …
```
> Tomcat reject illegal header

- spinnaker-dependencies/spinnaker-dependencies.gradle
Upgrade eureka to resolve below XStream CVEs
[CVE-2021-29505](https://github.com/advisories/GHSA-7chv-rrw6-w6fc)
[CVE-2021-21351](https://nvd.nist.gov/vuln/detail/CVE-2021-21351)
[CVE-2021-21350](https://nvd.nist.gov/vuln/detail/CVE-2021-21350)
[CVE-2021-21347](https://nvd.nist.gov/vuln/detail/CVE-2021-21347)
[CVE-2021-21346](https://nvd.nist.gov/vuln/detail/CVE-2021-21346)
[CVE-2021-21345](https://nvd.nist.gov/vuln/detail/CVE-2021-21345)
[CVE-2021-21344](https://nvd.nist.gov/vuln/detail/CVE-2021-21344)
[CVE-2021-21342](https://nvd.nist.gov/vuln/detail/CVE-2021-21342)
> chore(dependencies): Upgrade eureka-client to resolve xstream CVEs

- build.gradle
- kork-jedis-test/kork-jedis-test.gradle
- kork-plugins/kork-plugins.gradle
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/proxy/aspects/MetricInvocationAspect.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/SpringEventListenerAdapter.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
some dependencies (or transitive dependencies of those) only existed in bintray, not maven
central, and now that bintray is gone, we need to adjust.
> chore(build): use dependencies that exist in maven central

- kork-tomcat/src/test/java/com/netflix/spinnaker/kork/tomcat/CRLFHeaderTest.java
- spinnaker-dependencies/spinnaker-dependencies.gradle
This upgrades tomcat from 9.0.31, which enabled header value validation,
to 9.0.48. The header value validation introduced 3 regressions that
9.0.48 fixes. Upgrading to 9.0.48 also has fixes for the CVEs listed
below
See links for more details:
https://bz.apache.org/bugzilla/show_bug.cgi?id=65272
https://bz.apache.org/bugzilla/show_bug.cgi?id=64210
https://bz.apache.org/bugzilla/show_bug.cgi?id=64192
Associated CVEs:
CVE-2020-1935
CVE-2021-33037
Also pretty sure this [issue](https://github.com/spinnaker/spinnaker/issues/4684) was caused by this.
Signed-off-by: benjamin_j_powell <benjamin_j_powell@apple.com>
> fix(tomcat): upgrades tomcat to 9.0.48

- kork-core/src/main/java/com/netflix/spinnaker/kork/discovery/NoDiscoveryStatusPublisher.java
Trying to fix the `/admin/instance/enabled` endpoint in Orca. One of the reasons why it won't work is that the `NoDiscoveryStatusPublisher` emits `(previous=UNKNOWN, current=DOWN)`, but Keiko expects `(previous=UP, current=DOWN)`: https://github.com/spinnaker/orca/blob/master/keiko-spring/src/main/kotlin/com/netflix/spinnaker/q/discovery/DiscoveryActivator.kt#L43.
This all sort of seems like a hack to me, but I checked the uses of `DiscoveryStatusChangeEvent` across Spinnaker and this seems consistent with how it's used. (e.g., here: https://github.com/spinnaker/swabbie/blob/03e1b624c55340302d7b98459166a3e01e138d98/swabbie-core/src/test/kotlin/com/netflix/spinnaker/swabbie/work/WorkQueueManagerTest.kt#L64)
> fix(no-discovery): publish discovery events as expected by keiko

- spinnaker-dependencies/spinnaker-dependencies.gradle
This fix CVE-2021-29425 for all the following affected spinnaker components:
clouddriver, echo, fiat, front50, gate, halyard, igor, kayenta, rosco
> chore(dependencies): Upgrade commons-io:commons-io to resolve CVE

- spinnaker-dependencies/spinnaker-dependencies.gradle
[CVE-2020-8908](https://nvd.nist.gov/vuln/detail/CVE-2020-8908)
> chore(depenencies): Upgrade com.google.guava to resolve CVE

- kork-jedis-test/kork-jedis-test.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
https://github.com/spinnaker/clouddriver/runs/3355608452 is failing due to 0.8.0 not being available, 0.9.0 is available on mavenCentral
> fix(build): updating embedded redis version

- spinnaker-dependencies/spinnaker-dependencies.gradle
[CVE-2020-7692](https://nvd.nist.gov/vuln/detail/CVE-2020-7692)
Introduced by com.google.api-client:google-api-client in spinnaker-dependencies.
> chore(depenencies): Upgrade google-oauth-client to resolve CVE

- spinnaker-dependencies/spinnaker-dependencies.gradle
[CVE-2019-17195](https://nvd.nist.gov/vuln/detail/CVE-2019-17195)
com.nimbusds:nimbus-jose-jwt is introduced transitively by oracle-sdk, azure-client-auth. Affected spinnaker components are cloudriver, halyard and gate.
> chore(dependencies): Upgrade com.nimbusds:nimbus-jose-jwt to resolve CVE

- spinnaker-dependencies/spinnaker-dependencies.gradle
SONATYPE-2019-0115
org.testng:testng is transitively introduced by org.codehaus.groovy:groovy-testng (part of groovy-all)
> chore(dependencies): Upgrade org.testng:testng to resolve vulnerability

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/allowlist/InstantiationTypeRestrictor.java
When automatically updating base image once per week, we'd like to pin the version number to a particular day of the week: 
```java
LocalDate.now().with(TemporalAdjusters.previous(DayOfWeek.WEDNESDAY)).toString()
```
> feat(expressions): Allow TemporalAdjusters in expressions

- spinnaker-dependencies/spinnaker-dependencies.gradle
Part of spinnaker/spinnaker#6537
Upgrade spring boot from 2.2.5 to 2.2.13. 
Along with it upgrade org.junit:junit-bom to 5.6.3. due to this:
spring boot 2.2.13 uses groovy version 2.5.14, that upgrades org.codehaus.groovy:groovy-test from 2.5.11 (constrained in spinnaker-dependencies) to 2.5.14 and upgrades junit:junit from 4.13 to 4.13.1. 
In kork, org.junit:junit-bom is constrained to 5.6.2, having bug as junit-vintage-engine:5.6.2 does not parse junit version of format x.y.z, just parse x.y. 
This bug is fixed in 5.6.3 and 5.7.0. 
https://github.com/junit-team/junit5/issues/2529   
https://github.com/junit-team/junit5/issues/2198
> chore(dependencies): Upgrade Spring Boot to 2.2.13

- spinnaker-dependencies/spinnaker-dependencies.gradle
In preparation for bumping [spectator](https://github.com/Netflix/spectator) to [1.0.4](https://github.com/Netflix/spectator/releases/tag/v1.0.4) since that brings in 1.12.100.
> chore(dependencies): update the aws sdk to 1.12.100

- kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50PluginsConfiguration.java
- kork-plugins/src/main/java/com/netflix/spinnaker/config/HttpClientSdkConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentConfigResolver.kt
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/FileDownloaderProvider.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/SerdeServiceImplTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientIntegrationTest.kt
When we moved to Jackson 2.12 there were some constructors that weren't
updated and weren't caught until runtime. I don't know enough about
Jackson's Kotlin integration to why this wasn't an issue. I built and
ran tests on master for this project and everything was fine, even after
making the constructor changes.
I tested this change by using composite builds to bring this into rosco
and see that it starts successfully now. I'm not sure if we'll need to
do similar kork bumps in other services.
> fix(plugins): update constructors for jackson mappers

- spinnaker-dependencies/spinnaker-dependencies.gradle
Bumps log4j platform restriction.  Though the core lib is NOT included in dependencies, better safe than sorry...
> fix(security): set platform restriction on log4j

- kork-aws/kork-aws.gradle
Orca in particular (and other services likely) is unable to correctly assume
the IAM role associated with it's pod's service account when deployed to EKS.
It fails with a message like:
Reason: Unable to load AWS credentials from any provider in the chain
This appears to be because orca is not pulling in aws-java-sdk-sts as a dependency
anywhere. Other services like front50 and clouddriver are pulling in this library
and are able to function correctly in this EKS / IRSA deployment scenario.
kork-aws seems to be a good place to put this dependency after discussion on Slack.
I noticed this when trying to configure orca using a secret in secretsmanager.
fixes: https://github.com/spinnaker/spinnaker/issues/6502
> fix(dependencies): add com.amazonaws:aws-java-sdk-sts to kork-aws

- kork-core/kork-core.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
Start moving incrementally towards spring boot v2.5.0, first step being bumping to v2.3.12.RELEASE
Closes https://github.com/spinnaker/spinnaker/issues/6565
`library("Spring Framework", "5.2.15.RELEASE") {`
https://github.com/spring-projects/spring-boot/blob/v2.3.12.RELEASE/spring-boot-project/spring-boot-dependencies/build.gradle#L1676
`library("Groovy", "2.5.14") {`
https://github.com/spring-projects/spring-boot/blob/v2.3.12.RELEASE/spring-boot-project/spring-boot-dependencies/build.gradle#L369
`library("jOOQ", "3.13.6") {`
https://github.com/spring-projects/spring-boot/blob/v2.3.12.RELEASE/spring-boot-project/spring-boot-dependencies/build.gradle#L894
`library("Postgresql", "42.2.20") {`
https://github.com/spring-projects/spring-boot/blob/v2.3.12.RELEASE/spring-boot-project/spring-boot- …
> chore(dependencies): update spring boot

- kork-core/kork-core.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
This reverts commit 2e5e9989310a1ea3cf67d9e98662a30bb361f1e6.
since there are some PRs coming that were written and tested against spring boot 2.2, and
a bit more work to lay the groundwork for spring boot 2.3.
> Revert "chore(dependencies): update spring boot (#939)"

- kork-sql/kork-sql.gradle
This addresses https://github.com/spinnaker/spinnaker/issues/6625
* We observed that when clouddriver starts up, liquibase creates a table in the db and stores a lock, to ensure that only one of the pods can do the schema updates at any given point in time. If the pod is terminated before liquibase can release the lock, no new clouddriver pods can come up since in those pods, liquibase fails to acquire this lock as its held by a now dead pod. This lock has no timeout, so manual intervention is needed to clear this.
* Liquibase is aware of this issue, https://github.com/liquibase/liquibase/issues/1453 and has been working on it for a while. In the meantime, they propose using init containers https://www.liquibase.com/blog/using-liquibase-in-kubernetes  for running the liquibase logic or …
> feat(sql): use sessionlevel locking for liquibase locks

- kork-core/kork-core.gradle
- kork-jedis/kork-jedis.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
Upgraded following dependencies along with spring boot to 2.3.12.RELEASE:
[groovy-all:2.5.14](https://github.com/spring-projects/spring-boot/blob/4d089c4ecb1b356153a80984ef95fff49570eaa7/spring-boot-project/spring-boot-dependencies/build.gradle#L369)
[jooq:3.13.6](https://github.com/spring-projects/spring-boot/blob/4d089c4ecb1b356153a80984ef95fff49570eaa7/spring-boot-project/spring-boot-dependencies/build.gradle#L894)
Cleaned up following dependencies and constraints as being part of spring boot 2.3.12.RELEASE:
[spring-framework-bom:5.2.15.RELEASE](https://github.com/spring-projects/spring-boot/blob/v2.3.12.RELEASE/spring-boot-project/spring-boot-dependencies/build.gradle#L1676)
[assertj-core:3.16.1](https://github.com/spring-projects/spring-boot/blob/v2.3.12.RELEASE/spring-boot-project/sp …
> chore(dependencies): Upgrade Spring Boot to 2.3.12

- kork-secrets-aws/src/main/java/com/netflix/spinnaker/kork/secrets/engines/SecretsManagerSecretEngine.java
- kork-secrets-aws/src/test/java/com/netflix/spinnaker/kork/secrets/engines/SecretsManagerSecretEngineTest.java
- kork-secrets/kork-secrets.gradle
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/SecretConfiguration.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/SecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/StandardSecretParameter.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/engines/NoopSecretEngine.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/OpaqueUserSecret.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/UserSecret.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/UserSecretManager.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/UserSecretMapper.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/UserSecretMixin.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/UserSecretReference.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/UserSecretTypeProvider.java
- kork-secrets/src/test/java/com/netflix/spinnaker/kork/secrets/SecretManagerTest.java
- kork-secrets/src/test/java/com/netflix/spinnaker/kork/secrets/SecretSessionTest.java
- kork-secrets/src/test/java/com/netflix/spinnaker/kork/secrets/user/UserSecretManagerTest.java
- kork-secrets/src/test/java/com/netflix/spinnaker/kork/secrets/user/UserSecretMapperTest.java
- kork-secrets/src/test/java/com/netflix/spinnaker/kork/secrets/user/UserSecretReferenceTest.java
This adds a new UserSecret API to kork-secrets. These secrets provide Fiat role requirements in order to use these secrets. A basic "opaque" user secret type is introduced for transporting Fiat role requirements inside a secret payload, though other types of user secrets can be introduced through an extension mechanism.
See https://github.com/spinnaker/governance/pull/286 for the RFC
> feat(secrets): Add UserSecret API

- kork-web/kork-web.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
With upgrade of spring cloud dependencies, transitive dependency of resilience4j bumped up to 1.7.0. Removed the constraints marked for resilience4j in spinnaker-dependencies.gradle.
Adding runtime dependency of hibernate-validator, which has been removed from resilience4j:1.7.0. It is required by front50, orca and echo.
> chore(dependencies): Upgrade spring cloud dependencies to Hoxton.SR12

- kork-tomcat/kork-tomcat.gradle
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/DefaultTomcatConnectorCustomizer.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/TomcatConfiguration.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/x509/Blocklist.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/x509/BlocklistEnabledDynamicConfigMonitor.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/x509/BlocklistingJSSESocketFactory.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/x509/BlocklistingSSLImplementation.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/x509/BlocklistingX509TrustManager.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/x509/ReloadingFileBlocklist.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/x509/SslExtensionConfigurationProperties.java
This change effectively reverts https://github.com/spinnaker/kork/pull/684
as the removal of this functionality could have disastrous consequences
for operators.  The shameful choice in naming has been addressed.
\#684 was merged without any type of deprecation warning and there
doesn't seem to be an alternative approach for operators relying on the
ability to revoke certificates.
This reverts commit c6b94918d6fd26d1c84af3a4cf53f8cf2f5082e9.
> feat(x509/crl): reimplement the ability to revoke certificates

- spinnaker-dependencies/spinnaker-dependencies.gradle
to stay up to date.
Update jackson-bom to 2.12.6 since that's what version 1.12.176 of the aws sdk brings in
(https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-pom/1.12.176/aws-java-sdk-pom-1.12.176.pom).
> chore(dependencies): update the aws sdk to 1.12.176

- kork-secrets-gcp/kork-secrets-gcp.gradle
- kork-secrets-gcp/src/main/java/com/netflix/spinnaker/kork/secrets/engines/GoogleSecretsManagerSecretEngine.java
- kork-secrets-gcp/src/test/java/com/netflix/spinnaker/kork/secrets/engines/GoogleSecretsManagerSecretEngineTest.java
- spinnaker-dependencies/spinnaker-dependencies.gradle
This PR addresses the issue [#6666](https://github.com/spinnaker/spinnaker/issues/6666). It's not a breaking change.
With this feature, secrets of latest version can be accessed from Google Secret Manager using one of the following patterns:
**encrypted**:google-secrets-manager!p:<PROJECT_NUMBER>!s:<SECRET_ID>!k:<SECRET_KEY>!v:<SECRET_VERSION>
**encrypted**:google-secrets-manager!p:<PROJECT_NUMBER>!s:<SECRET_ID>!v:<SECRET_VERSION>
**encryptedFile**:google-secrets-manager!p:<PROJECT_NUMBER>!s:<SECRET_ID>!v:<SECRET_VERSION> 
v:<SECRET_VERSION> is optional and in it's absence latest secret version is fetched.
> feat(secret engine): Google Secret Manager support

- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/ConnectionPoolProperties.kt
- kork-web/src/main/groovy/com/netflix/spinnaker/okhttp/OkHttpClientConfigurationProperties.groovy
At any kind of scale, some of these settings are rather small.  Let's look at bumping some defaults to a TOUCH more conservative levels.  At least in ways that should NOT be 'negative" impact wise.  These are "max" vs. "min".  Open to discussion as well on the above!
ALSO tweaking certain other defaults including:
* Default disable TLS1.1 please!
* Default JDBC pool settings tuned a bit
* Default http request limits... since most services do calls to things like http://spin-clouddriver/ these are INSANELY small.  Let's fix!
> feat(tuning): Bump up default sizes

- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentConfigResolverTest.kt
- kork-plugins/src/test/resources/testplugin/plugin-empty-config.yml
During upgrade of spring boot from 2.3.x to 2.4.x, encountered the below runtime error while running any spinnaker component (here logs are of fiat component) :
```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.HashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{}')
at [Source: UNKNOWN; line: -1, column: -1]
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
at …
```
> test(plugins): Issue loading empty properties by kork plugin module while upgrading spring boot 2.4.x

- kork-secrets-aws/src/main/java/com/netflix/spinnaker/kork/secrets/engines/SecretsManagerConfiguration.java
- kork-secrets-aws/src/test/java/com/netflix/spinnaker/kork/secrets/engines/SecretsManagerConfigurationTest.java
This fixes a problem with the default configuration when used in other services.
> fix(kork-secrets-aws): Fix default client bean configuration

- kork-core/src/main/java/com/netflix/spinnaker/kork/jackson/JsonTypeNameParser.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/jackson/NamedTypeParser.java
- kork-core/src/main/java/com/netflix/spinnaker/kork/jackson/ObjectMapperSubtypeConfigurer.java
- kork-core/src/test/java/com/netflix/spinnaker/kork/jackson/NamedTypeParserTest.java
- kork-credentials-api/kork-credentials-api.gradle
- kork-credentials-api/src/main/java/com/netflix/spinnaker/credentials/definition/CredentialsType.java
- kork-credentials-api/src/test/java/com/netflix/spinnaker/credentials/definition/CredentialsDefinitionMixin.java
- kork-credentials-api/src/test/java/com/netflix/spinnaker/credentials/definition/CredentialsTypeTest.java
- kork-credentials-api/src/test/java/com/netflix/spinnaker/credentials/definition/TestCredentialsDefinition.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/EncryptedSecret.java
- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/UserSecretManager.java
- kork-secrets/src/test/java/com/netflix/spinnaker/kork/secrets/EncryptedSecretTest.java
- kork-secrets/src/test/java/com/netflix/spinnaker/kork/secrets/user/UserSecretManagerTest.java
- `@CredentialsType` type discriminator
- External secret APIs in `UserSecretManager` (based on `EncryptedSecret` to be analogous to `UserSecret`)
> Add some missing credentials and secrets APIs

- spinnaker-dependencies/spinnaker-dependencies.gradle
With the implementation of secret manager (https://github.com/spinnaker/spinnaker/issues/6666), there is a need to upgrade the version of google-auth-library-oauth2-http library which was introduced as part of gcs secret engine implementation. With the removal of the this dependency constraint, GCS secret engine continue to work without any issue.
> fix(dependencies): remove version constraint on dependency google-auth-library-oauth2-http

- kork-cloud-config-server/kork-cloud-config-server.gradle
- kork-cloud-config-server/src/main/java/com/netflix/spinnaker/kork/configserver/autoconfig/SpringCloudAwsS3ResourceLoaderConfiguration.java
- kork-cloud-config-server/src/main/resources/META-INF/spring.factories
- kork-eureka/src/main/java/com/netflix/spinnaker/kork/eureka/BootHealthCheckHandler.java
- kork-eureka/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaAutoConfiguration.java
- kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentConfigResolver.kt
- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
Upgraded following dependencies along with spring boot to 2.4.13
springCloud : 2020.0.5
While building kork with upgrade, faced errors like:
`
> Task :kork-eureka:compileJava FAILED
/home/opsmx/spinnakerforkcodebase/kork/kork-eureka/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaAutoConfiguration.java:30: error: cannot find symbol
import org.springframework.boot.actuate.health.HealthAggregator;
^
symbol:   class HealthAggregator
location: package org.springframework.boot.actuate.health
/home/opsmx/spinnakerforkcodebase/kork/kork-eureka/src/main/java/com/netflix/spinnaker/kork/eureka/EurekaAutoConfiguration.java:107: error: cannot find symbol
HealthAggregator healthAggregator,
^
symbol:   class HealthAggregator
location: class EurekaAutoConfiguration …
> chore(dependencies): Upgrade Spring Boot to 2.4.13

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/NotEvaluableExpression.java
- kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
**What?**
Spinnaker supports [the expression functions](https://github.com/spinnaker/kork/blob/a4617ed929ca34a2216449425ab5b54b5ac271d5/kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java#L55) e.g. `toJson`, `toBase64`, `fromBase64` and other. At the moment, `toJson` method [throws an exception](https://github.com/spinnaker/kork/blob/a4617ed929ca34a2216449425ab5b54b5ac271d5/kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java#L198-L200) for valid JSON when `${}` expression is defined as a string value
```java
String converted = mapper.writeValueAsString(o);
if (converted != null && converted.contains("${")) {
throw new SpelHelperFunctionException("result for toJson cannot contain an expression");
}
```
We …
> feat(spel): add doNotEval method to restrict expressions evaluation for an object

- spinnaker-dependencies/spinnaker-dependencies.gradle
https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.4.13/spring-boot-dependencies-2.4.13.pom
> chore(dependencies): Use groovy 2.5.15 to match spring boot 2.4.13

- spinnaker-dependencies/spinnaker-dependencies.gradle
https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.4.13/spring-boot-dependencies-2.4.13.pom
> chore(dependencies): use tomcat 9.0.55 to match spring boot 2.4.13

- gradle.properties
- kork-runtime/kork-runtime.gradle
- settings.gradle
To reduce code size and exposure to vulnerabilities when certain modules aren't being used.  Note that this doesn't actually change anything, but it makes it easier to do so.
> feat(build): make the modules that kork-runtime includes configurable

- spinnaker-dependencies/spinnaker-dependencies.gradle
since spring boot 2.4.13 brings in 3.11 (see https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.4.13/spring-boot-dependencies-2.4.13.pom).
> chore(dependencies): unpin org.apache.commons:commons-lang3:3.9

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandlerTest.java
When socket timeouts occur the response body is null which results in an
empty message being sent back to deck which is not useful.
Signed-off-by: benjamin_j_powell <benjamin_j_powell@apple.com>
> fix(exceptions): Exception message should never be empty

- kork-credentials/kork-credentials.gradle
- kork-credentials/src/main/java/com/netflix/spinnaker/credentials/jackson/Sensitive.java
- kork-credentials/src/main/java/com/netflix/spinnaker/credentials/jackson/SensitiveAutoConfiguration.java
- kork-credentials/src/main/java/com/netflix/spinnaker/credentials/jackson/SensitiveProperties.java
- kork-credentials/src/main/java/com/netflix/spinnaker/credentials/jackson/SensitiveSerializer.java
- kork-credentials/src/main/resources/META-INF/spring.factories
- kork-credentials/src/test/java/com/netflix/spinnaker/credentials/jackson/SensitiveAccount.java
- kork-credentials/src/test/java/com/netflix/spinnaker/credentials/jackson/SensitiveSerializerTest.java
This adds a new `Sensitive` annotation to explicitly mark fields as sensitive. A sensitive field will not be serialized to JSON unless its value is a `secret://...` URI to avoid leaking credentials. This serializer also provides a configurable regular expression to match against `CredentialsDefinition` property names to mark them as likely sensitive which applies masking in addition to logging a warning so that the affected class can be updated.
> feat(secrets): Add credentials masking in JSON

- spinnaker-dependencies/spinnaker-dependencies.gradle
Bump `commons-io` to `2.11.0` which fixed the cleaning
directory behavior when there is symlink.
In version `2.7.0` the delete directory will first check
if the file exists with `Files.exists`, then issue a deleting with
`File.deleteIfExists`. However when it's a symlink, the default
behavior for `Files.exists` is to follow link, if the file/directory
the symlink pointing to has been deleted, the symlink itself will not
be deleted, this will causes error with `deleteDirectory` when there
is still symlink left in the directory.
In the newer version will add `NOFOLLOW_LINK` option on the `File.exists`
check, therefore it will work as expected.
> fix(artifact/gitrepo): resolve symlink clean error

- spinnaker-dependencies/spinnaker-dependencies.gradle
It would be nice to jump all the way to 1.33 to get all the way up to date, and to resolve these CVEs:
CVE-2022-25857 (1.31), CVE-2022-38749 (1.31), CVE-2022-38750 (1.31), CVE-2022-38751 (1.32) and CVE-2022-38752 (1.32).
However, https://github.com/spring-projects/spring-boot/issues/32228#issue-1361858500 says to stick with 1.29 until >= 2.6.12, as [the commit that resolved that issue](https://github.com/spring-projects/spring-boot/commit/724f9ebf7107d99ac9bae4204b4f7c6444a49e03) went in to 2.6.12.
Note that spring boot 2.4.13 brings in version 1.27 (see https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.4.13/spring-boot-dependencies-2.4.13.pom).
2.5.14 brings in 1.28 (see https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-depend …
> chore(deps): specify version 1.29 of org.yaml:snakeyaml to stay partially up to date

- kork-aws/kork-aws.gradle
- kork-core-tck/kork-core-tck.gradle
- kork-web/kork-web.gradle
Removing this large dependency is generally good.  The specific motivation in this case is to get `org.testng:testng:7.4.0` out of shipping code, since it's vulnerable to CVE-2022-4065.
> chore(dependencies): remove dependency on groovy-all in non-test configurations

- kork-config/kork-config.gradle
- kork-config/src/main/java/com/netflix/spinnaker/kork/boot/DefaultPropertiesBuilder.java
- kork-config/src/test/java/com/netflix/spinnaker/kork/boot/DefaultPropertiesBuilderTest.java
- kork-config/src/test/java/com/netflix/spinnaker/kork/boot/TestApplication.java
With spring boot 2.4, spring location properties will no longer fail silently if the file or folder does not exist. Now, requires prefix "optional:" for the location.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#config-file-processing-application-properties-and-yaml-files
And introducing new spring additional data importing property suggested in the links below, to be used with Spring boot 2.4:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide
https://docs.spring.io/spring-boot/docs/2.4.0/reference/html/spring-boot-features.html#boot-features-external-config-files-importing
> fix(config): Issue with non-existing file/folder location used in Spring properties while upgrading spring boot 2.4.x.

- spinnaker-dependencies/spinnaker-dependencies.gradle
to avoid ArrayOutOfBoundsException parsing some yaml (including k8s manifests) with snakeyaml 1.29.  See https://github.com/spring-projects/spring-boot/issues/30159#issuecomment-1125969155 for details.
> fix(dependencies): use snakeyaml 1.27

- kork-secrets-aws/kork-secrets-aws.gradle
When running the service in an environment requires to assume into another role to fetch the required secrets, it will require the `aws-java-sdk-sts`. This happens when the service is running as EKS pod with service account associated with an IAM role.
> fix(dependencies): include aws-java-sdk-sts

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitExceptionHandlers.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitExceptionHandlersTest.java
Created a new method getResponseCode which will return status code of SpinnakerHttpException.
Removed to the getResponse method as all the services using the method to get the Status code only so getResponseCode method will get used instead of getResponse().getStatus()
> refactor(SpinnakerHttpException): created a method which return status code

- kork-web/src/main/java/com/netflix/spinnaker/kork/web/selector/ByCloudProviderServiceSelector.java
Last comment in https://github.com/spinnaker/kork/pull/967 for background.
As it turns out, `List<String>` doesn't work, and Orca blows up in spectacular fashion. My guess is because the constructor arg is a `Map<String, Object>`, Jackson doesn't know how to handle the `Object` and defaults to `LinkedHashMap`.
I don't want to break existing configs, so just fixing this selector class to use a `Map`. Eurgh.
cc @dbyron-sf
> fix(selectors): fix type cast error on cloud provider selector

- spinnaker-dependencies/spinnaker-dependencies.gradle
With the release of new minor version in release train Ilford, upgrading spring cloud from 2020.0.5 to 2020.0.6. [https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#202006]
> chore(dependency): upgrading spring cloud to 2020.0.6

- spinnaker-dependencies/spinnaker-dependencies.gradle
spring boot 2.4.13 brings in logback 1.2.7 which is vulnerable to CVE-2021-42550, fixed in 1.2.9.  spring boot 2.5.14 brings in 1.2.11 (the newest as of 7-feb-23), but use 1.2.10 to avoid https://jira.qos.ch/browse/LOGBACK-1623 which makes V2BakeryControllerTest in rosco hang.
> chore(dependencies): use version 1.2.10 of logback to resolve CVE-2021-42550

- spinnaker-dependencies/spinnaker-dependencies.gradle
Here's a snippet of ./gradlew kork-tomcat:dependencies before this change:
```
+--- org.springframework.boot:spring-boot-starter-tomcat:2.4.13
|    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
|    +--- org.apache.tomcat.embed:tomcat-embed-core:9.0.55 -> 9.0.62
|    +--- org.glassfish:jakarta.el:3.0.4
|    \--- org.apache.tomcat.embed:tomcat-embed-websocket:9.0.55 -> 9.0.62
|         \--- org.apache.tomcat.embed:tomcat-embed-core:9.0.62
```
and with this change:
```
+--- org.springframework.boot:spring-boot-starter-tomcat:2.4.13
|    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
|    +--- org.apache.tomcat.embed:tomcat-embed-core:9.0.55 -> 9.0.69
|    +--- org.glassfish:jakarta.el:3.0.4
|    \--- org.apache.tomcat.embed:tomcat-embed-websocket:9.0.55 -> 9.0.69
|         \--- …
```
> chore(deps): use version 9.0.69 of tomcat to resolve CVE-2022-42252 and CVE-2022-45143

- spinnaker-dependencies/spinnaker-dependencies.gradle
CVE-2020-0187:      fixed in 1.67
CVE-2020-15522:     fixed in 1.66
sonatype-2019-0673: fixed in 1.70
sonatype-2020-0770: fixed in 1.67
sonatype-2021-4916: fixed in 1.69
> chore(dependencies): use version 1.70 of bouncycastle to address multiple CVEs

- kork-web/src/main/java/com/netflix/spinnaker/kork/web/context/MdcCopyingAsyncTaskExecutor.java
- kork-web/src/test/java/com/netflix/spinnaker/kork/web/context/MdcCopyingAsyncTaskExecutorTest.java
This is a corner case that's unlikely to happen, but we may as well fix it.
> fix(web): properly handle an empty MDC in MdcCopyingAsyncTaskExecutor

- kork-proto/kork-proto.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
to resolve CVE-2022-3171 (fixed in 3.19.6) and CVE-2022-3509 (fixed in 3.21.7) and to stay up to date.  3.21.12 is currently the latest version, published 14-dec-2022.
Move com.google.protobuf:protobuf-bom above com.google.cloud:libraries-bom so it takes precedence.  Otherwise some transitive dependencies of libraries-bom override the versions in protobuf-bom.
> chore(dependencies): use version 3.21.12 of com.google.protobuf

- spinnaker-dependencies/spinnaker-dependencies.gradle
**Before applying the constraint**
```
./gradlew gate-saml:dependencyInsight --dependency esapi                
> Task :gate-saml:dependencyInsight
org.owasp.esapi:esapi:2.1.0.1
variant "compile" [
org.gradle.status              = release (not requested)
org.gradle.usage               = java-api
org.gradle.libraryelements     = jar (compatible with: classes+resources)
org.gradle.category            = library
Requested attributes not found in the selected variant:
org.gradle.dependency.bundling = external
org.gradle.jvm.version         = 11
]
org.owasp.esapi:esapi:2.1.0.1
\--- org.springframework.security.extensions:spring-security-saml2-core:1.0.9.RELEASE
+--- compileClasspath (requested org.springframework.security.extensions:spring-security-saml2-core)
+--- …
```
> fix(cve): Remove CVE-2022-23457 caused by esapi library version 2.1.0.1 that is resolved transitively trough spring-security-saml-dsl-core

- kork-aws/kork-aws.gradle
- kork-core/kork-core.gradle
- kork-exceptions/kork-exceptions.gradle
- kork-jedis/kork-jedis.gradle
- kork-pubsub-aws/kork-pubsub-aws.gradle
- kork-security/kork-security.gradle
- kork-telemetry/kork-telemetry.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
Removed `groovy-all` from kork-exception, kork-security, kork-pubsub-aws, kork-telemetry, kork-jedis, kork-aws, kork-core and spinnaker-depndencies.
> chore(dependencies): remove dependency on groovy-all from kork

- kork-jedis/kork-jedis.gradle
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisPool.java
- kork-jedis/src/test/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisPoolTest.java
The internalPool field is declared in JedisPool's super class, getDeclaredField("internalPool") could not get internalPool field from super class.
> fix(jedis): get reference to delegate's internal pool

- build.gradle
- gradle/kotlin-test.gradle
- gradle/kotlin.gradle
- kork-api/kork-api.gradle
- kork-artifacts/kork-artifacts.gradle
- kork-cloud-config-server/kork-cloud-config-server.gradle
- kork-config/kork-config.gradle
- kork-credentials-api/kork-credentials-api.gradle
- kork-credentials/kork-credentials.gradle
- kork-expressions/kork-expressions.gradle
- kork-plugins-tck/kork-plugins-tck.gradle
- kork-secrets-aws/kork-secrets-aws.gradle
- kork-sql-test/kork-sql-test.gradle
- kork-web/kork-web.gradle
- kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/selector/SelectableServiceSpec.groovy
Spring boot 2.4.x removed JUnit5 vintage engine from spring-boot-starter-test. 
[https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test] 
It is required for executing junit4 based test cases in kork. So, introducing junit-vintage-engine dependency in build.gradle, using testRuntimeOnly() as suggested in section 3.1 of https://junit.org/junit5/docs/5.6.2/user-guide/index.pdf
After applying this fix, coverage increased from 458 to 515 test case executions.
Clean up the call for test engines using `useJUnitPlatform()` from sub-modules, and placing it in build.gradle. As per the gradle docs, all test engines on the test runtime classpath will be used by sub modules. …
> fix(tests): Introduce junit5 vintage engine for running junit4 test cases over junit5 and cleanup of useJUnitPlatform() from sub-modules in kork

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandlerTest.java
This PR adds a `getHeaders()` method to `SpinnakerHttpException` so that the response headers for an HTTP request can be examined during exception handling. This is needed as part of the effort to [consume SpinnakerRetrofitHandler in each service](https://github.com/spinnaker/spinnaker/issues/5473).
> feat(retrofit): Add getHeaders() method to SpinnakerHttpException

- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedis.java
- kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisPool.java
- kork-web/src/main/groovy/com/netflix/spinnaker/config/ErrorConfiguration.groovy
- kork-web/src/main/java/com/netflix/spinnaker/kork/web/controllers/GenericErrorController.java
- spinnaker-dependencies/spinnaker-dependencies.gradle
Spring boot 2.5.x brings groovy 3.x as its transitive dependency.
https://docs.spring.io/spring-boot/docs/2.5.14/reference/html/dependency-versions.html#appendix.dependency-versions
Currently spinnaker services use gradle 6.x, that does not support groovy 3.x.
https://docs.gradle.org/6.8.1/userguide/compatibility.html
Restricting groovy to 2.5.x using the code snippet suggested below, till upgrade of gradle to 7.x.
https://docs.gradle.org/current/userguide/resolution_rules.html#sec:denying_version
##############################################################################
fix(dependency): Issue with kork-jedis while upgrading spring-boot to 2.5.14
While upgrading the spring-boot, the compilation of kork-jedis module failed with following error:
```
> Task :kork-jedis:compileJava FAILED …
```
> chore(dependencies): Upgrade Spring Boot to 2.5.14 

- .github/workflows/release.yml
to avoid warning messages like
Run echo ::set-output name=REPO::${GITHUB_REPOSITORY##*/} Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore(gha): replace deprecated set-output commands with environment files

- kork-web/kork-web.gradle
now that https://github.com/spinnaker/kork/pull/1004 introduced a HttpLoggingInterceptor.Level bean in kork-web's RetrofitConfiguration class.
This fixes failures like https://github.com/spinnaker/orca/actions/runs/4598191534/jobs/8121901031?pr=4442 and https://github.com/spinnaker/gate/actions/runs/4598187183/jobs/8121890373?pr=1647
> fix(web): com.squareup.okhttp3:logging-interceptor is an api dependency

- spinnaker-dependencies/spinnaker-dependencies.gradle
See: https://github.com/ESAPI/esapi-java-legacy/issues/567
and
https://github.com/spinnaker/kork/pull/1020#issuecomment-1495005465
ESAPI on newer releases removed a class that opensaml referenced in a hard coded manner.  We need to bump opensaml to a later release & do a LOT more validation.
> fix(saml): revert esapi library change

- .github/workflows/bump_dependencies.yml
since halyard's versioning scheme doesn't match the rest of spinnaker.
Similar to https://github.com/spinnaker/fiat/pull/947, with the fixes from https://github.com/spinnaker/fiat/pull/974 and https://github.com/spinnaker/fiat/pull/975.
Also see https://github.com/spinnaker/spinnaker/projects/20#card-85655999.
> fix(gha): only create autobump PRs in halyard on master

- kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/SpinnakerException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerNetworkException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandler.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandlerTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerExceptionTest.java
Adding utility methods on the SpinnakerRetrofitErrorHandler, as well as the SpinnakerException and all exceptions that inherit from SpinnakerException. These methods make it easier to add custom messages when dealing with SpinnakerExceptions
> feat(retrofit): add utility methods for improved exception handler (#82)

- spinnaker-dependencies/spinnaker-dependencies.gradle
While executing the build script with --warning-mode=fail received below error:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0
```
And the deprecated gradle features are:
```
> Configure project :spinnaker-dependencies
Using force on a dependency has been deprecated. This is scheduled to be removed in Gradle 7.0. Consider using strict version constraints instead (version { strictly ... } }). Consult the upgrading guide for further information: https://docs.gradle.org/6.8.1/userguide/upgrading_version_5.html#forced_dependencies
at spinnaker_dependencies_dcuj2z1cy4y7qsfj67cdmxmxr$_run_closure3$_closure4.doCall(/kork/spinnaker-dependencies/spinnaker-dependencies.gradle:66)
(Run with --stacktrace to get the full stack trace of this deprecation …
```
> refactor(deprecation): remove deprecated gradle constructs/features from kork in order to upgrade gradle 7

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/config/ExpressionProperties.java
Enabling “doNotEval” SPeL expression by default. This feature is disabled only when the flag is set explicitly to false.
Context reference ->  PR[ #1028](https://github.com/spinnaker/kork/pull/1028)
> feat(doNoEval): Default the “doNotEval” SPeL expression to ON

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
refactor(retrofit): Move rawMessage and response body map to SpinnakerHttpException as network / unexpected do not have a json response body
The ErrorHandlingExecutorCallAdapterFactory::execute() does not return/add a retrofit2 Response body if either of:
* network error like IOException(SpinnakerNetworkException) during server communication occurs or
* unexpected error like RuntimeException(SpinnakerServerException) while creating/decoding the request/response is thrown
> refactor(retrofit): Move rawMessage and response body map to SpinnakerHttpException

- kork-moniker/kork-moniker.gradle
While running test task with kork-moniker, groovy based tests are not detected and executed. To fix this, applying the groovy plugin in kork-moniker.gradle for detection and execution of groovy based tests. After fix, overall test executions increased from 539 to 584.
> fix(tests): apply groovy plugin for groovy based kork-moniker tests

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/ErrorHandlingExecutorCallAdapterFactory.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/Retrofit2SyncCall.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/RetrofitException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerNetworkException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandler.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/RetrofitExceptionTest.java
since it isn't using any retrofit-specific information from them.  This also removes the
potential to pass an http exception (e.g. a return value from RetrofitError.httpError) to
a SpinnakerServerException constructor, instead of SpinnakerHttpException.
> refactor(retrofit): remove retrofit-related constructors from SpinnakerServerException

- kork-artifacts/kork-artifacts.gradle
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/ArtifactTypes.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/README.md
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactDecorator.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactDeserializer.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStore.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfiguration.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfigurationProperties.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreURIBuilder.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreURISHA256Builder.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/EmbeddedArtifactSerializer.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStore.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/Artifact.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactDeserializerTest.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/EmbeddedArtifactSerializerTest.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifactTest.java
- kork-expressions/kork-expressions.gradle
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ArtifactUriToReferenceConverter.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
- kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
- kork-secrets-aws/src/main/java/com/netflix/spinnaker/kork/secrets/engines/SecretsManagerSecretEngine.java
- spinnaker-dependencies/spinnaker-dependencies.gradle
This commit adds a new feature called ArtifactStore. This allows for storage of embedded/base64 types to some storage, eg S3. So instead of having duplication of some artifact in a context, it'll now be referenced by a artifact URI.
Also, there's a nice README that explains various settings as well as how to setup a local S3 for testing artifact storage
[README link](kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/README.md )
The related PRs
https://github.com/spinnaker/clouddriver/pull/5976
https://github.com/spinnaker/orca/pull/4481
https://github.com/spinnaker/rosco/pull/998
https://github.com/spinnaker/gate/pull/1674
Further to enable this feature can be enabled via feature flag
```yaml
artifactStore:
enabled: true
applicationsRegex: "only-these-applications-*" # …
```
> feat(artifacts): Add ArtifactStore to Kork

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ArtifactUriToReferenceConverter.java
- kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
The type interceptor for detecting remote artifact URIs was not properly delegating `canConvert`, which resulted in only String -> String being auto-converted in SpEL.
This breaks many expressions, as SpEL's default `StandardTypeConverter` handles common cases like int -> long.
> fix(expressions): Restore delegation to default SpEL type converter

- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/EmbeddedArtifactSerializerTest.java
When I was refactoring the EmbeddedArtifactSerializerTest it looks like I copy pasta'd the same test vector twice. This commit addresses that and fixes it
> fix(artifacts): Fix test duplication in artifact store

- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/telemetry/HikariSpectatorMetricsTracker.kt
The SQL pool gauge metrics are disappearing due to the adhoc gauge objects being garbage collected. This change fixes the pool metrics to be class variables instead and hence avoid being garbage collected. The micrometer docs also alludes to this [issue](https://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing).
> fix(kork-sql): Use class variables for hikari pool metrics

- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpExceptionTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerExceptionTest.java
refactor(retrofit/test): moved http tests to new SpinnakerHttpExceptionTest class
> refactor(retrofit/test): moved http tests to new SpinnakerHttpExceptionTest class

- kork-artifacts/kork-artifacts.gradle
- kork-core/kork-core.gradle
- kork-credentials/kork-credentials.gradle
- kork-secrets/kork-secrets.gradle
- kork-security/kork-security.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
and make dependencies on log4j-api explicit.
https://github.com/spinnaker/kork/pull/1069 introduced the dependency on org.apache.logging.log4j.log4j-core in kork-artifacts, but it's not necessary.  At least, after removing it, and verifying the dependency is gone from
```
$ ./gradle kork-artifacts:dependencies
```
the code still builds fine.  As well
```
$ git grep "import org.apache.logging.log4j"
kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/user/UserSecretTypeProvider.java:import org.apache.logging.log4j.LogManager; kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequestDecorator.java:import org.apache.logging.log4j.ThreadContext;
```
turns up classes present in log4j-api, but nothing in log4j-core.
As well uses of the `@Log4j2` annotation depend …
> chore(dependencies): remove unnecessary dependency on log4j-core

- spinnaker-dependencies/spinnaker-dependencies.gradle
Consumed the modified kork to build and test all spinnaker components, all build successfully and test passed. Below is the difference in version of json-smart before and after the logback upgrade (in gate):
```
$ ./gradlew gate-web:dI --dependency json-smart --configuration testCompileClasspath
> Task :gate-web:dependencyInsight
net.minidev:json-smart:2.4.1
Variant compile:
| Attribute Name                 | Provided | Requested         |
|--------------------------------|----------|-------------------|
| org.gradle.status              | release  |                   |
| org.gradle.category            | library  | library           |
| org.gradle.libraryelements     | jar      | classes+resources |
| org.gradle.usage               | java-api | java-api          |
| …
```
> chore(dependency): unpin json-smart

- spinnaker-dependencies/spinnaker-dependencies.gradle
Consumed the modified kork to build and test all spinnaker components, all build successfully and test passed. Below is the difference in version of junit-bom before and after the junit-bom unpin (in gate):
```
$ ./gradlew gate-web:dI --dependency org.junit.jupiter --configuration testCompileClasspath
> Task :gate-web:dependencyInsight
org.junit.jupiter:junit-jupiter:5.6.3
Variant apiElements:
| Attribute Name                 | Provided | Requested         |
|--------------------------------|----------|-------------------|
| org.gradle.status              | release  |                   |
| org.gradle.category            | library  | library           |
| org.gradle.dependency.bundling | external | external          |
| org.gradle.jvm.version         | 8        | 11                |
| …
```
> chore(dependency): unpin junit-bom

- kork-retrofit/kork-retrofit.gradle
With RetrofitError (from retrofit1) and retrofit2.client.Response and retrofit2.Response as SpinnakerHttpException constructor arguments, code that uses SpinnakerHttpException needs these jars.
Without them,
https://github.com/spinnaker/clouddriver/actions/runs/5967605769/job/16189606342 fails with:
```
./gradlew :clouddriver-aws:integrationTest
> Task :clouddriver-aws:compileTestGroovy FAILED
FAILURE: Build failed with an exception.
* What went wrong: Execution failed for task ':clouddriver-aws:compileTestGroovy'.
> retrofit2.Response
```
> fix(retrofit): change retrofit and retrofit2 into api dependencies

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpExceptionTest.java
when there's no message from the http response body
For example:
before: Status: 500, URL: https://some-url, Message: 500 arbitrary reason
after: Status: 500, URL: https://some-url, Message: arbitrary reason
> fix(retrofit): remove duplicate http response code from SpinnakerHttpException message

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactDeserializer.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactReferenceURI.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStore.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreURIBuilder.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreURISHA256Builder.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStore.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactDeserializerTest.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactReferenceURITest.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreURISHA256BuilderTest.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ArtifactUriToReferenceConverter.java
- kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
This commit adds a new URI type to the artifact store signature. This allows for storage implementation to more easily use certain pieces of the URI for storage. For example, with this commit, artifacts stored as S3 objects will no longer have the `ref://` prefix, allowing for a better AWS console experience
> feat(artifacts): Add ArtifactReferenceURI to artifact store

- kork-artifacts/kork-artifacts.gradle
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactDeserializer.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/EmbeddedArtifactSerializer.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/exceptions/ArtifactStoreIOException.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStore.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/EmbeddedArtifactSerializerTest.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/exceptions/ArtifactStoreIOExceptionTest.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreTest.java
Prior to this commit, when the head object in s3 artifact store throws an exception in (de)serializer, we get a pretty bland exception back
```json
{"timestamp":"2023-09-25T17:54:02.550+00:00","status":500,"error":"Internal
Server Error"}
```
With this commit we will now see:
```json
{"timestamp":"2023-10-02T23:21:42.183+00:00","status":500,"error":"Internal Server Error","exception":"com.netflix.spinnaker.kork.artifacts.artifactstore.exceptions.ArtifactStoreIOException","message":"com.netflix.spinnaker.kork.exceptions.SpinnakerException: Failed to query artifact due to IAM permissions either on the bucket or object"}
```
The fix here was to intercept any `Exception` from the artifact store calls and ensure we rethrow a `ArtifactStoreIOException`. The reason why we rethrow an …
> fix(artifact): Handle exceptions better in artifact store

- kork-core/kork-core.gradle
since it results in these errors during testing:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/dbyron/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.36/a41f9cfe6faafb2eb83a1c7dd2d0dfd844e2a936/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/dbyron/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.12/d4dee19148dccb177a0736eb2027bd195341da78/logback-classic-1.2.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```
> fix(core/test): remove runtime dependency on org.slf4j:slf4j-simple

- build.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
Spring boot 2.5.14 transitively brings groovy 3.0.10 as mentioned [here](https://docs.spring.io/spring-boot/docs/2.5.14/reference/html/dependency-versions.html#appendix.dependency-versions)
Removed constraints of org.apache.ant because groovy-ant:3.0.10 (transitively introduced by spring boot 2.5.14) brings ant:1.10.12. https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-ant/3.0.10
Removed constraints of org.testng:testng:7.4.0 because groovy-testng:3.0.10 brings testng:7.5
https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-testng/3.0.10
Spring boot 2.5.14 upgrade brings io.rest-assured 4.3.3 as transitive dependency. We had [pinned to the nearest version (4.2.0) using groovy 2.x](https://github.com/spinnaker/kork/commit/f841432dfb6e84ebf0412c46720548514d3a4e59). Now …
> chore(dependency): upgrade to groovy 3.x and related cleanup

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/ErrorHandlingExecutorCallAdapterFactory.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/Retrofit2SyncCall.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerConversionException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerNetworkException.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandler.java
- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/Retrofit2SyncCallTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpExceptionTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofit2ErrorHandleTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandlerTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitExceptionHandlersTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerExceptionTest.java
so it's available to exception handling code that currently has access to the url via RetrofitError.
> feat(retrofit): move url attribute from SpinnakerHttpException to SpinnakerServerException

- kork-crypto/src/main/java/com/netflix/spinnaker/kork/crypto/CipherSuites.java
- kork-tomcat/kork-tomcat.gradle
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/TomcatConfigurationProperties.java
- kork-web/src/main/groovy/com/netflix/spinnaker/okhttp/OkHttpClientConfigurationProperties.groovy
This adds a common `CipherSuites` class for listing various profiles of cipher suites for use with TLS. The default cipher suites and TLS versions are updated to a slightly more secure version of the intermediate compatibility baseline from the Mozilla recommendations. These settings are used for both Tomcat and OkHttpClient. Of particular note, this adds in the required ciphers in TLS 1.3 to improve compatibility with modern clients and servers.
> config(crypto): Update the default TLS cipher suites

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifact.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/model/ExpectedArtifactTest.java
When expected artifact does matching on a base64 reference, containing special regex characters, it will attempt pattern matching where ‘+’ actually means something in regex and will fail matches because of this. This commit ensures that all base64 characters can be matched against that may not be valid regex expression.
Example pipeline:
```json
{
"application" : "spinnaker-ci",
"description" : "This pipeline ensures that artifacts with regex characters like '+' succeed in pipelines.",
"expectedArtifacts" : [ {
"defaultArtifact" : {
"artifactAccount" : "embedded-artifact",
"id" : "f435c890-c5b6-4bdb-a733-d788413fd5c1",
"type" : "embedded/base64"
},
"displayName" : "regex-artifact",
"id" : "be22c2c5-6561-4f41-b885-367ef91b8362",
"matchArtifact" : {
"artifactAccount" : "embedded-artifact", …
```
> fix(artifacts): references containing '+' break matching

- spinnaker-dependencies/spinnaker-dependencies.gradle
Removed constraint of ch.qos.logback because spring boot 2.5.15 brings logback:1.2.12.
Removed platform dependency com.fasterxml.jackson:jackson-bom because spring boot 2.5.15 brings jackson:2.12.7.20221012
Groovy get transitively upgraded to 3.0.17
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.5.15/spring-boot-dependencies-2.5.15.pom
> chore(dependency): upgrade spring boot to 2.5.15 and related cleanup

- kork-runtime/kork-runtime.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
It is observed that the snakeyaml version is not resolved to intended 1.27 for some of the modules. Hence making it strictly 1.27.
> chore(dependencies): make snakeyaml version strictly to 1.27

- spinnaker-dependencies/spinnaker-dependencies.gradle
to stay up to date and to resolve CVE-2021-2471 and CVE-2022-21363
[Spring boot 2.5.15](https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.5.15/spring-boot-dependencies-2.5.15.pom) uses version 8.0.33.
> chore(deps): use version mysql:mysql-connector-java from spring boot

- gradle.properties
- gradle/kotlin-test.gradle
- gradle/kotlin.gradle
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/PluginSecretTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/v2/scenarios/ComplexInjectionScenarioTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/v2/scenarios/ServiceDependenciesScenarioTest.kt
- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/v2/scenarios/ServiceInjectionScenarioTest.kt
- spinnaker-dependencies/spinnaker-dependencies.gradle
Upgrade kotlin from 1.4.0 to 1.5.32, in order to sync with spring boot 2.5.15. 
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.5.15/spring-boot-dependencies-2.5.15.pom
Upgrade kotlinx-coroutines-bom to 1.5.2, in order to sync with kotlin 1.5.x. 
https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.2/kotlinx-coroutines-core-jvm-1.5.2.pom
While upgrading kotlin 1.5.32, encounter below errors in kork-plugins module:
```
Unstarted application context org.springframework.boot.test.context.assertj.AssertableApplicationContext[startupFailure=org.springframework.beans.factory.parsing.BeanDefinitionParsingException] failed to start
java.lang.IllegalStateException: Unstarted application context …
```
> chore(dependency): upgrade kotlin to 1.5.32

- kork-secrets/src/main/java/com/netflix/spinnaker/kork/secrets/SecretAwarePropertySource.java
Recent changes to [SecretAwarePropertySource](https://github.com/spinnaker/kork/commit/4f71ac098c3b12c9aa8e3687a2d2c3b888fc1491#diff-a3d16fc3a6300b3565baa051815c4529df6eb7c463753c29a229b1cf25c78db4) broke the clouddriver code and the below error is thrown when clouddriver is started. The fix is to make delegate(underlying PropertySource) accessible so that the clouddriver can make use of it to identify BootstrapPropertySource.
```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: 
Error creating bean with name 'configurationRefreshListener' defined in URL [jar:file:/usr/lib/spinnaker-clouddriver/lib/clouddriver-web.jar!/com/netflix/spinnaker/clouddriver/listeners/ConfigurationRefreshListener.c …
```
> fix(PropertySource): add a delegate accessor to SecretAwarePropertySource

- spinnaker-dependencies/spinnaker-dependencies.gradle
After https://github.com/spinnaker/kork/pull/1117, these comments are no longer relevant.
> chore(liquibase): remove stale comments

- gradle/kotlin-test.gradle
- gradle/kotlin.gradle
- gradle/lombok.gradle
- kork-actuator/kork-actuator.gradle
- kork-plugins-spring-api/kork-plugins-spring-api.gradle
When projects have dependencies on artifacts, but depend on spinnaker-dependencies to provide the version, this makes the version available and removes failures from ./gradlew dependencies output.
Some examples of failures that this removes:
```
testRuntimeOnlyDependenciesMetadata
+--- org.junit.jupiter:junit-jupiter-engine FAILED \--- org.junit.platform:junit-platform-launcher FAILED
compileOnly - Compile only dependencies for compilation 'main' (target  (jvm)). \--- org.projectlombok:lombok FAILED
compileOnlyDependenciesMetadata
\--- org.projectlombok:lombok FAILED
testCompileOnly - Compile only dependencies for compilation 'test' (target  (jvm)). \--- org.projectlombok:lombok FAILED
testCompileOnlyDependenciesMetadata
\--- org.projectlombok:lombok FAILED
```
> chore(dependencies): add dependencies on spinnaker-dependencies

- spinnaker-dependencies/spinnaker-dependencies.gradle
Correct coordinate of jsch dependency is com.jcraft:jsch.
https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.54/jsch-0.1.54.pom
> chore(dependency): refactor correct coordinate of jsch dependency

- spinnaker-dependencies/spinnaker-dependencies.gradle
to stay up to date.  Previously, org.spockframework:spock-core:2.0-groovy-3.0 and spring boot 2.5.15 brought in org.junit:junit-bom:5.7.2.  5.10.1 is currently the latest, but it causes failures in echo, so let's take a smaller step.  Spring boot 2.6.15 brings in 5.8.2 as well.
> chore(dependencies): specify org.junit:junit-bom:5.8.2

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/README.md
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactReferenceURI.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStore.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreConfigurationProperties.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreURIBuilder.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/ArtifactStoreURISHA256Builder.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreConfiguration.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ArtifactUriToReferenceConverter.java
This PR has three commits which addresses 3 particular issues:
1. README updates to reflect on current artifact store usage
2. Moving of scheme from the builder to the `ArtifactReferenceURI` class instead as that makes more sense
3. Updates the artifact store to rely more easily on default values instead of requiring `null` checks for the individual storage types
Signed-off-by: benjamin-j-powell <bjp@apple.com>
> fix(artifacts): Addresses a couple things regarding artifact store

- kork-crypto/kork-crypto.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
bouncycastle <1.74 versions suffer from [CVE-2023-33201](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-33201) 
Also bouncycastle module names changed from *-jdk15on to *-jdk18on from 1.71 version.
Through this PR(and subsequent gate and clouddriver PRs), though not all modules from all spinnaker services get to use bouncycastle >1.74, it is done wherever possible.
|google-cloud-secretmanager| bouncycastle dependency|
|--------------------------------------|------------------------------------|
|2.1.7                                     | 1.67                                    |
|2.3.10                                   |  no bouncycastle dependency  |
|com.oracle.oci.sdk:oci-java-sdk-bom | bouncycastle dependency|
|--------------------------------------|------------------------- …
> chore(dependencies): upgrade bouncycastle from 1.70 to 1.77

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpExceptionTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofit2ErrorHandleTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandlerTest.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerExceptionTest.java
This PR adds the HTTP request method as an instance variable to `SpinnakerServerException`. The value is retrieved from the constructor params except in the case that the exception is created from a `RetrofitError` where the HTTP method is not available and thus set to `null` in the exception. There are also some test updates included to make sure the getter works as expected for server, HTTP, and network exceptions.
> feat(retrofit): Make HTTP method available in SpinnakerServerException

- spinnaker-dependencies/spinnaker-dependencies.gradle
[version 2.15.15 of the spring boot bom](https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.5.15/spring-boot-dependencies-2.5.15.pom) specifies 3.14.16, so that's what we were getting even though we specified 3.13.6.
before:
```
org.jooq:jooq:3.13.6 -> 3.14.16 (c)
```
after
```
org.jooq:jooq -> 3.14.16
```
> chore(dependencies): unpin jooq since the spring boot bom specifies it

- spinnaker-dependencies/spinnaker-dependencies.gradle
Here are snippets from `$ ./gradlew orca-web:dependencies`
before:
```
|    |    \--- com.hubspot.jinjava:jinjava:2.5.2
|    |         +--- org.slf4j:slf4j-api:1.7.21 -> 1.7.36
|    |         +--- com.google.guava:guava:22.0 -> 30.0-jre
|    |         |    +--- com.google.guava:failureaccess:1.0.1
|    |         |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |         |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |         |    +--- org.checkerframework:checker-qual:3.5.0 -> 3.19.0
|    |         |    +--- com.google.errorprone:error_prone_annotations:2.3.4 -> 2.10.0
|    |         |    \--- com.google.j2objc:j2objc-annotations:1.3
|    |         +--- org.javassist:javassist:3.24.1-GA
|    |         +--- org.jsoup:jsoup:1.10.3
|    | …
```
> chore(deps): use version 2.7.1 of jinjava

- kork-core/kork-core.gradle
- kork-core/src/main/java/com/netflix/spinnaker/kork/resilience4j/Resilience4jHelper.java
- kork-core/src/test/java/com/netflix/spinnaker/kork/resilience4j/Resilience4jHelperTest.java
to help configure logging for RetryRegistry objects
Originally from [clouddriver](https://github.com/spinnaker/clouddriver/blob/3f31190d40419218fd1d31ca78bb1661f1ef881a/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutor.java#L134-L193).
> feat(core): add Resilience4jHelper

- spinnaker-dependencies/spinnaker-dependencies.gradle
to remove vulnerability CVE-2022-31159 that version 1.12.176 is subject to
> chore(dependencies): use version 1.12.261 of the aws sdk

- spinnaker-dependencies/spinnaker-dependencies.gradle
to resolve sonatype-2023-4380 / https://github.com/advisories/GHSA-xpw8-rcwv-8f8p
Before this, spring boot 2.5.15 brought in version 4.1.92.Final of netty.  Note that one of the aws sdk v2 dependencies was expecting 4.1.86.Final:
```
|    \--- software.amazon.awssdk:netty-nio-client:2.19.0
|         +--- software.amazon.awssdk:annotations:2.19.0
|         +--- software.amazon.awssdk:http-client-spi:2.19.0 (*)
|         +--- software.amazon.awssdk:utils:2.19.0 (*)
|         +--- software.amazon.awssdk:metrics-spi:2.19.0 (*)
|         +--- io.netty:netty-codec-http:4.1.86.Final -> 4.1.92.Final
|         |    +--- io.netty:netty-common:4.1.92.Final
|         |    +--- io.netty:netty-buffer:4.1.92.Final
|         |    |    \--- io.netty:netty-common:4.1.92.Final
|         |    +--- …
```
> chore(dependencies): pin io.netty:netty-bom to 4.1.100.Final

- spinnaker-dependencies/spinnaker-dependencies.gradle
to resolve https://github.com/advisories/GHSA-jgvc-jfgh-rjvv
No change in dependencies in kork. `$ ./gradlew clouddriver-kubernetes:dependencies` and `./gradlew orca-clouddriver:dependencies` change as follows.
before:
```
+--- io.kubernetes:client-java -> 11.0.4
|    \--- org.bitbucket.b_c:jose4j:0.7.3
|         \--- org.slf4j:slf4j-api:1.7.21 -> 1.7.36
```
after:
```
+--- io.kubernetes:client-java -> 11.0.4
|    \--- org.bitbucket.b_c:jose4j:0.7.3 -> 0.9.3
|         \--- org.slf4j:slf4j-api:1.7.21 -> 1.7.36
```
Note that https://github.com/spinnaker/clouddriver/pull/6133 teaches clouddriver to use version 13.0.2 of io.kubernetes.client-java-api-fluent. It's easy enough to get version 13.0.2 of io.kubernetes.client-java as well.  Unfortunately, that only brings the dependency on …
> chore(dependencies): pin org.bitbucket.b_c:jose4j to version 0.9.3

- spinnaker-dependencies/spinnaker-dependencies.gradle
to resolve CVE-2020-8908 and CVE-2023-2976 and to stay up to date.
> chore(dependencies): use version 33.0.0 of com.google.guava:guava

- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreStorerTest.java
to verify exact matches and use of regexes in both the "allow list" and "deny list" cases.
> test(artifacts): extend testing of applicationsRegex

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreStorer.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreStorerTest.java
This commit addresses a bug where storing SpEL can cause major issues down the chain, e.g. expected artifacts.
The easiest solution is to simply not store the artifact, but improvements could be made to evaluate the SpEL, if it makes sense to do
> fix(artifacts): Do not store non-base64 artifacts

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStore.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStorerTest.java
Manual backport of https://github.com/spinnaker/kork/pull/1164
> fix(s3Artifacts): Fixes where artifacts are SPeL vs. base64 direct. 

- spinnaker-dependencies/spinnaker-dependencies.gradle
to resolve CVE-2023-51775.
No change to dependencies in kork.  `$ ./gradlew clouddriver-kubernetes:dependencies` and `./gradlew orca-clouddriver:dependencies` change as follows:
before:
```
+--- io.kubernetes:client-java -> 11.0.4
|    \--- org.bitbucket.b_c:jose4j:0.7.3 -> 0.9.3
|         \--- org.slf4j:slf4j-api:1.7.21 -> 1.7.32
```
after:
```
+--- io.kubernetes:client-java -> 11.0.4
|    \--- org.bitbucket.b_c:jose4j:0.7.3 -> 0.9.4
|         \--- org.slf4j:slf4j-api:1.7.36 -> 1.7.32
```
> chore(dependencies): use version 0.9.4 of org.bitbucket.b_c:jose4j

- spinnaker-dependencies/spinnaker-dependencies.gradle
to resolve CVE-2023-6378 and CVE-2023-6481.  See See https://logback.qos.ch/news.html#1.3.12 and https://logback.qos.ch/news.html#1.2.13.
before:
```
|    |    |    +--- ch.qos.logback:logback-classic:1.2.12
|    |    |    |    +--- ch.qos.logback:logback-core:1.2.12
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
```
after:
```
|    |    |    +--- ch.qos.logback:logback-classic:1.2.12 -> 1.2.13
|    |    |    |    +--- ch.qos.logback:logback-core:1.2.13
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
```
> chore(dependencies): use version 1.2.13 of logback

- spinnaker-dependencies/spinnaker-dependencies.gradle
to resolve CVE-2023-51074.
before:
```
+--- com.jayway.jsonpath:json-path:2.5.0
|    +--- net.minidev:json-smart:2.3 -> 2.4.10
|    |    \--- net.minidev:accessors-smart:2.4.9
|    |         \--- org.ow2.asm:asm:9.3
|    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36
```
after:
```
+--- com.jayway.jsonpath:json-path:2.5.0 -> 2.9.0
|    +--- net.minidev:json-smart:2.5.0
|    |    \--- net.minidev:accessors-smart:2.5.0
|    |         \--- org.ow2.asm:asm:9.3
|    \--- org.slf4j:slf4j-api:2.0.11 -> 1.7.36
```
> chore(dependencies): use version 2.9.0 of com.jayway.jsonpath:json-path

- kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringPluginStatusProviderTest.kt
- kork-swagger/kork-swagger.gradle
- kork-swagger/src/main/java/com/netflix/spinnaker/config/SpringfoxHandlerProviderBeanPostProcessor.java
- kork-swagger/src/main/resources/META-INF/spring.factories
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/DefaultTomcatConnectorCustomizer.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/TomcatConfiguration.java
- kork-tomcat/src/main/java/com/netflix/spinnaker/kork/tomcat/TomcatConfigurationProperties.java
- spinnaker-dependencies/spinnaker-dependencies.gradle
Spring cloud release 2021.0.x is compatible with spring boot 2.6.x. 
https://github.com/spring-cloud/spring-cloud-release/wiki/Supported-Versions#supported-releases
While upgrading spring boot 2.6.15 and spring cloud 2021.0.8, encounter below errors in kork-plugins and kork-tomcat modules:
```
> Task :kork-plugins:compileTestKotlin FAILED
e: /kork/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringPluginStatusProviderTest.kt: (50, 11): Type mismatch: inferred type is Array<???> but SpringApplication! was expected
e: /kork/kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringPluginStatusProviderTest.kt: (51, 11): Type mismatch: inferred type is ConfigurableEnvironment but Array<(out) String!>! was expected
e: …
```
> chore(dependency): upgrade spring boot from 2.5.15 to 2.6.15 and spring cloud from 2020.0.x to 2021.0.x

- spinnaker-dependencies/spinnaker-dependencies.gradle
Spring boot 2.6.15 brings in snakeyaml 1.29, which [fails to parse yaml](https://github.com/spring-projects/spring-boot/issues/30159#issuecomment-1125969155) (including some k8s manifests).  It's safe to upgrade beyond 1.29 according to [this](https://github.com/spring-projects/spring-boot/issues/32228#issue-136185850.0). However, snakeyaml 1.32 has a [feature](https://bitbucket.org/snakeyaml/snakeyaml/issues/547/restrict-the-size-of-incoming-data) to restrict the size of incoming data to 3 MB by default ([PR](https://bitbucket.org/snakeyaml/snakeyaml/pull-requests/22)), and spring boot versions <= 3.0.7 are not equipped to modify this.  So, use 1.31 in order to avoid the limit till upgrade >= 3.0.7 and to resolve CVE-2022-25857 and CVE-2022-38749.
before:
```
|    |    +--- …
```
> chore(dependencies): upgrade snakeyaml from 1.29 to 1.31

- gradle.properties
- gradle/kotlin-test.gradle
- gradle/kotlin.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
Upgrade kotlin from 1.5.32 to 1.6.21, in order to sync with spring boot 2.6.15. Unpinning kotlinx-coroutines, that brings version 1.5.2 as transitive dependency of spring boot 2.6.15. So, effectively no change in kotlinx-coroutines version. 
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.6.15/spring-boot-dependencies-2.6.15.pom
> chore(dependency): upgrade kotlin to 1.6.21 and unpin kotlinx-coroutines

- kork-expressions/kork-expressions.gradle
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/functions/ArtifactStoreFunctions.java
- kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
Introduces a simple SpEL function that returns the reference that was stored in the artifact store
```
${ #fetchReference(#stage('Bake Manifest').context.artifacts[0].reference) }
```
> feature(expressions): fetchReference SpEL function

- kork-security/src/main/java/com/netflix/spinnaker/security/UserPermissionEvaluator.java
so S3ArtifactStoreGetter can call a username-based hasPermission method. FiatPermissionEvaluator has this method, but using FiatPermissionEvaluator in kork would create a circular dependency.
The plan is:
- publish a kork jar with UserPermissionEvaluator,
- consume it in fiat and change FiatPermissionEvaluator to implement UserPermissionEvaluator instead of PermissionEvaluator
- publish a fiat jar and consume it everywhere
- change S3ArtifactStoreGetter to use UserPermissionEvaluator to fix the bug that https://github.com/spinnaker/kork/pull/1178 demonstrates
- publish yet another kork jar and consume it everywhere to fix use of fetchReference in Evaluate Variables stages
> feat(security): add UserPermissionEvaluator

- gradle.properties
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreConfiguration.java
- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreGetter.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreGetterTest.java
instead of SecurityContextHolder.getContext() which might be null.  Previously hasAuthorization would only user userId for logging.  Now it's used for authentication too.  This fixes the bug that https://github.com/spinnaker/kork/pull/1178 demonstrates.
depends on https://github.com/spinnaker/fiat/pull/1155
> fix(artifacts): authenticate against AuthenticatedRequest.getSpinnakerUser in S3ArtifactStoreGetter

- spinnaker-dependencies/spinnaker-dependencies.gradle
> chore(dependencies): use version 1.19.8 of testcontainers

- spinnaker-dependencies/spinnaker-dependencies.gradle
postgresql not supporting `afterColumn` feature and various issues with liquibase versions resulted in delayed liquibase upgrade from 3.10.3 to 4.24.0 in spinnaker 1.33.0 release. Here is the PR- https://github.com/spinnaker/kork/pull/1117
But even after the upgrade, migrating databases faced [checksum issues](https://github.com/spinnaker/spinnaker/issues/6941).
In order to fix this issue two changes are needed.
1. Upgrade liquibase further to 4.27.0 (through this PR)
2. Add validCheckSum tags to those changeSets in clouddriver and Orca which are failing with CheckSum errors.
- https://github.com/spinnaker/clouddriver/pull/6217
- https://github.com/spinnaker/orca/pull/4727
Kork 7.201.0 upgraded liquibase to 4.24.0. And this is causing checkSum error for spinnaker upgrades. So all the …
> chore(dependencies): upgrade liquibase to 4.27.0

- spinnaker-dependencies/spinnaker-dependencies.gradle
This reverts commit 4ff407e8c4486e8d51dacbcdf24e2057482f74fa.
Turns out that we don't need liquibase 4.27.0 to fix migration issues with postgres. https://github.com/spinnaker/clouddriver/pull/6217 fixes the migration with 4.24.0.
> Revert "chore(dependencies): upgrade liquibase to 4.27.0 (#1184)"

- kork-actuator/src/main/resources/META-INF/spring.factories
- kork-actuator/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-aws/src/main/resources/META-INF/spring.factories
- kork-aws/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-cloud-config-server/src/main/resources/META-INF/spring.factories
- kork-cloud-config-server/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-core/src/main/resources/META-INF/spring.factories
- kork-core/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-credentials/src/main/resources/META-INF/spring.factories
- kork-credentials/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-eureka/src/main/resources/META-INF/spring.factories
- kork-eureka/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-retrofit/src/main/resources/META-INF/spring.factories
- kork-retrofit/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-retrofit2/src/main/resources/META-INF/spring.factories
- kork-retrofit2/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-secrets/src/main/resources/META-INF/spring.factories
- kork-secrets/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-sql-test/kork-sql-test.gradle
- kork-sql/kork-sql.gradle
- kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt
- kork-swagger/src/main/resources/META-INF/spring.factories
- kork-swagger/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- kork-tomcat/src/main/resources/META-INF/spring.factories
- kork-tomcat/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- spinnaker-dependencies/spinnaker-dependencies.gradle
Unpin netty-bom to align with spring boot during upgrade to spring boot 2.7.x 
With spring boot 2.7.18, separate dependency management for netty-tcnative has been removed in favor of the dependency management provided by Netty’s bom. 
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#separate-dependency-management-for-netty-tcnative-removed
Exclude `DataSourcePoolMetricsAutoConfiguration` class from auto-configuration to resolve circular reference issue during upgrade to spring boot 2.7.x. 
While upgrading spring boot 2.7.18, encounter below error during test compilation of kork-sql module:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
The dependencies of some of the beans in the application context …
```
> chore(dependency): upgrade spring boot from 2.6.15 to 2.7.18

- spinnaker-dependencies/spinnaker-dependencies.gradle
In this issue https://github.com/spinnaker/spinnaker/issues/6958
You can see that rev20201102 1.30.10 isn't forced successfully.
The reason is the version com.google.apis:google-api-services-compute:alpha-rev20200526-1.30.9 is leaked from other places
> chore(Google-api-services-compute-beta): upgrading to rev20201102 1.30.10 

- spinnaker-dependencies/spinnaker-dependencies.gradle
`com.nimbusds:nimbus-jose-jwt` dependency is pinned to version 7.9, that is old version and shows [CVE-2023-52428](https://nvd.nist.gov/vuln/detail/CVE-2023-52428) as direct vulnerability. In order to fix this vulnerability upgrading and pinning nimbus-jose to 9.37.2.
The components using nimbus-jose as direct or transitive dependency are gate, clouddriver, front50 and halyard.
> chore(dependency): upgrade nimbus-jose to fix CVE-2023-52428

- kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/config/ExpressionProperties.java
Spring Expression Lanuage (SpEL) has a default limit of 10,000 characters. Springframework provides the feature to configure the limit. This feature allows to configure the limit of characters for SpEL expressions.
Approach:
In order to use an expression with characters more than the given default limit, require to follow either of the below approaches:
1. For Springframework >=5.3.28 and <6.1.3, by setting `maximumExpressionLength` field while instantiating the custom `SpelParserConfiguration` class. 
https://github.com/spring-projects/spring-framework/issues/30380 
https://github.com/spring-projects/spring-framework/issues/30446
2. For Springframework >=6.1.3, by setting a JVM system property or Spring property named `spring.context.expression.maxLength` to the maximum expression length …
> feat(SpEL): implement to configure the limit of characters for SpEL expressions

- build.gradle
- kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
that uses a non-public constructor/method, and so requires special treatment under java 17.
> test(expressions): demonstrate behavior of SpEL expression evaluation

- spinnaker-dependencies/spinnaker-dependencies.gradle
As part of upgrading the spock framework from 2.0-groovy-3.0 to 2.2-groovy-3.0, it is required to update junit5 to 5.9.0. 
https://spockframework.org/spock/docs/2.3/release_notes.html#_2_2_2022_08_31 
Spring boot 2.7.18 brings junit-jupiter 5.8.2.
https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.18/spring-boot-dependencies-2.7.18.pom 
So, junit-bom version to be pinned to 5.9.0, untill spring boot >= 3.0.0.
> chore(dependency): upgrade junit-jupiter to 5.9.0

- kork-moniker/src/main/java/com/netflix/spinnaker/moniker/Namer.java
- kork-moniker/src/main/java/com/netflix/spinnaker/orchestration/OperationDescription.java
and add an overloaded applyMoniker method with the description parameter.
Added a new overloaded applyMoniker method to the Namer interface with an OperationDescription parameter. The new method defaults to calling the existing applyMoniker method without the description. Moved the OperationDescription from clouddriver's com.netflix.spinnaker.clouddriver.orchestration to kork-moniker's com.netflix.spinnaker.orchestration.
First used in https://github.com/spinnaker/kork/pull/1199
> feat(moniker): Move OperationDescription from clouddriver to kork 

- kork-aws/kork-aws.gradle
- kork-core-tck/kork-core-tck.gradle
- kork-web/kork-web.gradle
- spinnaker-dependencies/spinnaker-dependencies.gradle
As part of the effort to upgrade groovy from 3.x to 4.x, upgrading to 4.0.15 version that is supported by spring boot 3.0.13 (expected as next upgrade). Replacing the coordinates from `org.codehaus.groovy` to `org.apache.groovy` supported by groovy 4.x and above versions. Upgrading spockframework from 2.2-groovy-3.0 to 2.2-groovy-4.0 to support groovy 4.
Spring boot 2.7.18 brings rest-assured 4.5.1 as its transitive dependency, that uses groovy 3. In order to resolve the groovy version to 4, pinning `io.rest-assured` to 5.2.1 till spring boot upgrade >=3.0.13
> chore(dependency): upgrade groovy to 4.0.15

- spinnaker-dependencies/spinnaker-dependencies.gradle
`rest-assured-commons` dependency is used by clouddriver-artifacts, clouddriver-aws, clouddriver-kubernetes and clouddriver-ecs modules. Since this dependency is not pinned in kork along with other rest-assured dependencies, it is leaking groovy [3.0.9](https://repo1.maven.org/maven2/io/rest-assured/rest-assured-common/4.5.1/rest-assured-common-4.5.1.pom).
```
$ ./gradlew clouddriver-kubernetes:dI --dependency codehaus.groovy:groovy --configuration integrationCompileClasspath
> Task :clouddriver-kubernetes:dependencyInsight
org.codehaus.groovy:groovy:3.0.19
Variant compile:
| Attribute Name                     | Provided | Requested         |
|------------------------------------|----------|-------------------|
| org.gradle.status                  | release  |                   |
| …
```
> fix(dependency): pin rest-assured-common to prevent old groovy version leak during upgrade of groovy 4.x

- kork-secrets-gcp/src/main/java/com/netflix/spinnaker/kork/secrets/engines/GcsSecretEngine.java
- kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/ConfigParams.java
- spinnaker-dependencies/spinnaker-dependencies.gradle
Support `resourceManagerTags` in GCE. See: https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates/insert
These changes upgrade the version of `google-api-services-compute` and `google-api-client`.
Issue related: https://github.com/spinnaker/spinnaker/issues/6931
> feat(gce): support resourceManagerTags in instance template

- kork-artifacts/src/main/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreStorer.java
- kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/artifactstore/s3/S3ArtifactStoreStorerTest.java
Front50 applications in many situations (especially when created via templates or pipeline as code automation) have a mix of Upper/Lower case names.  Deck is always presenting the application names in lower-case so the end-user needs to query front50 directly to find out how the application name is actually stored.  
This PR is making the pattern matching for the artifactStore enabling per application as case-insensitive to avoid a situation when the user expects the artifact-store to be enabled in an application and finds out it is stored in different case in front50.
> fix(artifactStore): Make applicationsRegex pattern matching case-insensitive

- spinnaker-dependencies/spinnaker-dependencies.gradle
Upgrade google api client to 1.33.0 to allow new features in GCE.
All the google api services were updated to the compatible version with 1.33.0
> feat(gce): upgrade google-api-client to 1.33.0

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/RetrofitServiceFactory.java
This commit adds the SpinnakerRetrofitErrorHandler to service factories which allows for clients that rely on service factories to properly have RetrofitErrors be converted to some Spinnaker*Exception.
This PR needs to remain as a draft until gate has fully changed its exception handling to support non-RetrofitError exceptions
> feature(retrofit): Add exception handler to service factory

- spinnaker-dependencies/spinnaker-dependencies.gradle
PR https://github.com/spinnaker/kork/pull/1198 removed restassured from the dependencies but it is needed in Clouddriver and Kayenta
> fix(deps): Reverting removal of restassured

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/RetrofitServiceFactory.java
- kork-retrofit2/src/main/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactory.java
- kork-web/src/main/java/com/netflix/spinnaker/config/DefaultServiceClientProvider.java
- kork-web/src/main/java/com/netflix/spinnaker/config/okhttp3/OkHttpClientProvider.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/client/ServiceClientFactory.java
- kork-web/src/main/java/com/netflix/spinnaker/kork/client/ServiceClientProvider.java
- kork-web/src/test/java/com/netflix/spinnaker/config/okhttp3/OkHttpClientProviderTest.java
As an alternate to using `OkHttp3ClientConfiguration` for creating an OkHttpClient, `OkHttpClientProvider` was created through
https://github.com/spinnaker/kork/pull/639. But there are many existing retrofit clients that are passing Interceptor(s) which is not supported by `OkHttpClientProvider`.  This PR allows `OkHttpClientProvider` to accept `okhttp3.Interceptor` list. 
As we are slowly moving to retrofit2(rosco completed, [echo](https://github.com/spinnaker/echo/pull/1466) under review), the real consumer of OkHttpClientProvider will be `Retrofit2ServiceFactory`(as opposed to `RetrofitServiceFactory`) but since it's an implementation of `ServiceClientFactory`,  I had to add a method that takes `List<Interceptor>` which is specific to `Retrofit2ServiceFactory` and hence the method has …
> feat(retrofit2): Improvise OkHttpClientProvider to accept interceptors

- kork-retrofit2/kork-retrofit2.gradle
- kork-retrofit2/src/test/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactoryTest.java
Adds test coverage to the following classes by creating a retrofit2 client: Retrofit2ServiceFactory, DefaultServiceClientProvider, OkHttpClientProvider.
> test(web): add Retrofit2ServiceFactoryTest to test the creation of retrofit2 client using Retrofit2ServiceFactory

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/Retrofit2SyncCall.java
- kork-retrofit2/src/test/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactoryTest.java
Existing method `Retrofit2SyncCall.execute()` returns response body when an api is invoked by a retrofit2 client and hence there is no way to capture headers when needed. So added a new method that returns `retrofit2.Response` object through which headers can be accessed.
> feat(retrofit2): add a method that returns Response object when retrofit2 client invokes an api

- .github/workflows/release.yml
The default HEAD reference is included in the remote branch list when `git branch -r --contains refs/tags/v7.249.0` is run. 
Refer: https://github.com/spinnaker/kork/actions/runs/12996151157/job/36284220771.
```
Run BRANCHES=$(git branch -r --contains refs/tags/v7.249.0) 
BRANCHES is '  origin/HEAD -> origin/master
origin/master'
NUM_BRANCHES is '2'
exactly one branch required to release kork, but there are 2 (  origin/HEAD -> origin/master
origin/master)
Error: Process completed with exit code 1.
```
> fix(build): fix a build error

- kork-retrofit2/kork-retrofit2.gradle
- kork-retrofit2/src/main/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactory.java
- kork-retrofit2/src/test/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactoryTest.java
- Retrofit2 client defined in Retrofit2ServiceFactory doesn't have CallAdapterFactory set. 
- This PR sets `ErrorHandlingExecutorCallAdapterFactory` to the retrofit2 client which is responsible for classifying the exceptions into `SpinnakerHttpException`, `SpinnakerNetworkException` or `SpinnakerServerException`.
> feat(retrofit2): add ErrorHandlingExecutorCallAdapterFactory to the retrofit2 client

- kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/ErrorHandlingExecutorCallAdapterFactory.java
- kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofit2ErrorHandleTest.java
- kork-retrofit2/src/test/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactoryTest.java
At present the SpinnakerConversionException.getMessage() gives only the static text : `Failed to process response body`. With this PR, the message will have more details on the actual conversion error.
Ex: `Failed to process response body: Unrecognized token 'this': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`
> refactor(retrofit2): add more details to the SpinnakerConversionException's message

- kork-retrofit/src/test/kotlin/com/netflix/spinnaker/kork/retrofit/RetrofitServiceProviderTest.kt
- kork-retrofit2/src/test/java/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceFactoryTest.java
- kork-retrofit2/src/test/kotlin/com/netflix/spinnaker/kork/retrofit/Retrofit2ServiceProviderTest.kt
- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttp3ClientConfiguration.groovy
- kork-web/src/main/groovy/com/netflix/spinnaker/okhttp/OkHttpClientConfigurationProperties.groovy
- kork-web/src/main/java/com/netflix/spinnaker/config/OkHttpClientComponents.java
- kork-web/src/main/java/com/netflix/spinnaker/config/okhttp3/OkHttpClientProvider.java
- kork-web/src/main/java/com/netflix/spinnaker/okhttp/Retrofit2EncodeCorrectionInterceptor.java
- kork-web/src/test/java/com/netflix/spinnaker/config/OkHttp3ClientConfigurationTest.java
- kork-web/src/test/java/com/netflix/spinnaker/config/OkHttpClientComponentsTest.java
- kork-web/src/test/java/com/netflix/spinnaker/config/okhttp3/OkHttpClientProviderTest.java
- kork-web/src/test/java/com/netflix/spinnaker/okhttp/Retrofit2EncodeCorrectionInterceptorTest.java
This PR addresses the issue - https://github.com/spinnaker/spinnaker/issues/7021
- Retrofit2 encoding is different from that of retrofit1, so if the path parameter or query parameter have special characters the APIs are rejecting the request with 400. An issue has been raised with [retrofit team](https://github.com/square/retrofit/issues/4312) but the solution from them is not in the near future.
- This PR addresses all the encoding issues caused by retrofit2 by first decoding the partially encoded path/query parameters and then encoding it properly in a newly created interceptor - `Retrofit2EncodeCorrectionInterceptor`.  
- Added a test class `Retrofit2EncodeCorrectionInterceptorTest` to demonstrate the issue and the fix.
- The default behaviour of a retrofit2 client created using any of …
> fix(retrofit2): fix retrofit2 partial encoding issue

- kork-web/kork-web.gradle
- kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttp3ClientConfiguration.groovy
- kork-web/src/test/java/com/netflix/spinnaker/okhttp/Retrofit1ImpactTest.java
- While creating retrofit2 specific Interceptor `Retrofit2EncodeCorrectionInterceptor` as part of https://github.com/spinnaker/kork/pull/1228, it got added to the OkHttpClient meant for retrofit1. This PR fixes this issue.
> fix(web): remove Retrofit2EncodeCorrectionInterceptor from OkHttpClient client meant for retrofit1 client
