spinnaker/kork

kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttpClientConfiguration.groovy

prevent OkHttp from retrying HTTPS POSTs when they time out

---

gradle/buildViaTravis.sh

Revert "debug travis error"

---

kork-security/kork-security.gradle
kork-security/src/main/groovy/com/netflix/spinnaker/security/User.groovy

@cfieber or @ajordens PTAL
@jtk54 FYI

Makes User implement UserDetails to work with Spring Security

---

kork-security/src/main/groovy/com/netflix/spinnaker/security/User.groovy

Fixes an issue @ajordens found while visiting MSFT.
@jtk54 FYI

Makes User's username nonnull

---

kork-security/src/main/groovy/com/netflix/spinnaker/security/User.groovy
kork-security/src/test/groovy/com/netflix/spinnaker/security/UserSpec.groovy

@ajordens @cfieber @jtk54 PTAL
I'll merge this once the other dependent CLs have also been LGTM'ed

Makes user mutable with the option to make immutable

---

build.gradle

boot and friends to 1.2.8.RELEASE

update to latest dependencies

---

kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MonitoredResourceBuilder.java
kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/MonitoredResourceBuilderTest.java

Dont need project_id in stackdriver managed resource.

---

kork-web/src/main/groovy/org/springframework/boot/actuate/endpoint/ResolvedEnvironmentEndpoint.groovy

Adds exception handling for unresolvable properties in /resolvedEnv endpoint

---

kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/ConfigParams.java
kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MetricDescriptorCache.java
kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/MetricDescriptorCacheTest.java
kork-stackdriver/src/test/java/com/netflix/spectator/stackdriver/StackdriverWriterTest.java

@ttomsu 
Feedback from previous PR that I submitted before seeing your comments.

Cleanup tests

---

build.gradle
kork-core/src/main/java/com/netflix/spinnaker/kork/metrics/SpectatorConfiguration.java
kork-swagger/kork-swagger.gradle
kork-web/kork-web.gradle
kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingJSSESocketFactory.java

Revert "Upgrade to Spring Boot 1.4"

---

kork-stackdriver/kork-stackdriver.gradle

Remove unused deps from stackdriver module

---

kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/StackdriverWriter.java

Dont log stackdriver calls; too much noise.

---

kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/ConfigParams.java

Set Stackdriver user agent.

---

kork-core/kork-core.gradle
kork-core/src/main/java/com/netflix/spinnaker/kork/metrics/SpectatorConfiguration.java
kork-stackdriver/src/main/java/com/netflix/spinnaker/config/StackdriverConfig.java

Decoupled SpectatorWebEndpoints from Stackdriver

---

kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MetricDescriptorCache.java

Fixed NPE in stackdriver

---

build.gradle

updates jackson and spectator versions

chore(dependencies): upgrade to spinnaker-dependencies 0.84.0

---

kork-stackdriver/src/main/java/com/netflix/spectator/stackdriver/MonitoredResourceBuilder.java

fix(stackdriver): Permit cross project monitoring

---

build.gradle

update to latest spinnaker-dependencies

---

kork-web/src/main/groovy/com/netflix/spinnaker/config/ErrorConfiguration.groovy
kork-web/src/main/java/com/netflix/spinnaker/kork/web/controllers/GenericErrorController.java
kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlers.java
kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/HasAdditionalAttributes.java
kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/NotFoundException.java
kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlersSpec.groovy

Ported from spinnaker/gate#423

feat(web): Generic exception handling

---

kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlers.java

This exception handler will propagate the underlying retrofit error
status rather than an HTTP 500 as is the current behavior.

feat(web): Add a generic RetrofitError exception handler

---

kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy

feat(web): add interceptor to propagate a request traceid (via X-SPINNAKER-REQUEST-ID header) to be set by gate to downstreams and logs

feat(web): Add request id to AuthenticatedRequest

---

build.gradle
kork-dynomite/kork-dynomite.gradle
kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientDelegate.java
kork-jedis/kork-jedis.gradle
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientDelegate.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientDelegate.java
settings.gradle

This is in preparation for adding dyno as an option to Orca & Fiat.
@cfieber PTAL
Depends on https://github.com/spinnaker/spinnaker-dependencies/pull/119

feat(jedis): Adds functional interface delegate between Jedis and Dynomite

---

kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy

Propagate execution id's once initially added to MDC by Orca

feat(web): propagate executionId if on MDC

---

kork-exceptions/kork-exceptions.gradle
kork-exceptions/src/main/java/com/netflix/spinnaker/kork/core/RetrySupport.java
kork-exceptions/src/test/groovy/com/netflix/spinnaker/kork/core/RetrySupportSpec.groovy

This was extracted from `orca`.

feat(core): General purpose retry support

---

kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientConfiguration.java
kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientDelegateFactory.java
kork-dynomite/src/main/java/com/netflix/spinnaker/kork/dynomite/DynomiteClientFactory.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/RedisClientConfiguration.java

* A couple NPEs when app configs weren't setting up any clients The New Way(tm)
* Jumping through some hoops to get around Spring's config resolver shortcomings when config is too deep (connection pool configuration for dynomite!)

fix(redis): Fixing dynomite connpool configuration wiring

---

kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlers.java

fixes https://github.com/spinnaker/spinnaker/issues/2518

fix(core): Return 405 status instead of 500 when http method not supported

---

kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientConfiguration.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisClientDelegateFactory.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/JedisPoolFactory.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedis.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisException.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisPool.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/TelemetryHelper.java

Instruments:
* The latency for every command
* The payload size for (most) writes
* The error rate for individual commands
* The combined error rate for the client

feat(redis): Instrumented Jedis client & Pool

---

kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedis.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedPipeline.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/TelemetryHelper.java

More dataz, more improved.
* Pipelines are now instrumented (tagged either "pipelined=true" or "false"
* Now with percentile timers and distribution summaries
* Removed error metrics, moved to a general invocation metric with success flag
* Refactored the instrumentation logic so it's easier to make sweeping changes to instrumentation logic

feat(redis): Instrumented Redis Pipeline

---

kork-core/src/main/java/com/netflix/spinnaker/kork/lock/RefreshableLockManager.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java
kork-jedis/src/test/groovy/com/netflix/spinnaker/kork/jedis/locking/RedisLockManagerSpec.groovy

- Collections.singletonList(..) causes a ClassCastException when using the dyno redis driver
- Support retrying heartbeat on failure

fix(locking): Use Arrays.asList(..) over Collections.singletonList(..)

---

kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttpClientConfiguration.groovy

- added comment to state alternative: `OkHttp3ClientConfiguration`

chore(retrofit): Add deprecation comment for OkHttpClientConfiguration

---

kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java

- adding lock name as a tag for how long a lock is kept by a client

fix(locking): Prefer using a tag for duration metric

---

kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java

refactor(locking): Renaming metrics names to be more generic

---

kork-web/src/main/java/com/netflix/spinnaker/kork/web/interceptors/MetricsInterceptor.java

Redundancy is good except in metric names.

fix(web): *Percentile* distribution summary metric

---

kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java
kork-core/src/main/java/com/netflix/spinnaker/kork/lock/RefreshableLockManager.java
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java
kork-jedis/src/test/groovy/com/netflix/spinnaker/kork/jedis/locking/RedisLockManagerSpec.groovy

- this will also prevent the heartbeat from increasing the version
- allows for the same owner to acquire the lock

feat(locking): Allow to override version

---

kork-web/src/main/groovy/com/netflix/spinnaker/filters/AuthenticatedRequestFilter.groovy

Handles a situation where a certificate used for service to service
communication was created with an RFC822 email address.

fix(web): Avoid extracting `spinnakerUser` from cert if available in header

---

kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisPool.java

Simplifying the instrumented pool. Now lazily gets a reference to the internal pool, and also no-ops on init and close operations, since those should be managed by the delegate anyhow.

fix(jedis): Fix NPE on delegate internal pool

---

build.gradle

chore(dependencies): Bumped dependencies to 1.0.16 for spectator update.

---

kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java

Adding a log statement. My redis configuration was wrong, and it was _very_ hard to debug why nothing was running.

chore(logs): adding logging of exception

---

kork-test/kork-test.gradle
kork-test/src/main/java/com/netflix/spinnaker/kork/test/time/MutableClock.java

Pulling this class from [orca](https://github.com/spinnaker/orca/blob/7c4896117fdcd6930cadaa82bfdf5dcb8383f89b/orca-test/src/main/java/com/netflix/spinnaker/orca/time/MutableClock.java) to use for testing in other services.

feat(testing): mutable clock for testing

---

build.gradle
gradle/buildViaTravis.sh
gradle/init-publish.gradle
gradle/installViaTravis.sh

Do not merge with release candidate libraries - needs https://github.com/spinnaker/spinnaker-gradle-project/pull/47 to be released.
Supercedes https://github.com/spinnaker/kork/pull/157
Ref: https://github.com/spinnaker/spinnaker/issues/2844

fix(builds): Pulls in unopinionated spinnaker-gradle-project plugin

---

build.gradle
gradle/init-publish.gradle

Fixes publishing of all modules

fix(builds): Bump gradle plugin version (again)

---

kork-telemetry/src/main/java/com/netflix/spinnaker/kork/telemetry/InstrumentedProxy.java
kork-telemetry/src/test/groovy/com/netflix/spinnaker/kork/telemetry/InstrumentedProxySpec.groovy

The change to use an instrumeted proxy for Jenkins calls is masking error codes received from the Jenkins server. This is because exceptions thrown in InvocationHandler.invoke are wrapped in the checked exception InvocationTargetException before being returned to the caller. This ultimately leads to downstream code receiving an UndeclaredThrowableException rather than the particular exception.

fix(telemetry): Unwrap InvocationTargetException

---

kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/JooqToSpringExceptionTransformer.kt

No need to do any SQL spring exception translations if there's no SQL exception!

fix(sql): Allow null SQLException translation

---

build.gradle

chore(deps): Bump dependencies to 1.10.0

---

kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/EncryptedSecret.java

Part of [spinnaker/spinnaker#3649](https://github.com/spinnaker/spinnaker/issues/3649)

feat(kork/secrets): isEncryptedSecret should handle null values

---

kork-core/src/main/java/com/netflix/spinnaker/kork/dynamicconfig/DynamicConfigService.java

Mostly for unit testing as I've reimplemented this in a few different spots now.

feat(config): add noop DynamicConfigService.

---

kork-secrets/src/main/java/com/netflix/spinnaker/config/secrets/SecretManager.java
kork-secrets/src/test/java/com/netflix/spinnaker/config/secrets/SecretManagerTest.java

Part of secrets management project: https://github.com/spinnaker/spinnaker/issues/3649
This caching was formerly in Halyard, but per @lwander's comment on [this PR](https://github.com/spinnaker/halyard/pull/1157), we're moving it into Kork.

feat(secrets): add secrets caching to SecretManager

---

kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionEvaluationSummary.java
kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionTransform.java

cc / @claymccoy.
Visibility levels necessary for Canal pipeline DSL.

chore(expressions): increase the visibility of expression eval methods

---

kork-web/src/main/groovy/com/netflix/spinnaker/config/ActuatorEndpointsConfiguration.java

chore(boot2): really change order of ActuatorEndpointsConfiguration

---

kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt

Enable scheduling so SQL health provider works

---

kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/telemetry/InstrumentedJedisPool.java

chore(jedis): make method public

---

kork-core-tck/kork-core-tck.gradle
kork-core-tck/src/main/groovy/com/netflix/spinnaker/kork/lock/BaseLockManagerSpec.groovy
kork-core/src/main/java/com/netflix/spinnaker/kork/lock/LockManager.java
kork-jedis/kork-jedis.gradle
kork-jedis/src/main/java/com/netflix/spinnaker/kork/jedis/lock/RedisLockManager.java
kork-jedis/src/test/groovy/com/netflix/spinnaker/kork/jedis/locking/RedisLockManagerSpec.groovy
settings.gradle

I didn't end up actually implementing a second version but I don't think this is a bad idea regardless.

Make lock manager test a reusable TCK

---

spinnaker-dependencies/spinnaker-dependencies.gradle

clouddriver is not happy with the latest version of jooq.

fix(deps): downgrade jooq, add deps for clouddriver

---

kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy

this fixes configuring SSL on any additional ports (only really applicable for gate)

fix(ssl): update SSL configuration for boot2

---

kork-web/src/main/java/com/netflix/spinnaker/kork/web/selector/ByLocationServiceSelector.java
kork-web/src/main/java/com/netflix/spinnaker/kork/web/selector/SelectableService.java
kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/selector/SelectableServiceSpec.groovy

- assists in finding a service by region/location

feat(serviceSelector): Added a byLocationServiceLocator

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties

This will do the bump, assuming you have a github.token defined in your ~/.gradle/gradle.properties:
```
./gradlew -PenablePublishing=true -Prelease.disableGitChecks=true -Prelease.useLastTag=true bumpDependencies
```
Will work on wiring it into some automation as a followup

feat(autobump): enable autobump plugin

---

kork-security/src/main/java/com/netflix/spinnaker/security/AuthenticatedRequest.java
kork-security/src/test/groovy/com/netflix/spinnaker/security/AuthenticatedRequestSpec.groovy

also, remove the side-effect of generating request id for now

fix(headers): fix mixed up request/execution_id headers

---

kork-web/kork-web.gradle
kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy
kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistEnabledDynamicConfigMonitor.java
kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingJSSESocketFactory.java
kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingSSLImplementation.java
kork-web/src/main/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingX509TrustManager.java
kork-web/src/test/groovy/com/netflix/spinnaker/tomcat/x509/BlacklistingX509TrustManagerSpec.groovy

adds metrics on checked/rejected requests
adds ability to disable via dynamic property service

feat(ssl/blacklist): ops improvements for SSL blacklist

---

kork-web/src/main/java/com/netflix/spinnaker/kork/web/selector/v2/SelectableService.java
kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/selector/v2/SelectableServiceSpec.groovy

- supports flexible selection of a service based on parameters
- allows per service visibility and access to config attributes

feat(selector): Adding v2 service selector

---

kork-web/src/main/java/com/netflix/spinnaker/kork/web/selector/v2/SelectableService.java

- s/private/public/ on  SelectedService

chore(v2Selector): Making SelectedService constructor public

---

kork-web/src/main/java/com/netflix/spinnaker/kork/web/selector/v2/SelectableService.java
kork-web/src/test/groovy/com/netflix/spinnaker/kork/web/selector/v2/SelectableServiceSpec.groovy

- Ensuring input params are AND'ed during comparison to be more exact
- Values within the same param are OR'ed

fix(v2Selector): Fixing base params to input params comparison

---

gradle.properties

this should stop autobumping kayenta

chore(build): latest spinnaker-gradle-project

---

kork-manageddelivery/src/main/java/com/netflix/spinnaker/kork/manageddelivery/model/Resource.java
kork-manageddelivery/src/main/java/com/netflix/spinnaker/kork/manageddelivery/model/ResourceEvent.java

Adding the basic keel resource structure (no type info, just lovely maps) to kork.

feat(keel): add basic resource

---

spinnaker-dependencies/spinnaker-dependencies.gradle

Pick up latest ECS task definition model

chore(aws): Bump aws dependencies

---

kork-plugins/kork-plugins.gradle
kork-plugins/src/main/java/com/netflix/spinnaker/kork/plugins/spring/PluginLoader.java
kork-plugins/src/main/java/com/netflix/spinnaker/kork/plugins/spring/SpinnakerApplication.java

Adding beta tag to signify plugins are a beta feature

chore(plugins): adding beta tag

---

spinnaker-dependencies/spinnaker-dependencies.gradle

See https://github.com/spinnaker/spinnaker/issues/4662#issuecomment-514793357
Fixes https://github.com/spinnaker/spinnaker/issues/4662

chore(dependencies): Upgrade springfox-swagger to 2.9.2

---

kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java

Apply Orca change from https://github.com/spinnaker/orca/commit/4a770d8152e180cfc05bf287a9cc028ae4a57180

chore(expressions): Remove noisy spel function registration log message

---

kork-manageddelivery/src/main/java/com/netflix/spinnaker/kork/manageddelivery/model/ResourceEvent.java

Forgot this wasn't kotlin. Oops!

fix(keel): add @Data

---

kork-exceptions/kork-exceptions.gradle
kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/ExceptionSummary.java
kork-exceptions/src/main/java/com/netflix/spinnaker/kork/exceptions/SpinnakerException.java
kork-exceptions/src/test/groovy/com/netflix/spinnaker/kork/exceptions/ExceptionSummarySpec.groovy

From https://github.com/spinnaker/clouddriver/pull/3972

feat(exceptions): Add standard exception summary model for service boundaries

---

spinnaker-dependencies/spinnaker-dependencies.gradle

Pick up suspend/resume APIs for Application Auto Scaling
Related to spinnaker/spinnaker#4707

chore(aws): Bump aws sdk

---

kork-plugins/kork-plugins.gradle
kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50UpdateRepositoryConfiguration.java
kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerPluginInfo.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/FileDownloaderProvider.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/front50/Front50Service.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/front50/Front50UpdateRepository.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/Front50UpdateRepositoryTest.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/downloader/FileDownloaderProviderTest.kt
kork-web/src/main/groovy/com/netflix/spinnaker/config/OkHttp3ClientConfiguration.groovy

I messed up my branch here https://github.com/spinnaker/kork/pull/469 and found it easier just to re-create the PR.
Closes spinnaker/spinnaker#5241

feat(plugins): Front50UpdateRepository and required configuration

---

kork-proto/src/main/proto/stats/log.proto

We would like to be able to track how users are installing Spinnaker and what version of those tools they're using. One example would be tracking which versions of halyard people are using to install Spinnaker in their environments.
We have some related work to do in a PR to echo to start propagating this information.

feat(telemetry): add deployment method and version to kork-proto

---

kork-proto/src/main/proto/stats/log.proto

List of deployment types updated based on Linux Foundation agreement.

fix(telemetry): update deployment type list to kork-proto

---

gradle/buildViaTravis.sh

I think this will work? If not I'll just cancel them all, I guess.

chore(build): disable autobump for tags on this branch

---

spinnaker-dependencies/spinnaker-dependencies.gradle

including important coroutines memory leak fix

chore(dependencies): bump some dependencies

---

kork-plugins/src/main/java/com/netflix/spinnaker/config/HttpClientSdkConfiguration.java

fix(plugins): Remove always false condition

---

spinnaker-dependencies/spinnaker-dependencies.gradle

Bump the version of retrofit2, in the hope that it resolves deadlock issue we're seeing in keel: https://github.com/spinnaker/keel/issues/951

deps: Bump retrofit2 version

---

kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/SpringStrictPluginLoaderStatusProvider.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/bundle/PluginBundleExtractor.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/SpringPluginInfoReleaseProvider.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/SpringStrictPluginLoaderStatusProviderTest.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/bundle/PluginBundleExtractorTest.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/SpringPluginInfoReleaseProviderTest.kt

These changes were meant to be part of https://github.com/spinnaker/kork/pull/564, I had some local commits I forgot to push 😬

fix(plugins): allow for relaxed plugin loading

---

kork-telemetry/src/main/java/com/netflix/spinnaker/kork/telemetry/InstrumentedProxy.java

Should fix https://github.com/spinnaker/spinnaker/issues/5571
If not, we'll have a little better exception to understand what's going on here.

fix(telemetry): Instrumented methods map should be concurrent

---

kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy

This change sets the compression settings on the additional tomcat connectors we create (i.e. on legacy and API ports)
Spring configures compression on the default connector, but not on additional ones.

fix(connectors): Apply compression to additional connectors

---

kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt

Firstly, this won't compile under Java 11. I believe `InetAddressCachePolicy` is available at runtime, so you could get it to work via reflection instead, but...
This doesn't feel like something an application developer should be setting. If you're concerned about DNS caching times, either set the TTL to 0 at the DNS level or configure this via JVM properties. Disabling DNS caching for the entire JVM is something that an operator should make a decision about, not us.
Obviously I'm happy to wait to submit this until you've had time to set the appropriate JVM properties in your deployments, but I figured I'd open a PR to start the discussion...

feat(dns): remove the DNS caching changes

---

kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClient.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientTest.kt

- Adding supplied request params to the URL.

fix(plugins): consider request params while building ok http client

---

spinnaker-dependencies/spinnaker-dependencies.gradle

This should fix spinnaker/spinnaker#5685

chore(jinjava): Upgrade jinjava

---

.detekt.yml
.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.github/workflows/release_info.sh
build.gradle
gradle.properties
gradle/kotlin-test.gradle
gradle/kotlin.gradle
gradle/wrapper/gradle-wrapper.properties
kork-bom/kork-bom.gradle
kork-proto/kork-proto.gradle
spinnaker-dependencies/spinnaker-dependencies.gradle

updates to gradle 6.3
updates github actions workflows for new release flags

chore(build): update to newer spinnaker project plugin

---

kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50PluginsConfiguration.java
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/EnvironmentServerGroupLocationResolver.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/EnvironmentServerGroupNameResolver.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/ServerGroupLocationResolver.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/ServerGroupNameResolver.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/internal/Front50Service.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/Front50PluginInfoReleaseSource.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/Front50PluginInfoReleaseSourceTest.kt

Depends on: https://github.com/spinnaker/front50/pull/791

feat(plugins): Adding server group plugin version pinning

---

kork-plugins/src/main/java/com/netflix/spinnaker/config/Front50PluginsConfiguration.java
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/EnvironmentServerGroupLocationResolver.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/update/EnvironmentServerGroupNameResolver.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/EnvironmentServerGroupLocationResolverTest.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/EnvironmentServerGroupNameResolverTest.kt

fix(plugins): Fix environment resolvers for front50 version pinning

---

kork-web/src/main/java/com/netflix/spinnaker/config/DefaultServiceEndpoint.java
kork-web/src/main/java/com/netflix/spinnaker/config/okhttp3/OkHttpClientProvider.java
kork-web/src/main/java/com/netflix/spinnaker/config/okhttp3/package-info.java

-- Adding package level annotations instead of repeating the annotation for every field and method args.

fix(misc): Add package level annotations

---

kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/proxy/aspects/MetricInvocationAspect.kt

fix(plugins): Use timer instead of PercentileTimer

---

kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/ExtensionConfiguration.java
kork-plugins-api/src/main/java/com/netflix/spinnaker/kork/plugins/api/PluginConfiguration.java
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/ConfigCoordinates.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/config/ConfigFactory.kt
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/dsl.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/DependencyInjectionTest.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/config/ConfigFactoryTest.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/config/SpringEnvironmentConfigResolverTest.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/PreferredPluginInfoReleaseSourceTest.kt
kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/release/source/SpringPluginInfoReleaseSourceTest.kt

This removes `@ExtensionConfiguration`.  If this general idea seems to make sense I'll clean this up and fix up docs and tests.

feat(plugins): PluginConfiguration annotation

---

kork-web/src/main/groovy/com/netflix/spinnaker/config/TomcatConfiguration.groovy

fix(startup): fix missed variable in cleanup

---

kork-proto/src/main/proto/stats/log.proto

This allows kleat to report itself as a deployment method.

feat(stats): Add kleat as a deployment method

---

kork-proto/src/main/proto/stats/log.proto

* whether or not Spinnaker is running under Kubernetes
* which artifacts were used to deploy Spinnaker
* the number of pipelines in this Spinnaker instance
* the number of pipelines in the event's application

feat(stats): add some additional stats data

---

kork-artifacts/src/test/java/com/netflix/spinnaker/kork/artifacts/model/ArtifactTest.java

I had wanted to make the metadata map an ImmutableMap as it is now immutable, but this caused some NPEs because it is possible to have metadata with null values. In order to exercise the current functionality, add some tests around what happens when you have null values in the metadata map.
At this point this PR will just add the tests so nobody makes the same mistake; I may come back later to filter out null values, then make the map immutable, but for now just adding the tests.

test(artifacts): Add some tests around null metadata values

---

kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/sdk/httpclient/Ok3HttpClientRegistry.kt

There's a bug in how `Ok3HttpClientRegistry` is building HTTP clients, but I haven't been able to figure it out just looking at the code. Figured there was opportunity here for some logs before I dive into doing stuff locally.

chore(plugins): Logging around HTTP client SDK internals

---

gradle.properties

Bump to latest Kotlin release﻿

Kotlin 1.4.10

---

kork-plugins/src/test/kotlin/com/netflix/spinnaker/kork/plugins/update/SpinnakerUpdateManagerTest.kt

We listen to these events and don't want them to get dropped in a future refactor...
Would it make sense to put these application events into the api package?

feat(test): test that downloading a plugin emits an event

---

spinnaker-dependencies/spinnaker-dependencies.gradle

Bump kotlinx-coroutines to 1.4.0﻿

chore(dependencies): update kotlinx-coroutines

---

spinnaker-dependencies/spinnaker-dependencies.gradle

Kotlin Coroutines 1.4.1

---

kork-retrofit/kork-retrofit.gradle
kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerNetworkException.java
kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitErrorHandler.java
kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java

Moved from clouddriver.  See https://github.com/spinnaker/clouddriver/pull/4325 + https://github.com/spinnaker/spinnaker/issues/5473.

feat(core): add SpinnakerRetrofitErrorHandler

---

kork-sql-test/src/main/java/com/netflix/spinnaker/kork/sql/test/SqlTestUtil.java

Keel recently started using foreign keys in its database and I've noticed intermittent CI failures caused by attempts to truncate tables that have foreign key references. Although `SqlTestUtil.cleanupDb` disables foreign key checks I think what we're seeing is Gradle running tests in `keel-sql` and `keel-web` concurrently. Both use testcontainers and will clean up after tests with `SqlTestUtil.cleanupDb`. I think what's happening is that one test finishes cleaning up while another has just started and re-enables foreign key checks. This PR tries to correct this by batching all the truncate commands and the commands that disable/re-enable foreign key checks. That way they should all execute atomically.

Batch truncate commands in cleanupDb

---

gradle.properties
spinnaker-dependencies/spinnaker-dependencies.gradle

Kotlin 1.4.21, Coroutines 1.4.2﻿

update kotlin and kotlinx-coroutines

---

kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/DefaultSqlConfiguration.kt
spinnaker-dependencies/spinnaker-dependencies.gradle

JOOQ is specified in the spring-dependencies BOM but we were already using a newer version﻿

update JOOQ and add jooq-kotlin

---

kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsAutoConfiguration.java
kork-plugins/src/main/java/com/netflix/spinnaker/config/PluginsConfigurationProperties.java
kork-plugins/src/main/kotlin/com/netflix/spinnaker/kork/plugins/v2/SpinnakerPluginService.kt

Configure via:
```
spinnaker:
extensibility:
proxyExtensions: true | false
```

feat(plugins): Add config property to enable/disable extension proxying

---

gradle.properties

chore(dependencies): Kotlin 1.4.32

---

build.gradle

see https://status.bintray.com/

chore(build): remove jcenter since it no longer exists

---

kork-plugins-tck/kork-plugins-tck.gradle
kork-plugins-tck/src/test/kotlin/com/spinnaker/netflix/kork/plugins/TestPluginGeneratorTest.kt
spinnaker-dependencies/spinnaker-dependencies.gradle

bumping strikt, since 0.28.0 isn't in maven central

fix(build): strikt bump to 0.31.0

---

.github/workflows/bump_dependencies.yml
.github/workflows/release.yml

* feat(build): bump dependencies for the given branch
* Update .github/workflows/bump_dependencies.yml
Co-authored-by: David Byron <82477955+dbyron-sf@users.noreply.github.com>
* chore(docs): adding comments
* chore(docs): updating language, adding TODOs
* feat(build): check for no branch and multiple branches
Co-authored-by: Cameron Motevasselani <cameron@armory.io>
Co-authored-by: David Byron <82477955+dbyron-sf@users.noreply.github.com>

fix(bumpdeps): point to maven central instead of bintray (#857)

---

kork-retrofit/src/main/java/com/netflix/spinnaker/config/RetrofitErrorConfiguration.java
kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitExceptionHandlers.java
kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerServerException.java
kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofitExceptionHandlersTest.java
kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/BaseExceptionHandlers.java
kork-web/src/main/java/com/netflix/spinnaker/kork/web/exceptions/GenericExceptionHandlers.java

See https://github.com/spinnaker/spinnaker/issues/6572 for background.

Handler for spinnaker server exception and spinnaker http exception

---

.github/workflows/release.yml
build.gradle
gradle.properties
kork-jedis-test/kork-jedis-test.gradle
kork-plugins/kork-plugins.gradle
spinnaker-dependencies/spinnaker-dependencies.gradle

fix(build): bump dependencies for the given branch (

---

kork-web/src/main/java/com/netflix/spinnaker/config/BinderControllerAdvice.java

Temporary mitigation for [RCE in Spring Core](https://bugalert.org/content/notices/2022-03-30-spring.html). Code from [here](https://www.praetorian.com/blog/spring-core-jdk9-rce/).

fix(spring): Mitigate RCE in spring-core

---

kork-moniker/kork-moniker.gradle

This change makes the project compatible with Gradle 7

chore(build): Gradle 7 compatibility

---

kork-proto/kork-proto.gradle
spinnaker-dependencies/spinnaker-dependencies.gradle

See https://github.com/spinnaker/clouddriver/pull/5752#issuecomment-1214587680 for background.

Protobuf cleanups

---

kork-expressions/kork-expressions.gradle
kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupport.java
kork-expressions/src/main/java/com/netflix/spinnaker/kork/expressions/config/ExpressionProperties.java
kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionTransformTest.java
kork-expressions/src/test/java/com/netflix/spinnaker/kork/expressions/ExpressionsSupportTest.java
spinnaker-dependencies/spinnaker-dependencies.gradle

**Usage**
```
expression:
do-not-eval-spel:
enabled: true
```
**References**:
* https://github.com/spinnaker/kork/pull/978
* https://github.com/spinnaker/orca/pull/4309

feat(spel): Add feature flag for DoNotEval SpEL.

---

kork-swagger/kork-swagger.gradle
kork-swagger/src/main/java/com/netflix/spinnaker/config/SwaggerConfig.java
spinnaker-dependencies/spinnaker-dependencies.gradle

Upgrading springfox fix vulnerabilities.
Followed the migration steps suggested [here](https://springfox.github.io/springfox/docs/current/#migrating-from-existing-2-x-version). 
Replaced guava based `com.google.common.base.Predicate` class with `java.util.function.Predicate` class and modified the logic to accommodate the same.
Note: This upgrade has introduced a breaking change where swagger-ui location has moved from http://host/context-path/swagger-ui.html to http://host/context-path/swagger-ui/index.html OR http://host/context-path/swagger-ui/ for short.
Dependency insight before the upgrade:
```
$ ./gradlew kork-swagger:dI --dependency swagger
> Task :kork-swagger:dependencyInsight
io.springfox:springfox-swagger-common:2.9.2
Variant compile:
| Attribute Name                 | …
```

chore(dependency): upgrade springfox documentation from 2.9.2 to 3.0.0

---

kork-retrofit/src/main/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerHttpException.java
kork-retrofit/src/test/java/com/netflix/spinnaker/kork/retrofit/exceptions/SpinnakerRetrofit2ErrorHandleTest.java

when available
followup to https://github.com/spinnaker/kork/pull/1149.

feat(retrofit): include the request method in SpinnakerHttpException messages

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
gradle.properties

chore(build): compile with JDK17
